### ISSUE TITLE
Can't find custom symbols on Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1035]
**Description of the problem**

When running the tests on Windows CI (#948), I see some scripts failing with errors like:
```
686/839 Test #689: psxy/custom_symbol.sh ...................***Failed    3.69 sec
psxy [ERROR]: Could not find either custom symbol or EPS macro D:A:/1/s/test/psxy/comet
psxy [ERROR]: Could not find custom symbol D:A:/1/s/test/psxy/comet
ERROR: gmtest:58
memtrack errors: 0
exit status: 1
ERROR: custom_symbol.sh:7
memtrack errors: 0
exit status: 1
```

The output of `gmt defaults -Vd` is:
```
gmt [DEBUG]: Obtained the ppid from parent: 5344
gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl
gmt [DEBUG]: GMT->session.SHAREDIR = D:/a/1/s/gmt-install-dir/share
gmt [DEBUG]: GMT->session.HOMEDIR = D:/a/1/s
gmt [DEBUG]: GMT->session.USERDIR = D:/a/1/s/.gmt [created]
gmt [DEBUG]: GMT->session.CACHEDIR = D:/a/1/s/.gmt/cache [created]
```

These directories all look good. But the path to search custom symbols is obviously wrong. Any idea how it happens? 

Refer to the [build log](https://dev.azure.com/GenericMappingTools/GMT/_build/results?buildId=1105) if you want to see more output.

**Comment by PaulWessel** [comment]
I suspect gmtinit_handle_dosfile in gmt_init.c. It temporarily replaces : with ; and then later back again in order to parse -B properly.  But don't see how it is called in the custom symbol context.  Not sure how D:/a/1 can become D:A:/1 otherwise.  There has to be some wrong logic somewhere in the code (gmt_init.c, gmt_io.c) where we have an unstated assumption of the dir name after X: being longer than 1.

**Comment by PaulWessel** [comment]
Is this another manifestation of minGW replacing /a with A: inside a path so that D:/a/ becomes D:A:/?

**Comment by PaulWessel** [comment]
From what you and @joa-quim described with minGW replacing stuff, here we are basically issuing this GMT call:

`gmt psxy -R0/20/10/30 -JM6i -P -Bag -W0.5p,red -SkD:/a/1/s/test/psxy/comet/2.5i -K -Xc -Yc > $ps
`

So if I understand correctly, minGW will examine this command and do its replacements, which in our case turns D:/a/ into D:A:
If that is true then we would need to build such defenses deep into the gmt i/o so that if we find two colons in a path X:Y:/ then the second Y: should be replaced with /y.

**Comment by seisman** [comment]
I don't think that is true. I created a file `C:\a\test.txt` and run some commands:

This command works
```
gmt psxy C:/a/test.txt -JX10c -R0/10/0/10 -Baf > test.ps
```

This command fails:
```
gmt psxy -R0/20/10/30 -JM6i -P -Bag -W0.5p,red -SkC:/a/test/2.5i -Xc -Yc > map.ps
psxy [ERROR]: Could not find either custom symbol or EPS macro C:A:/test
psxy [ERROR]: Could not find custom symbol C:A:/test
```

**Comment by PaulWessel** [comment]
Maybe you can add a printf (stderr, "-C arg is %s\n", opt->arg); instead the parsing for 'S' in psxy.c and see what it prints? If it has junk then we know it is minGW changing things before passing it in to psxy.

**Comment by seisman** [comment]
I added `fprintf(stderr, "###-S option: %s\n", opt->arg)` after line 758.
https://github.com/GenericMappingTools/gmt/blob/9d2e62a64c6bcc4e5a0c403dfd0dd253e13ed991/src/psxy.c#L757-L760

The output is:
```
###-S option: kC:A:/test/2.5i
```

Seems you're right.

**Comment by PaulWessel** [comment]
It is crazy but it seems consistent.  We have three functions (gmt_getsharepath, gmt_getdatapath, gmtlib_getuserpath) that takes a file name and finalizes the path (if it is a hard path it accepts it).  Perhaps we should insert some code like this in those three functions:

```
#ifdef WIN32
mingw_undo_path_substitution (path);  /* Undo any damage that MinGW may have made in the bash */
# endif
```

and then have

```
#ifdef WIN32
GMT_LOCAL void mingw_undo_path_substitution (char *path) {
    if (support_char_count (path, ':') == 2) {
        /* Replace X:Y: with X:/y */
    }
}
# endif
```

**Comment by seisman** [comment]
Looks a good solution to me.

**Comment by PaulWessel** [comment]
OK, submitted.  See if it works and perhaps fix anything stupid if it is not right.  It was only needed in gmtlib_getuserpath since full paths are not allowed in the others.

**Comment by seisman** [comment]
It seems the problem is more complicated.

```
gmt psxy -R0/20/10/30 -JM6i -P -Bag -W0.5p,red -SkC:/abc/test/2.5i -Xc -Yc > map.ps
psxy [ERROR]: Could not find either custom symbol or EPS macro C:C:/Program/Files/Git/abc/test
psxy [ERROR]: Could not find custom symbol C:C:/Program/Files/Git/abc/test
```

**Comment by PaulWessel** [comment]
Hah, so perhaps we do a two-pass: After what we just did, we check for X:X: and if so shift 2 to the left.  What you think?

**Comment by PaulWessel** [comment]
Oops, I see, so C:/abc/test became C:C:/Program/Files/Git/abc/test.  Can you tell if it would be correct if the double C: was removed?

**Comment by seisman** [comment]
I need some time to investigate the behavior of MinGW's path conversion. Actually, I'm confused why `gmt psxy C:/a/test.txt -JX10c -R0/10/0/10 -Baf > test.ps` works.

**Comment by PaulWessel** [comment]
Yes.  One difference is that C:/a/test.txt is probably determined to be an actual file, whereas -SkC:/abc/test/2.5i is just some text that has C:/ in it but otherwise not a file.  Perhaps it thinks the C:/ is the start of a path and since it cannot find C:/abc/test/2.5i it decides to do the replacement.

**Comment by PaulWessel** [comment]
At some point one must throw up arms and say if you want to work in that environment it is up to you to do double-slashes etc to get that not to be changed.  There is also the MSYS_NO_PATHCONV=1 environment parameter to try.

**Comment by joa-quim** [comment]
> C:C:/Program/Files/Git/abc/test

This reveals a second bug (I consider the current replacement behavior a bug). What it does is to replace the ``/`` (when it does it) by the Windows dir which is linked to seem to be the unix root dir. For example, I get ``C:C:/MinGW64/msys64/abc/test``. The other bug is that it transformed ``/Program Files/`` into ``/Program/Files``. I've never noticed this because I hate that directory and NEVER let anything that might be run from the command line be installed under ``c:\Program Files\``
 
I don't think there is anything we can do to cleverly undo that shit. But there is one solution that came out to me in my inspiration moment (the shower). Should have remembered this long ago. Use Windows paths

```
/c/v> gmt psxy -R0/20/10/30 -JM6i -P -Bag -W0.5p,red -SkC:\\abc\\test\\2.5i
psxy [ERROR]: Could not find either custom symbol or EPS macro C:\abc\test\2.5i
psxy [ERROR]: Could not find custom symbol C:\abc\test\2.5i
```

**Comment by joa-quim** [comment]
Curiously that solution works also in Winbubtu
```
j@MacMarilu:~$ gmt psxy -R0/20/10/30 -JM6i -P -Bag -W0.5p,red -SkC:\\abc\\test\\2.5i
psxy [ERROR]: Could not find either custom symbol or EPS macro C:\abc\test\2.5i
psxy [ERROR]: Could not find custom symbol C:\abc\test\2.5i
```
So this means we can change the tests with this issue to use ``\\`` and they will still work on unix.

**Comment by PaulWessel** [comment]
Doubt that very much:

ls \\Users\\pwessel
ls: \Users\pwessel: No such file or directory

**Comment by seisman** [comment]
I think it's impossible to undo mingw's path conversion.

For @joa-quim's case, both `C:/C/MinGW64/msys64/abc/test` and `C:/abc/test` are converted to `C:C:/MinGW64/msys64/abc/test`. We can't know the real path.

**Comment by PaulWessel** [comment]
I tend to agree.  Do we need to undo any of the gymnastics I added yesterday? I guess they don't help, but dont hurt either...

**Comment by seisman** [comment]
I suggest we discard PR #1069.

**Comment by seisman** [comment]
BTW, setting `MSYS_NO_PATHCONV=1` works.

**Comment by PaulWessel** [comment]
OK, can you help discarding PR #1069 as I don't know how...
If the MSYS setting works then perhaps that is something to document.  Did you try that with the WIndows tests?

**Comment by seisman** [comment]
Not yet. I will try if it works for the windows tests.

**Comment by seisman** [comment]
Setting MSYS_NO_PATHCONV=1 works for Windows tests.

**Comment by PaulWessel** [comment]
Should this issue be closed now?

**Comment by seisman** [comment]
OK. Let's close this.
