### ISSUE TITLE
Sessions have a too long memory

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1170]
``GMT_Create_Session()`` calls ``gmt_begin()`` that initialize the default config and reads (if any) users ``gmt.conf`` files (plus others). But while the session is alive no more reading of ``gmt.conf`` or ``gmt.history`` takes place. 

This is good and bad. Good because we can pass settings to modules via sessions but bad because further changes to ``gmt.conf`` via ``gmtset`` are ignored. Bad also because the ``--PAR=val`` mechanism, which is supposed to work on a one-command-only basis, in fact is stored in session and will be active until changed or the session deleted. This is in complete contradiction to the idea of ``--PAR=val``.

I dug a bit into this and tried this in ``gmt_end_module()`` (actually added it to 6.0 but as commented code) . At the beginning it seemed to work fine but then found that all examples that involve a call to ``psscale`` and a vertical shifts (like gallerie's ex02) somehow screw the postscript resulting in overlapping figs. Couldn't find the reason for that.
 
```
	if (GMT->parent->external) {
		gmtinit_conf (GMT);
		gmt_getdefaults (GMT, NULL);	// Re-read local GMT default settings (if any)
	}
```

**Comment by PaulWessel** [comment]
First, we should use a branch for this instead of commented code.  You raised two issues: 

1. gmtset has no effect after first gmt_begin.  This is not too serious I think but nevertheless a minor bug.  An alternate solution would be to have gmtset be aware it is called externally and have it re-read the gmt.conf before it exits.
2. The second issue with` --PAR=val` is more serious I think since we do want those settings to only live during the life of the module.  I see no obvious alternative to having a shadow defaults structure with the original before parsing, and then keep track of which items were changed via ` --PAR=val`, and then undo at the end of the module, only if called externally.

**Comment by joa-quim** [comment]
The commented code is very small (4 lines only) and easier to see than in a branch. And it doesn't work well enough anyway.
It tries to address the point 2. in a simple way. Calling ``gmtinit_conf (GMT);`` should reset all the defaults, which is what we want. The next call ``gmt_getdefaults`` should restore whatever is in ``gmt.conf``. But, as I said, in some cases it screws the PS.

**Comment by joa-quim** [comment]
I think I may have solved this in GMT.jl, where this concern was raised. So, close it.
