### ISSUE TITLE
Don't look for file w/e/s/n if w/e/s/n is legal data region

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1232]
**Full script that generated the error**

```
gmt begin map
gmt basemap -R0/10/0/10 -JX10c -Baf
echo 5 5 | gmt plot -Sc0.5c -Vd
gmt end
```

**Full error message**

```
gmt [DEBUG]: Modern mode: Added -R to options since history is available.
gmt [DEBUG]: Modern: Adding -J to options since there is history available.
psxy [DEBUG]: History: Process -R
psxy [DEBUG]: History: Process -J
psxy [DEBUG]: Look for file 0/10/0/10 in /Users/seisman/.gmt
psxy [DEBUG]: Look for file 0/10/0/10 in /Users/seisman/.gmt/cache
psxy [DEBUG]: Look for file 0/10/0/10 in /Users/seisman/.gmt/server
psxy [DEBUG]: Look for file 0/10/0/10 in /Users/seisman/.gmt/server/srtm1
psxy [DEBUG]: Look for file 0/10/0/10 in /Users/seisman/.gmt/server/srtm3
psxy [INFORMATION]: Processing input table data
```

**Description of the problem**

`0/10/0/10` is a proper data region. There is no need to check if it's a regular file.

**Comment by PaulWessel** [comment]
True, but we dont really know that yet since this is the sequence of steps taken by gmt plot in this script:

1. Notice there is no **-R** given.
2. Determine that there is a **-R** given in history.
3. Obtains that history and creates a new option **-R** with no arguments.
4. Now process the input arguments and find **-R**.
5. Expand any common option that may have history; this adds 0/10/0/10 string to **-R**.
6. Process **-R**0/10/0/10 form scratch: It may be a file so first check if we can access it.  This is what you are seeing.
7. If not a file, then parse as w/e/s/n, etc.


We do it in that order to ensure we never miss a file given as an argument to **-R**.

So, I think this issue can be closed.

**Comment by PaulWessel** [comment]
In other words, we do not keep track in the gmt.history what the -R is.  It is treated as just a string that needs to be parsed again.  To avoid the extra checking there would have to be some further information stored in the gmt.history that would let us know 0/10/0/10 is a region and not a file..
