### ISSUE TITLE
gmt which without -G doesn't work as expected

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1278]
```
# cleanup GMT server directory
$ rm -r ~/.gmt/server

# file not found, and not downloaded
$ gmt which @earth_relief_30m
gmtwhich [ERROR]: File @earth_relief_30m.grd not found!

# download the remote file 
$ gmt which @earth_relief_30m -Gu
earth_relief_30m: Download file from the GMT ftp data server [data set size is 377K].
earth_relief_30m: Earth Relief at 30x30 arc minutes obtained by Gaussian spherical filtering (55 km fullwidth) of ETOPO1 (Ice g) [NOAA].

/Users/seisman/.gmt/server/earth_relief_30m.grd

$ gmt which @earth_relief_30m -Gu
/Users/seisman/.gmt/server/earth_relief_30m.grd

# should report the file path
$ gmt which @earth_relief_30m
gmtwhich [ERROR]: File @earth_relief_30m.grd not found!
```

**Comment by PaulWessel** [comment]
Per the documentation, gmt which @earth_relief_30m should fail because -G is not given so it does not try to download, and earth_relief_30m does not exist locally as a file since no extension.  The 0G is required to activate the curl operation.

However, this seems to be a problem:

gmt which @earth_relief_30m.grd
gmtwhich [ERROR]: File @earth_relief_30m.grd not found!

In this case it should strip off the @ and look, but instead it tries to find that file starting with '@'.

I propose that without -G we strip off any starting '@' characters, but otherwise require -G to do curl.

**Comment by seisman** [comment]
> I propose that without -G we strip off any starting '@' characters, but otherwise require -G to do curl.

Looks good to me.

BTW, the documentation says:

```
The $GMT_USERDIR and $GMT_DATADIR environment variables can be colon-separated 
list of directories.
```

The path separator should be comma now.

**Comment by seisman** [comment]
> gmt which @earth_relief_30m
