### ISSUE TITLE
gmt_fill_syntax et al. should allow a string as an option

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1309]
**Description of the desired feature**

Function `gmt_fill_syntax` is defined as 
```
void gmt_fill_syntax (struct GMT_CTRL *GMT, char option, char *string)
```
It only accepts a single character as the second argument.

Sometimes, we need to specify a *fill* in a modifier (e.g. `-F+g<fill>`) or as part of the argument (e.g. `-Fe<fill>`). In these cases, passing a single-character option gives inacurrate error messages, like:

```
$ gmt meca meca.dat -R239/240/34/35.2 -Jm4c -Sa1c -Feblu -pdf test   
psmeca [ERROR]: Colorname blu not recognized!
psmeca [ERROR]: Syntax error -e option.  Correct syntax:
	-e<fill>   Specify <fill> as one of:
	   1) <gray> or <red>/<green>/<blue>, all in the range 0-255;
	   2) <c>/<m>/<y>/<k> in range 0-100%;
	   3) <hue>-<sat>-<val> in ranges 0-360, 0-1, 0-1;
	   4) any valid color name;
	   5) P|p<pattern>[+b<color>][+f<color>][+r<dpi>];
	      Give <pattern> number from 1-90 or a filename, optionally add +r<dpi> [300].
	      Optionally, use +f,+b to change fore- or background colors (set - for transparency).
	   For PDF fill transparency, append @<transparency> in the range 0-100 [0 = opaque].
```

Other `gmt_*_syntax` functions may have the same problem.

We can extend these functions and allow them accept a string as the second argument.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
I agree, but we need a clever solution since we often pass opt->option (a char) as that second arguments and if we made it char * then I don't think we can pass &opt->option, etc.  Maybe we need a 3rd argument char *longoption that, if not NULL, is used instead of the option char?  That way we could replace all gmt_fill_syntax by first inserting NULL as the new 3rd argument, and then modify the function to consult that arg internally when it prints, then slowly fix the gmt_fill_syntax calls where modifier fill is used?

**Comment by seisman** [comment]
`char *longoption` looks good.
