### ISSUE TITLE
subplot tag position issue

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1355]
See script and figure below. Adding `-A` option to `subplot begin` will place tags at the TL corner.
```
gmt begin map
gmt subplot begin 2x2 -Fs5c/5c -BWSen
    gmt subplot set 0 -A'(a)'
    gmt basemap -R0/10/0/10 -JX11.75c/5c -Baf

    gmt subplot set 2 -A'(b)'
    gmt basemap -R0/10/0/10 -JX? -Baf

    gmt subplot set 3 -A'(c)'
    gmt basemap -R0/10/0/10 -JX? -Baf
gmt subplot end
gmt end show
```

![image](https://user-images.githubusercontent.com/3974108/62811115-8346df00-bace-11e9-8e42-743cf8815514.png)

**Comment by PaulWessel** [comment]
So the way it is meant to work is that you use the begin -A to indicate that you want auto-tagging and it sets the location and justification, etc etc.  The set -A is just a plain string that replaces what would otherwise be plotted.  So I think you need to add -A at the begin otherwise it is user error.

**Comment by seisman** [comment]
Fair enough.
