### ISSUE TITLE
Incorrect annotations for polar projection -JP

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1432]
Command:
```
gmt begin polar png
gmt basemap -JPa5c -R0/360/0/1 -Bxa45f 
gmt end show
```
Output:
![image](https://user-images.githubusercontent.com/3974108/63486637-5c958a80-c476-11e9-84a4-698a3847468c.png)

Strictly speaking, polar projection is not a geographic projection. It doesn't make much sense to have annotations from -180 to 180 while 0-360 is used in -R.

**Comment by PaulWessel** [comment]
Hm, yes you are correct it is not geographic data, but I am not so sure if anyone might be making a plot of longitude versus some radius and they would like those longitudes to be ±180 instead of 0-360.  It would be harsh for us to refuse that by hardwiring it to 0-360, no? You can always add  --FORMAT_GEO_MAP=+D to get the 0-360.

**Comment by seisman** [comment]
If anyone want to have longitudes to be ±180, they may need to use **-fg** to indicate geographic data?

**Comment by PaulWessel** [comment]
Dont think so, the projection is still periodic so -90 and 270 is still in the same direction.  I just needed FORMAT_GEO_MAP=+D to get the labels 0-360.

**Comment by seisman** [comment]
OK. We can claim it as a feature.
