### ISSUE TITLE
Missing coast -B option causes psconvert error ？

### ISSUE THREAD

**Issue by ZMAlt** [GenericMappingTools/gmt#1462]
```
gmt begin map pdf
R=110/120/10/20
J=Q4i
gmt coast -R$R -J$J -Gwhite 
gmt end


psconvert [ERROR]: Unable to decode BoundingBox file /Users/xxx/.gmt/sessions/gmt6.26801/psconvert_27270c.bb
```
add -B option, no error 

* Operating system: macOS
* Version of GMT: gmt rc3

**Comment by PaulWessel** [comment]
Your particular call plots a few white polygons on a white background, resulting in a white plot with no features.  It seems the ghostscript boundingbox operator does not sense the difference between areas not plotted and white.  I am not sure if it is a gs bug or not.  However, your plot is nonexistant since it is all white.  I would agree that if you made a transparent PNG from this it would show white and transparency elsewhere, but we may not get there if the BB cannot be computed.  Change -Gwhite to -Gred and you can see something.

**Comment by ZMAlt** [comment]
Yes. I do see something when I change -Gwhite to -Gred. Thank you!
