### ISSUE TITLE
ex45 is broken

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1631]
gm diff image:
![image](https://user-images.githubusercontent.com/3974108/65429466-3734cd00-dde4-11e9-9203-804ecd106834.png)

**Comment by PaulWessel** [comment]
Probably because I updated the data file to go to 2019.  Yet, not failing here...

**Comment by PaulWessel** [comment]
Also, need to reinstall older Xcode to debug since Xcode 11 expects the next OS version...

**Comment by PaulWessel** [comment]
We have a problem in that the gmt_check_filearg function in the local parsers determines that a remote @file is cache file so it skips to position 2 to avoid the @ sign, but then calls gmt_access to see if the file is already there and of course it is.  Thus, it does not check hash codes etc, which explains why my ex45 works (using old file) and yours (getting new file) breaks.
If you can upload a new ex45 ps orig file then I will try to fix this problem.  We need to inject that check for hash ahd size as we do in other places, such as grids.  I think this problem is limited to command line file args (which is a log).

**Comment by PaulWessel** [comment]
Need to test this tomorrow when my hash file is > 24 hrs to make sure it really works.  I will make a small change to a file on the server and update the hash code and then we will see.  Leave this open until then.

**Comment by PaulWessel** [comment]
It seems that check to gmt_access should only happen when no leading @ was given - otherwise it can never get to the code that compares sizes and hash codes.

**Comment by PaulWessel** [comment]
This issue should now be fixed via #1637.  Closing.
