### ISSUE TITLE
3D bars out of place?

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#185]
We have example 8 that looks correct, but I don't see what (if) I'm doing wrong here:

```
grdmath -R-2/2/-2/2 -I0.1 X Y R2 NEG EXP X MUL = lixo.grd
grd2xyz lixo.grd | psxyz -So0.03u+b-0.45028042 -R-2.05/2.05/-2.05/2.05/-0.4288/0.4288 -JX12c -JZ6c -Baf0.1 -Bza -BWSZ -G0/115/190 -p200/30 -Wthinnest -P > lixo.ps
```
As we see, the bars are clearly out of place. Note that grid is grid registered but psxyz's -R is pixel reg so the bars should be centered on the tick marks.
Another non shown issue is that if one omits -G we get black bars and not the non-filled that is mentioned in psxyz -G doc.

![capture](https://user-images.githubusercontent.com/537321/48740120-16449e00-ec4e-11e8-9282-ae1d70ffb089.JPG)

**Comment by PaulWessel** [comment]
Doesn't matter if your -R is "pixel registered", the coordinates from the
grid are what they are.  You would have to fake a phase shift in -B if you
want ticks to line with columns I think.

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa


On November 19, 2018 at 12:55:24 PM, Joaquim (notifications@github.com)
wrote:

We have example 8 that looks correct, but I don't see what (if) I'm doing
wrong here:

grdmath -R-2/2/-2/2 -I0.1 X Y R2 NEG EXP X MUL = lixo.grd
grd2xyz lixo.grd | psxyz -So0.03u+b-0.45028042
-R-2.05/2.05/-2.05/2.05/-0.4288/0.4288 -JX12c -JZ6c -Baf0.1 -Bza -BWSZ
-G0/115/190 -p200/30 -Wthinnest -P > lixo.ps

As we see, the bars are clearly out of place. Note that grid is grid
registered but psxyz's -R is pixel reg so the bars should be centered on
the tick marks.
Another non shown issue is that if one omits -G we get black bars and not
the non-filled that is mentioned in psxyz -G doc.

[image: capture]
<https://user-images.githubusercontent.com/537321/48740120-16449e00-ec4e-11e8-9282-ae1d70ffb089.JPG>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GenericMappingTools/gmt/issues/185>, or mute the thread

**Comment by joa-quim** [comment]
Yes, but exactly because coordinates are what they are that the lower left column should be at (-2,2). Centered on that point or with origin at it, though that's a separate issue, but never outside the axes as it happens in this case.

**Comment by PaulWessel** [comment]
OK, make a new test with one or two columns only that should plot at -2,-2 etc so it is clear.

**Comment by joa-quim** [comment]
OK. This works fine
```
grdmath -R0/2/0/2 -I1 X Y R2 NEG EXP X MUL = lixo.grd
grd2xyz lixo.grd | psxyz -So0.85u/0.85u+b0 -R-0.5/2.5/-0.5/2.5/0/0.367879450321198 -JX12c -Baf0.5g1 -Bza -BWSENZ -JZ6c -G0/115/190 -p200/30 -Wthinnest -P
> lixo1.ps
```
![lixo1](https://user-images.githubusercontent.com/537321/48744753-70e6f580-ec60-11e8-84bc-f5a279140c2c.png)

but now, between [-1 1], columns start to *fall* trough the south borther
```
grdmath -R-1/1/-1/1 -I1 X Y R2 NEG EXP X MUL = lixo.grd
grd2xyz lixo.grd | psxyz -So0.85u/0.85u+b-0.38627342 -R-1.5/1.5/-1.5/1.5/-0.367879450321198/0.367879450321198 -JX12c -Baf0.5g1 -Bza -BWSENZ -JZ6c -G0/115/190 -p200/30 -Wthinnest -P > lixo2.ps
```
![lixo2](https://user-images.githubusercontent.com/537321/48744779-9673ff00-ec60-11e8-9f47-7801da1de9cc.png)

**Comment by PaulWessel** [comment]
Time to close this issue?

**Comment by joa-quim** [comment]
Right. Those commands were generated by the Julia wrapper. Must see why the -S+b and z_min are not equal.
