### ISSUE TITLE
gmt docs which doesn't work

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1897]
`gmt docs gmtwhich` works but `gmt docs which` doesn't work.

**Comment by PaulWessel** [comment]
None of the gmt_name_ work as gmt docs _name_.

**Comment by seisman** [comment]
Right, is it possible to allow that?

**Comment by PaulWessel** [comment]
The problem is that for the plotting functions we have both pscoast.html and coast.html. So we handle modern and classic names.
We have no similar scheme for handing URLs to long and short gmt modules that start with the word gmt.  It has difficult to know when to prepend gmt without  function telling me to do so.  WIll have a look.

**Comment by PaulWessel** [comment]
Need a solution for this problem.  If I want gmtconvert and I type convert I can make that into gmtconvert.  However, if I type defaults I currently am getting gmt.conf since we made defaults a valid alias for gmt.conf.  Maybe we need to think of another alias that is not also a module.  Maybe _settings_?

**Comment by seisman** [comment]
I don't think users really know what "settings" mean in GMT. It's even worse that new GMT users may even don't know gmt.conf, since they're using modern mode.

**Comment by PaulWessel** [comment]
We certainly discuss GMT default settings throughout the docs, and here and there refer to it by name (e.g., **PROJ_LENGTH_UNIT**).  We may even say see the gmt.conf page.  So using _defaults_ or _settings_ for _GMT default settings_ seem somewhat arbitrary anyway.  Picking _settings_ makes this unique.  We still honor gmt docs gmt.conf.

**Comment by seisman** [comment]
OK, sounds good.
