### ISSUE TITLE
Inconsistent module purpose in codes and docs

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1934]
The module purposes are used in many places:

1. in the C code of each module (i.e. `THIS_MODULE_PURPOSE` macro)
2. in `gmt_core_module.c` and `gmt_supplements_module.c`
3. in each module's manpage
4. in the modern mode module list
5. in the classic mode module list

Currently, we can update `gmt_core_module.c` and `gmt_supplements_module.c` by running the script `gmt_make_module_src.sh`. But for the rst files, we have to update them manually. 

Here is my suggestion:

1. Create a file module_purpose.rst_ in doc/rst/source directory. The content of the file looks like:
```
.. |psxy_purpose| replace:: Plot lines, polygons, and symbols

.. |plot_purpose| replace:: Plot lines, polygons, and symbols
```
It's possible to update this file automatically by writing a script like `gmt_make_module_src.sh`.

2. In the documentation, include `module_purpose.rst_` and use `|psxy_purpose|` if the purpose of psxy is needed.

**Comment by PaulWessel** [comment]
I agree with something like this. Note that THIS_MODULE_PURPOSE is the same as what is in the gmt_*_module.c since that is what gmt_make_module_src.sh does.  But we did not tie that in with the man pages and the module list.  Seems like the module_purpose.rst_ should be created by gmt_make_module_src.sh since it is the same steps.  Do we make seaprate module_core_purpose.rst_ and supplements/module_suppl_purpose.rst_ files for this since there are different levels in the directories?

**Comment by seisman** [comment]
I think it makes sense to let `gmt_make_module_src.sh` generate seaprate module_core_purpose.rst_ and supplements/module_suppl_purpose.rst_.

**Comment by PaulWessel** [comment]
OK, done in branch modernsort which adds the two rst_ files.  Any magic that can be done to actually use these?

**Comment by seisman** [comment]
I pushed one commit to modernsort branch, showing how it works. I think I can write a script to do the replacement.

**Comment by PaulWessel** [comment]
That would be great.

**Comment by seisman** [comment]
Done in branch modernsort.
