### ISSUE TITLE
Modern mode: specifying grids

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#1994]
In modern mode, wouldnt it be nice if GMT also remembered the grid being used? We dont need to specify e.g. ``-R`` more than once. Why not do the same with input grids?

Today:

```
gmt begin map pdf
	gmt grdimage @earth_relief_30m -R-5/53/90/81r -JU+34/20c -t50
	gmt grdcontour @earth_relief_30m -C+-500  -Q100
gmt end
```

Suggestion:
```
gmt begin map pdf
	gmt grdimage @earth_relief_30m -R-5/53/90/81r -JU+34/20c -t50
	gmt grdcontour -C+-500  -Q100
gmt end
```

I.e. no need to specify input grid more than once (if the same is to be used). If another grid is to be used, then it is specified.

**Comment by joa-quim** [comment]
Interesting, but it would be a breaking change.

**Comment by PaulWessel** [comment]
Hm, how is it breaking anything?

**Comment by joa-quim** [comment]
Right, not exactly a break because nothing from the past would stop working. But also not exactly like a new option that can only be used if installed version allows it. In this case a use could see an example like the one above but his version would not know how to use it and simply error for a apparently unknown reason.

**Comment by PaulWessel** [comment]
But is not that true of any new feature attempted to be run with an older version?  You will get errors since that feature is not supported in an older version.  It is like trying to use -l for legends in GMT5.

**Comment by seisman** [comment]
I don't see any benefits to remember the grid. Is it just for saving a few keystrokes?

**Comment by joa-quim** [comment]
Almost, but when you try to use **-l**, you'll get an error message saying *-l option is unknown* whilst in this case one would see something like *grdcontour error you must provide a grid to work on*. That is, no info that a newer version would accept this syntax.

But I'm not against this feature. Just pointing that it can lead to more incomprehensible error messages. 

Just saw Dongdong's comment. For me it's not about the keystrokes (it never is) but if it contributes to make the scripts look shorter and simpler.

**Comment by abanbj** [comment]
Isn't one of the main purposes of modern mode to save keystrokes? I don't see how this is different from the convenience that ``-R`` only has be typed once. But, I do understand the potential confusion.

**Comment by joa-quim** [comment]
Saving keystrokes is not the main purpose (see the longoptions idea), but simplifying and making scripts more human readable, is.

**Comment by PaulWessel** [comment]
It is an interesting suggestion, @abanbj, so we are debating it.  One objection might be that the same scheme cannot be done for table data since those modules expect to read from _stdin_ if no file is given.  So if we implemented it for grids we might have people doing this

```
gmt plot mydata -Sc0.1i
myprocess | gmt plot -W1p
```

and get frustrated that the second plot is still plotting mydata and ignoring stdin, for instance.

**Comment by abanbj** [comment]
Yes, I understand. Maybe some things are best said explicitly.

**Comment by PaulWessel** [comment]
I think there are more negatives than positives for this.  I particularly find my own objection that points out the different handling of different types of datasets problematic (!).  So I think we will need to reject this proposal.

**Comment by abanbj** [comment]
Glad we could discuss it! Closing.
