### ISSUE TITLE
Auto legend and height of legend box

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#1998]
The width of the automatic legend box adjusts good, but the height may be very off, depending on symbol size.

```
gmt begin map pdf
        gmt pscoast -R-5/53/90/81r -JU+34/20c -W -Dl
        echo 0 60 > 1.gmt
        echo 15 60 >> 1.gmt
        gmt psxy -W1c -l"Line" 1.gmt
        gmt psxy -Sc1.5c 1.gmt -Gred -l"Point"
        rm 1.gmt
gmt end
```

**Comment by PaulWessel** [comment]
True, but the same happens in classic mode pslegend calls.  You would have to change the linespacing or the annotation font to match the larger symbols.  If you insert this line before gmt end you will see the effect:

`	gmt set FONT_ANNOT_PRIMARY 36p
`

I am not sure what the best solution is here but the linespacing in the legend (distance between sets of symbols and their labels is given by the primary annotation font size times the line-spacing factor set via **-D+l**, which defaults to 1.1 and cannot be changed when doing auto-legend.

We could find the largest symbol plotted and if larger than will fit on a line then warn, since not sure if scaling the font size _or_ increasing the linespacing are necessarily good ideas.

**Comment by abanbj** [comment]
Ah, I see. No need to complicate. You can always go _true legend_ if needed. Thanks Paul. Closing.
