### ISSUE TITLE
Add more useful targets for gmt docs

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2013]
`gmt docs` can open a module's documentation using the default browser. Besides the module names, some special targets are also supported:

- gmt
- cookbook
- gallery
- settings
- api
- tutorial

@PaulWessel proposed to allow `gmt docs home` or `gmt docs website` to open the GMT homepage (https://www.generic-mapping-tools.org/).

Any suggestions for other useful targets?

**Comment by PaulWessel** [comment]
Maybe data could open the Dataset page.

**Comment by seisman** [comment]
I'm a little hesitating to add more special targets to "gmt docs". To me, the targets I need is "forum" (https://forum.generic-mapping-tools.org/), "homepage" (https://www.generic-mapping-tools.org/), and the "documentation landing page" (https://docs.generic-mapping-tools.org/).

The target to the "Dataset" page may be unnecessary. Users can always open the documentation page first (via "gmt docs doc" or something similar), then find Dataset page from the left sidebar.

**Comment by PaulWessel** [comment]
I agree that dataset is not critical.  I find myself very often needing to open either our main site.  The forum I usually go to by responding to an email with an issues, and the top doc page I go to indirectly via a module then click on sidebar, so that would be useful.  I am not super-sure about what to call the targets.  I listed website and you listed homepage; both are kind of long.  What do you and @joa-quim think about these:

1. gmt docs _home_  [Go to the "home" of the docs - i.e., the top documentation site]
2. gmt docs _forum_  [Go to the user Discourse forum]
3. gmt docs _website_|_site_|_@_ [Goes to the GMT URL]

**Comment by joa-quim** [comment]
If by *target* one mean the *keyword* we can add to ``gmt docs xxxx`` then I think *data* is a good one. Having several is not distracting anyway. I do blind trials when I don't remember what exists.

**Comment by PaulWessel** [comment]
I tried gmt docs solve-my-problem and it failed miserably.

**Comment by PaulWessel** [comment]
To resolve this issue, I think these are not too shabby:

- gmt docs forum: Go to forum
- gmt docs data: Open the dataset page

We need to more targets: the top documentation page and the website.  I feel the target home is ambiguous.  gmt docs home sounds like the home page of the documentation rather than the gmt website.  Is that how you see it too? If so, then maybe that is OK and we can use gmt docs website for the website?

**Comment by seisman** [comment]
> To resolve this issue, I think these are not too shabby:
> 
> * gmt docs forum: Go to forum
> * gmt docs data: Open the dataset page

These two are good for me.

> I feel the target home is ambiguous. gmt docs home sounds like the home page of the documentation rather than the gmt website. 

I have the exact same feeling.

> Is that how you see it too? If so, then maybe that is OK and we can use gmt docs website for the website?

I don't have other better words, so `gmt docs website` is OK to me.

**Comment by joa-quim** [comment]
``website`` or just ``site`` is good for me too
