### ISSUE TITLE
Filling polygon can't handle shitty data points

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2194]
This example came out of a shapefile. If you look at the end of the file there is a pair of NaNs followed by some noise around a single point. A data problem for sure, but ``psxy`` without filling handles it (probably plots a single point). However if we add a fill then this happens

```
gmt psxy -JX12c -Baf -BWSen -R604000/610000/4508000/4516000 -Ggreen -W1 shitty.dat -png map
```

![map](https://user-images.githubusercontent.com/537321/69916555-44111500-1454-11ea-8018-bc3e2c6143d0.png)
 

[shitty.zip](https://github.com/GenericMappingTools/gmt/files/3908393/shitty.zip)

**Comment by PaulWessel** [comment]
If I tell GMT to just skip NaN records, i.e.,

```
gmt plot -JX12c -Baf -BWSen -R604000/610000/4508000/4516000 -Ggreen -W1 shitty.dat -png map --IO_NAN_RECORDS=skip
psxy [ERROR]: Encountered first invalid ASCII data record near/at line # 202
psxy [ERROR]: Likely causes:
psxy [ERROR]: (1) Invalid x and/or y values, i.e. NaNs or garbage in text strings.
psxy [ERROR]: (2) Incorrect data type assumed if -J, -f are not set or set incorrectly.
psxy [ERROR]: (3) The -: switch is implied but not set.
psxy [ERROR]: This file had 1 data records with invalid x and/or y values
```

I get a better plot:

![map](https://user-images.githubusercontent.com/26473567/69924962-03180100-1452-11ea-99ba-9c9f7548f0c7.png)

Brings up a few somewhat unrelated points:

- Since GMT continues and makes a plot, probably should not be ERROR messages? But then, would require -V to see them as warnings.
- The error message still reports psxy even though I ran plot. I thought I fixed that but apparently now ;  must debug.
- Why are the NaN NaN record giving a plowable coordinate (I assume 0,0)?

**Comment by joa-quim** [comment]
- ``should not be ERROR messages? But then, would require -V to see them as warnings.`` Right, it should be a WARNING. The **-V** issue is a more general one. I think that there are many warnings that should not need **-V** to be printed.
- Yep, some shit makes the line go to LL corner. It's not (0,0), it's just the figure's origine
- Another issue is that you told it to skip NaNs but it still complains about the bad point.

**Comment by PaulWessel** [comment]
We overhauled the messages not long ago.  There are errors, warnings, information, compatibility, and debug.  I think it is tricky to separate warnings into two kinds of warnings, i.e., those we think users must see and those we think are not that important.  It would be messy.
I still think it is OK with -V and skip nans to display that message.
