### ISSUE TITLE
Annotations for automatically generated CPT

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2307]
See the script and output below:
```
gmt begin map png
gmt grdimage @earth_relief_20m -JH15c -Rg -Baf -BWSen
gmt colorbar
gmt end show
```

![image](https://user-images.githubusercontent.com/3974108/71283463-4f0de580-232e-11ea-952a-13d0073c86d6.png)

**Comment by PaulWessel** [comment]
So the bar is scaled to fit the data range, and when that happens we normally want to use -B to get sane intervals.  On the other hand, the default is to annotate the boundaries as given in the CPT.  I guess we need to know if the cpt was stretched and hence we should instead default to -B.

**Comment by PaulWessel** [comment]
In terms of detecting that we have this case, perhaps we can do so by examining the z-levels? I.e., if they are not equidistant and not integers? but may not be what users want.  Seems like we need to remember that we automatically stretched the CPT to fit a data range, not a user-specified range? If someone did `gmt makecpt -Cgeo -T-9000/9000` then that is different from just using a grids min/max. The autostretch happens in grd2kml, grdimage, grdvector and grdview.  These have a **-C**...[**+i**dz] that can be used to round the CPT rather than use the raw min/max. Perhaps if _dz_ == 0 (not given) we will want to pass that information to the CPT so when it is used (by colorbar) we know we should do -B if no -B was given?
Alternatively, we could just decide that in modern mode all colorbar calls without **-B** gets **-Baf**.

**Comment by seisman** [comment]
> Alternatively, we could just decide that in modern mode all colorbar calls without **-B** gets **-Baf**.

No, users may write their own CPT and want to annotate it in the same as what CPT does.

> The autostretch happens in grd2kml, grdimage, grdvector and grdview. These have a **-C**...[**+i**dz] that can be used to round the CPT rather than use the raw min/max. Perhaps if _dz_ == 0 (not given) we will want to pass that information to the CPT so when it is used (by colorbar) we know we should do -B if no -B was given?

I think this is a better solution.
