### ISSUE TITLE
Give credits to contributors by adding them to AUTHORS.md

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2330]
We encourage more contributors to help maintain and improve GMT. For these contributors, I think we should give them credits by adding them to AUTHORS.md. Or they can choose to add themselves to AUTHORS.md when submitting a PR.

We already have a section "Further Acknowledgments" in AUTHORS.md, but it's a long paragraph. Maybe better to change it to a list of names.

**Comment by weiji14** [comment]
Just a suggestion to use https://allcontributors.org/ (see example at https://github.com/pyproj4/pyproj/). I feel that some contributors can be quite shy to open up a PR to add their name so it might be nice to have a maintainer do it like so:

![Add contributor automatically using bot](https://user-images.githubusercontent.com/23487320/71563982-7ff3d480-2afd-11ea-91e6-69ad74b398c3.png)

The bot defaults to using the README.md, but I see that it can be configured to use the AUTHORS.md file instead. It might take a bit of time to set up, but I think it'll work nicely in the long run to acknowledge not just code/documentation writers but also translators, bloggers, event organizers, [etc](https://allcontributors.org/docs/en/emoji-key)

**Comment by seisman** [comment]
allcontributors looks nices, but it uses a lot of raw HTML codes, and makes the **raw** README/AUTHOR.md unreadable.

**Comment by leouieda** [comment]
One thing to keep in mind is that some people may not want to be added, so it's important to check before adding anyone.

We just adopted the following guidelines for my geophysics modelling packages: https://github.com/fatiando/contributing/blob/master/AUTHORSHIP.md That set's out how we acknowledge people on different levels: the AUTHORS.md file, the changelog, authorship on Zenodo archives, and authorship on papers. These might be a good starting point for GMT as well.

**Comment by seisman** [comment]
> One thing to keep in mind is that some people may not want to be added, so it's important to check before adding anyone.

I agree with @leouieda, so we won't add any names to the `AUTHORS.md`. 

Instead, we should let contributors know that they are welcome to **add themselves** to the AUTHORS.md file if they want. This is exactly how we do in the PyGMT project (https://github.com/GenericMappingTools/pygmt/blob/master/AUTHORS.md).

The problem is that, the current AUTHORS.md has a long paragraph for "Acknowledgments". If I were a new contributor and would like to add my name to AUTHORS.md, I would have no idea where to put my name.

I think we can choose either option:

1. Change the "Further Acknowledgments" paragraph to a list of names (alphabetically sorted by last name)
2. Don't change the "Further Acknowledgments" section, but add a new section "Contributors".

**Comment by meghanrjones** [comment]
I think that improvements to the cookbook and tutorial are two of the easier places for new contributors to get involved with GMT development. To me, it seems that the authorship structure for these two documents could be made more welcoming. It's important to recognize the years to decades that the seven people included in the front pages of the [tutorial](https://docs.generic-mapping-tools.org/dev/tutorial.html) and [cookbook](https://docs.generic-mapping-tools.org/dev/cookbook.html) have spent developing these resources, while still providing a clear path for new contributors to be acknowledged for their efforts.

Here are two options that I think could help clarify GMT's authorship structure:

1. Keep the current structure of listing authors in [AUTHORS.md](https://github.com/GenericMappingTools/gmt/blob/master/AUTHORS.md), [the cookbook front page](https://docs.generic-mapping-tools.org/dev/cookbook.html), and the [tutorial front page](https://docs.generic-mapping-tools.org/dev/tutorial.html), but add information to [CONTRIBUTING.md](https://github.com/GenericMappingTools/gmt/blob/master/CONTRIBUTING.md) with the process for contributors to be added to those documents (this is similar to @seisman's suggestion from https://github.com/GenericMappingTools/gmt/issues/2330#issuecomment-690842315). An essential component of this option is deciding at what point a contributor becomes an 'author' of the GMT documentation.
2. Restructure the authorship acknowledgements using a format similar [Numpy's team gallery](https://numpy.org/gallery/team.html). I think this would work best if combined with the addition of a governance document that explains how people get added to different teams.

I prefer option 2, because in my opinion it better reflects the opportunities to become involved relative to a publication-type authorship list. The sections for the team gallery could include 'GMT Founders', 'GMT 4 Core Developers', ' GMT 5 Core Developers', 'GMT 6 Core Developers', 'Supplement Developers', and 'Documentation Team'. Note that in the numpy example, there is also a separate [THANKS.txt](https://github.com/numpy/numpy/blob/main/THANKS.txt) which seems similar to some of the mentions in GMT's [AUTHORS.md further acknowledgments section](https://github.com/GenericMappingTools/gmt/blob/master/AUTHORS.md#further-acknowledgments).

I am interested in hearing feedback from @GenericMappingTools/core about whether any of these changes would be welcome.

**Comment by WalterHFSmith** [comment]
Sounds great to me.

w

**Comment by seisman** [comment]
Yes, I think option 2 is better.

**Comment by meghanrjones** [comment]
Thanks for the feedback - I will open a PR with a draft implementation for option 2.
