### ISSUE TITLE
Anchors seems wrong for legend

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2451]
I want to plot a legend box at the top left corner, so I use **-DjTL**. However, it puts my legend at a wrong position (not the same as I expected). See the script below. I expect to see the legend box at the position the same as the text "TopLeft". Am I misunderstanding something?
```
gmt pscoast -Rg -JH15c -B0 -A10000 -Glightblue -K -P > map_classic.ps
echo TopLeft | gmt pstext -R -J -F+cTL -K -O >> map_classic.ps
gmt pslegend -R -J -DjTL+w5c -F+p1p -O >> map_classic.ps << EOF
S 0.1i c 0.15i red 0.25p 0.3i Events
EOF
```

![image](https://user-images.githubusercontent.com/3974108/72476476-4e486200-37bb-11ea-9e16-03df540cdcf5.png)

BTW, I'm using 6.1.0_48648f2_2020.01.15, the lastest cpthingework branch.

**Comment by PaulWessel** [comment]
I think TL refers to geographical top/left which is the N pole in your case.
We probably want these justification codes to use the projected coordinates.

**Comment by seisman** [comment]
GMT 5.4.5 gives different output for **gmt text -F+cTL**, but the GMT6 one makes more sense to me.
![image](https://user-images.githubusercontent.com/3974108/72481379-54910b00-37c8-11ea-87fb-0d2b0a14f1f1.png)

**Comment by PaulWessel** [comment]
When we place embellishments (legends, scales, colorbars, etc) on a map and the projection yields a ellipse or circles etc, then the justification codes should be based on the projected rectangle and not the longitude,latitude I think.  The code does this (in gmt_set_refpoint):

```
gmt_just_to_lonlat (GMT, A->justify, gmt_M_is_geographic (GMT, GMT_IN), &A->x, &A->y);
gmt_geo_to_xy (GMT, A->x, A->y, &x, &y);
```

but if **-DJ** is used (outside the box) we use

`gmt_just_to_xy (GMT, A->justify, &x, &y);`

I think we should do _gmt_just_to_xy_ always since you can always place something at a specific coordinate via **-Dg**.  The first 2 lines above cannot possibly give you what you want since there is no lon,lat that correspond to your corner.

**Comment by seisman** [comment]
Yes, I agree. I think we can declare it as a long-term bug.

**Comment by PaulWessel** [comment]
From the **-Dj** code comment:

> Since intended for inside frame items (scales) we use the wesn rectangle to get the lon/lat coordinate from the code

Pretty clear there is not always a wesn **rectangle** for many projections.  I will declare a bug and treat **-Dj** and **-DJ** the same (against the imaginary enclosing rectangle).
