### ISSUE TITLE
-h option may not work as documented 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2503]
The documentation says:

> Blank lines and lines starting with # are always skipped

But the script below gives:
```
gmt select -h2 << EOF
# ABC
1
2
3
4
5
6
EOF
```
Output:
```
# ABC
# 1
2
3
4
5
6
```

**Comment by PaulWessel** [comment]
Perhaps the docs can be improved.  Normally, records with # are skipped.  I you run your command without **-h** you won't see the ABC on output.  However, when you add **-h** it means consider the first _n_ records of the file as header records and store them in the table header array.  Then, since **-h** means **-hi** and **-ho** it will print out those _n_ headers and prepend # if not present, hence the # 1 record.  Any records after those _n_ records will be treated as normal, meaning a # record will be skipped.
We added the **-h** option because some dumb files have plain ascii header text with no leading # character and the only way to get past them is to skip _n_ records.

**Comment by seisman** [comment]
Now I see how it works. The documentation need to be improved.

**Comment by seisman** [comment]
**+t** doesn't work?
```
gmt select -h+t"Title" << EOF
# ABC
1
2
3
4
5
6
EOF
```

**Comment by PaulWessel** [comment]
In general the ascii head modifiers don't work well.  Partly this is because we have a mix of modules reading rec-by-rec vs entire files.  Run the same example with gmt convert instead and you get a title out but it raises other questions:

```
gmt convert t.txt -h+tTitle
# ABC
 Title : Title
# Command : gmtconvert t.txt -h
1
2
...
```

I think this is a long-term issue... but I should fix the messing # for the Title statement.

**Comment by seisman** [comment]
Another issue:
```
gmt convert t.txt -ho+tTitle+rABC
gmtconvert [ERROR]: Can only set the number of input header records; +tTitle+rABC ignored
# ABC
# Title : Title
# Command : gmtconvert t.txt -ho
# Remark : ABC
1
2
3
4
5
6
```

**Comment by PaulWessel** [comment]
Now addressed in #2506.

**Comment by PaulWessel** [comment]
The whole documentation for the -h modifiers are not good.  I will see if I can improve it further.

**Comment by PaulWessel** [comment]
I think I address the issue.  Can we close this, @seisman ?
