### ISSUE TITLE
Unusual lines for a coastline basemap

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2669]
```
gmt coast -W1/1p -JH20c -R-180/179/-90/90 -Baf -png map
```

![map](https://user-images.githubusercontent.com/3974108/73862016-edd1a100-480b-11ea-8178-c16dcc905868.png)

**Comment by PaulWessel** [comment]
There are some assumptions and decision made in how to avoid those things, but allowing -R-180/179 is not one of them.  I am OK with this generating a bad map as a lesson to the user.  Trying to track this case is not worth my time.  Basically, giving a range that is between 360 and 360-binwidth will often fail. binwidth is the binning with of GSHHS.  The above example will work if you give -Df since its binning is 1 degree, and will work with 178 if -Dh, etc.

**Comment by seisman** [comment]
OK. Closing the issue as it won't be fixed.
