### ISSUE TITLE
gmtconnect warning

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2747]
Oddly this one fails in Julia (does not connect) but works on Matlab. However, in both cases it prints the warning
```
gmtmex('gmtconnect -T1.1', [0 0; 1 1], [1.1 1.1; 2 2])
gmtconnect [WARNING]: Trouble: Pass 1 found 1 while pass 2 found 2 connections!
```
But this one is silent
```
gmtmex('gmtconnect -T1.5', [0 0; 1 1], [1.1 1.1; 2 2])
gmtconnect [WARNING]: Trouble: Pass 1 found 1 while pass 2 found 2 connections!
```
something is weird. Even **-T0.1** should be enough, but
```
gmtmex('gmtconnect -T0.1', [0 0; 1 1], [1.1 1.1; 2 2])
gmtconnect [WARNING]: Trouble: Pass 1 found 0 while pass 2 found 1 connections!
gmtconnect [WARNING]: Trouble: Pass 1 found 0 while pass 2 found 1 connections!
```

**Comment by PaulWessel** [comment]
That is a new check I added.  The issue is that some time (and apparently in your case) we pass -B options first that only sets labels and then a later -B sets intervals.  This currently means the automatic -Baf kicks in the first time and then the second -B comes an overrides.  Ideally we need to change the linked list of options so that the interval -B comes first but that is a bit involved, so for now I an issuing a message. We could move that to INFORMATION but...

So see if you are placing label -B statements before interval statements.  The frame setting order does not matter.

**Comment by PaulWessel** [comment]
Sorry, never mind - you tricked me.  Nothing to do with your gmt connect problem.

**Comment by PaulWessel** [comment]
But it does remind us that there is a bug lurking in gmtconnect.  I have tried to trace through this issue before and not figured it out.  Will see if I can find the time.  The life of a department Chair is unpredictable.

**Comment by PaulWessel** [comment]
Wait, let's examine what you say here.  Why would -T0.1 be enough? The two closest end points [(1,1) and (1.1,1.1)] are a distance of 0.141421... apart, so would require at least -T0.1415, no?.  I am not yet sure what the messages even mean, but any -T larger that 0.1414 connects the two lines for me (on the command line).

I find that -T1.273 and larger gives no messages but -T1.272 or smaller does.  This might be helpful when I debug those two cases since I cannot see what difference this should make (both should connect).

**Comment by joa-quim** [comment]
Ok, I forgot about that Pythagoras guy. But I got messages with -T1.5

**Comment by PaulWessel** [comment]
OK, you said it was silent above but you listed the message.  So when is it silent for you?

**Comment by joa-quim** [comment]
Hmm, don't know anymore. It seems the issue is not entirely reproducible. Now -T1.5 is silent.

**Comment by PaulWessel** [comment]
OK, working on making the program readable by renaming obtuse variable names, adding comments to what things are, etc.  Hoping this will prevent the usual headaches as I debug later...
