### ISSUE TITLE
grdinterpolate with 3D Earth tomography models

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2785]
IRIS EMC (http://ds.iris.edu/spud/earthmodel) provides several 3D Earth tomography models in 3D-netCDF format. 

I tried to apply grdinterpolate to these 3D-netCDF files. The data file used below is S362ANI model, a global S wave velocity model in km/s. It can be downloaded from http://ds.iris.edu/spudservice/data/17996723. Here are some issues I found.

---

```
$ gmt grdinterpolate S362ANI_kmps.nc    
grdinterpolate [ERROR]: Option -R: Must specify output knot(s)
grdinterpolate [ERROR]: Option -G: Must specify output grid file
grdinterpolate [ERROR]: Must specify only one output grid file
```
- A typo in the first error message. It should be `-T` not `-R`
- It's not clear what "knot" means. The documentation also doesn't mention "knots". Maybe better to say "Must specify output levels"? 

---

```
$ gmt grdinterpolate S362ANI_kmps.nc -Glayer.nc -T200
grdinterpolate [WARNING]: No range attribute, guessing registration to be gridline
grdinterpolate [WARNING]: netCDF grid S362ANI_kmps.nc information has zmin = zmax = NaN. Reset to 0/0.
grdinterpolate [WARNING]: No range attribute, guessing registration to be gridline
grdinterpolate [WARNING]: netCDF grid S362ANI_kmps.nc information has zmin = zmax = NaN. Reset to 0/0.

$ gmt grdinfo layer.nc
layer.nc: Title: Global model of shear-wave velocity
layer.nc: Command: 2019-12-05 IRIS DMC, updated geospatial fields, if needed, to float
Wed Nov 20 10:28:33 2019: ncatted -O -a creator_email,global,m,c,product@iris.washington.edu S362ANI_kmps.nc
2016-08-11 IRIS DMC, updated variable definitions to make sure they are compatible with CF
2013-01-11 released
layer.nc: Remark:
layer.nc: Gridline node registration used [Geographic grid]
layer.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
layer.nc: x_min: -180 x_max: 180 x_inc: 2 name: longitude n_columns: 181
layer.nc: y_min: -90 y_max: 90 y_inc: 2 name: latitude n_rows: 91
layer.nc: z_min: 4.33699989319 z_max: 4.78660011292 name: Isotropic Shear Velocity [km.s-1]
layer.nc: scale_factor: 1 add_offset: 0
layer.nc: format: netCDF-4 chunk_size: 181,91 shuffle: on deflation_level: 3
```
The warning messages says `zmin = zmax = NaN`, but the output grid looks good. Does it make sense?

**Comment by PaulWessel** [comment]
Thanks, I'll have a look at that data.  I initially used some NOAA file to test the 3D reading part.  Maybe the data cube is not COARD compliant so we cannot find certain attributes? Or maybe in contains more than one cube, etc.

**Comment by seisman** [comment]
I also plotted the output *layer.nc* data.

The command is:
```
$ gmt grdimage layer.nc -JH20c -png map
```
The output is:
![image](https://user-images.githubusercontent.com/3974108/75085593-d88d8f80-54f8-11ea-9b37-abb7fd42e2cf.png)

The figure looks good as a whole, but there are some gray pixels at the boundary. Do I miss any options?

**Comment by PaulWessel** [comment]
No, I think that is right. -T200 should just yield sampling at 200.  I suspect the registration guess (since something is not found) is off and we are off at the boundaries?
Sorry, heading home.

**Comment by PaulWessel** [comment]
The layer.nc grid has no NaNs so what you see is just "normal" projection from (lon,lat) to (x,y) on that projection.  The 3-D grid is CF-1 compliant and we are reading it just fine (apart from some aggressive warnings I have moved to information).

**Comment by seisman** [comment]
OK, fixed.

**Comment by PaulWessel** [comment]
Close to finishing my implementation of creating a **vertical sliced grid** from the 3D cube. This would let us view a crossection of seismic velocities along a great circle through Hawaii, for instance.  I do this by recycling the **-E** option from grdtrack to set up the coordinates of the profiles on the surface.  Some questions for @joa-quim and **@**seisman:

Stuff like -E180/20/220/20+i1d works and gives a great circle cut.  However, maybe the user wants a cross-section along the 20N parallel.  OK, so I also ported the **-A** option from grdtrack and add **-Ap**. Two issues:

1. The x-coordinates in the grid is the distance along the profile so it goes from 0 to 37.6 spherical degrees, not 180 to 220 in longitude.
2. The increment is spherical degrees, not longitude at that latitude.

I can imagine similar slices along a meridian (and that would be a great circle so 1d == 1 degree latitude) but it would have an origin of 0 and not the start latitude.

Suggested upgrade for **-E**_lon1_/_lat1_/_lon2_/_lat2_**+i**_inc_:

1. Detect if _lon1_ == _lon2_ [and **-Am** but not required] and **+i**_inc_ given with unit **d**, **m**, **s**.  Then we adjust the distances to be latitude with origin at _lat1_ and set the meta data in the output grid as well
2. Detect if _lat1_ == _lat2_ and **-Ap** and **+i**_inc_ given with unit **d**, **m**, **s**.  Then we adjust the distances to be degrees longitude with origin at _lon1_ and set the meta data in the output grid as well.

Otherwise the distances start at zero and are whatever the units chosen (km, meters, degrees, ...).

Let me know what you think.

**Comment by PaulWessel** [comment]
Updated to say -A is required to get this feature.

**Comment by PaulWessel** [comment]
OK, updated to do as indicated. For instance

`gmt grdinterpolate S362ANI_kmps.nc -E180/20/220/20+i1d -T25/500/25 -Gslice.nc -Ap`   

will sample along the 20N parallel in steps of 1 degree longitude, while (without -A)

`gmt grdinterpolate S362ANI_kmps.nc -E180/20/220/20+i1d -T25/500/25 -Gslice.nc`    

will sample along the great circle connecting the two points in steps of 1 spherical degree.

Plotting the first slice with `gmt grdimage slice.nc -B -JX15cd/-15c -png map` yields

![map](https://user-images.githubusercontent.com/26473567/75101364-98252480-557f-11ea-87d1-54e73f957c9a.png)

**Comment by PaulWessel** [comment]
Want do make plot with **-JP** for this to show crossection of Earth, top 500 km.  But depth in grid is positive down so `gmt grdimage slice.nc -B -JP15c+z -png map` gives

![map](https://user-images.githubusercontent.com/26473567/75101577-a7f23800-5582-11ea-8e0e-ddd30fe032a2.png)

How to get shallow to be on the other side...

**Comment by seisman** [comment]
1. Does the **-E** option also support modifiers **+a**, **+o** et al., as in grdtrack -E？
2. For cross-sections along parallels and meridians, users may still need great circle distance as x-coordinate. I think we can add a modifier to allow changing the x-coordinate to "longitude or latitude degree".

**Comment by PaulWessel** [comment]
Yes, untested but all of **-E** was moved with the exception of disallowing **+d** (since we always need distances as the new x-dimension) and **+c** (which I add separately under the hood to ensure continuity).  We may wish to add some more checks.  For instance, makes no sense to give two lines unless they share a common point.
I agree with your second point.  This is also true for grdtrack.  Perhaps **+g** for gridline coordinates (lon or lat)? and remove the talk about **-A** (which we can then set under the hood).

**Comment by PaulWessel** [comment]
I added **+g** and it works fine.  It even sets the default unit to **d** when **+g** is used, otherwise km for geographic.  The **+g** also sets **-Am** or **-Ap** under the hood.  Given that, I am not sure if we need to expose the **-A** option at all to the user.  The **-Af** and **-Ar**|**R** options pertain to specifics about the users input data, but the users don't input data in **-E**. That leaves **+l** which is a feature I don't think we want to loose. We could add **+x** to **-E** for loxodrome and remove **+l** from **-A** (but keep that backwards compatible).  Then, **-A** can be removed from grdinterpolate but kept at grdtrack since user input may need the other flavors of **-A**.

**Comment by seisman** [comment]
If I understand it correctly:

- `-E180/20/220/20+i1d` means a great-circle cross-section
- `-E180/20/220/20+i1d+g` means a parallel cross-section, and longitude as x-coordinate

How can users specify a parallel cross-section, but also use great-circle distance as x-coordinate?

**Comment by PaulWessel** [comment]
Hm, yes, we want the ability to do both.  Perhaps we need to keep -A.

**Comment by seisman** [comment]
Or we can let **+g** to follow parallel or meridian only, and add another modifier to change the x-coordinate.

**Comment by PaulWessel** [comment]
I agree these are two separate functions.  Perhaps this:

**+p** means follow that parallel (not needed for meridians)
**+g** means report degree longitude along the parallels

So for grdinterpolate, making a vertical crossection along a parallel and wanting longitude to remain the x-coordinates we would do things like -E180/20/220/20+p+g.

**Comment by seisman** [comment]
For meridians, `-E30/-20/30/50`, users may want the x-coordinates to be "0 to 70 (distance)" or "-20 to 50 (latitude)".

**Comment by PaulWessel** [comment]
So **+g** would give -20 to 50; otherwise you get 0-70.

**Comment by seisman** [comment]
Yes, that looks good.

**Comment by PaulWessel** [comment]
Closing this now.
