### ISSUE TITLE
Oblique Mercator Projection - Orientation of the Oblique Equator

### ISSUE THREAD

**Issue by WherezWally** [GenericMappingTools/gmt#2786]
The Feature Request is that GMT includes the option to plot oblique projections with the oblique equator parallel to the y-axis.

The oblique equator in an Oblique Mercator projection is plotted parallel to the x axis.    It would be useful to be able to plot the oblique equator parallel to the y-axis.   

**Are you willing to help implement and maintain this feature?** No. Regrettably I do not have sufficient coding skills.

**Comment by PaulWessel** [comment]
Placing a few notes for myself here as to how this might be implemented.  My initial thought was this:

1. It will require a new modifier, somewhere, probably to -JO, that flags a desire to et the oblique equator be the vertical y-axis instead of the horizontal x-axis.
2. There is obviously a simple 90-degree rotation to flip the plot.  This will place data correctly.
3. The final coup-de-grace is to let the frame-annotation machinery know that we have rotated the paper by 90 degrees and this affects how annotation angles are selected.

However, not so sure about this since step (3) above is not so easy to fix.  Another idea is this:

1. At the end of the lon/lat to x/y projection, add the 90 degree translation/rotation there.  Now, nothing else is rotated and map frames should work normally.

Only real way to find out is to try.  I think the last option is at least easy to test, so will attempt that first.  The initial guess is that the positive x gets rotated to become positive y, and the positive y needs to be reversed to be positive x.  But, might there be cases where one wants positive y to go the other way? E.g, for an oblique projection for Baja California it makes sense that the oblique equator aligned with the peninsula points positive northwards, but presumably one might want to have "up" be the other direction.
