### ISSUE TITLE
kml2gmt: Support extracting fill and outline information

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2802]
I have a KML file with a color-filled polygon. With kml2gmt, I got 
```
> -L"RF-1"
-75.8594760442	19.7604400328
-65.739808851	12.7705502527
-57.4482475924	20.781139354
-68.5180356013	26.7218600274
-75.8594760442	19.7604400328
```
It would be useful if kml2gmt can also write **-G** and **-W** to segment headers.

**Comment by PaulWessel** [comment]
I think it is nontrivial to do.  The color/pen selections are done via styles and we would need to read/store the styles in memory and when we parse the style for the polygon we would then need to get and write the color or pen.  Perhaps you can upload an example of the types of files you have so we can see?  it is presumably not a file made by gmt2kml.

**Comment by seisman** [comment]
Attached is an example KML file created by Google Earth.
[example.kml.zip](https://github.com/GenericMappingTools/gmt/files/4247172/example.kml.zip)

**Comment by PaulWessel** [comment]
So that KML defines two Style ids.  Both sets the color.  Neither seems to set any outline and pen, but it shows up in GE as a 1 pt white perimeter and it says outline+fill is selected.  The PolyStyle settings are supposed to have fill and outline tags but none given here.  So not sure where fill and outline are set to 1.  I think this is why it is a bit tricky.
For instance, I could use gmt2kml with a CPT and make 20 different styles, and maybe 5 are used by my data.  I would have to parse all the Styles and then do a lookup when I find the styleUrl tag and find the corresponding style and its color and settings.  Perhaps flag this as a longterm feature request - need to build up energy for that one.
