### ISSUE TITLE
Let psxy -C -Z use 3rd column to set color

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2804]
**-C** & **-S** let us paint the symbols after the *z* value in 3rd column of input data. 
**-Z** should let us do the same thing to polygons.

Choropleths will have a good use for this new feature. Although we can do them via **-G** in *headers* the coloring is normally dependent on a (variable) condition and should not be set fix in segment headers.

Ideally, **-Z** should accept also a file with the *z* values (one per polygon) so that the whatever condition that is used to set the color is made independent of the polygons outline.

**Comment by PaulWessel** [comment]
Just in case you are not aware, we also parse **-Z**_value_ arguments in the segment headers and then lookup the color that way.  I do not like the idea of a separate file with z-values per polygon since now there is a coupling of two files that both can change and no longer work well together.  Seems to me the header **-Z**_value_ is pretty reasonable?

**Comment by joa-quim** [comment]
Yes, I'm aware of **-Z***value* parsing, but that shares the same issue with **-G**. 

If we have a file with many polygons that we want to use more then once (*e.g.* to make 2 figs) to paint the polygons then there is no escape to have some program scan the headers to set (or update if they exist already) the **-Z** or **-G**. For this program to run it will have to have a second file (or vector in memory) decoupled from the polygons file. Allowing a **-Z***file* is the way that I see which minimizes the needed work. Right, it opens a door to user errors but still seems to me the more user friendly solution.

**Comment by joa-quim** [comment]
I made a crude implementation of -Z<file> and with it I can do

```
julia> neigh = gmtread("C:\\v\\postgis-workshop-2018\\data\\nyc_neighborhoods.shp");
julia> C = makecpt(T=[0 1]);
julia> plot(neigh, C=C, choro=rand(size(neigh)[1],1), name="run1.png", title="Run1", show=true)
julia> plot(neigh, C=C, choro=rand(size(neigh)[1],1), name="run2.png", title="Run2", show=true)
```
and get (going through the *headers* way would be a lot more work)

![run2](https://user-images.githubusercontent.com/537321/75632197-b7602980-5bf1-11ea-83ba-bfbb9ffe9eff.png)


![run1](https://user-images.githubusercontent.com/537321/75632195-b4653900-5bf1-11ea-8836-c3eb72177fd6.png)

**Comment by PaulWessel** [comment]
So I am still not clear on the purpose and when this is useful.  You are making the case for a polygon whose z-value needs to be changed.  How is that different from a data point whose z-value needs to change? Would we have a second file to override the z-value in the data file? Of course not, you would edit the data file if there really was a good reason to edit that point (e.g., type, updated analysis).  You would not update it so that your CPT lookup would select another color.  In fact, you would mess with your CPT to get what you needed.

**Comment by joa-quim** [comment]
I'm trying to do choropleth maps. For them, the basic info is the polygon, that we color according to some condition, and we can have many different conditions (number of this, number of that, density of this, density of that, etc...). Look that in my example I loaded a shape file that has 159 polygons (not that many). How would we achieve the same effect going the the -Z<val> header way?

I don't think choropleths are exactly similar to data points that may have associated a value representing something.

**Comment by PaulWessel** [comment]
Right, but doesn't the shape file has all that as aspatial values and you can select the one you want to be Z?  Look, I am not trying to prevent a solution here, but it you have not yet convinced me that this is not just bad data arrangement.

**Comment by joa-quim** [comment]
We can't rely that the shapes (or whatever formats) have a single attribute that we would know how to read and use it for assigning colors.

It might not be such a good data arrangement, but do you propose to do choropleths? 
Manual editing a file with a 100 polygons to add color in headers seems out of question, no?

**Comment by PaulWessel** [comment]
Well, shape files are very good for this - despite the ugly and obsolete format.  Via **-a** you can pick any of the spatial values listed for a polygon - and there may be lots - and make that your z-value in psxy.  I would think almost all cases of database or of geospatial data formats support that sort of thing.

Now, I can also imagine that one might have a file with polygons and then a separate set of data that you want to associate with the polygons.  If that is the case then perhaps the solution is to allow those to files to blend.  Rather than add **-Z** options to all modules that might need to do this, maybe it could be done by gmtspatial or gmtconvert.  I do not think your case is very common - all the cases I have seen of cloropleth etc. deal with data values in the original files.

**Comment by joa-quim** [comment]
> perhaps the solution is to allow those to files to blend.

That's exactly what I'm trying to achieve. Be it with -Z or gmtconvert I ofc don't mind but notice that with gmtconvert we would need to make a data copy and work only in ascii files.

I also don't get well how you envisage picking the aspatial data "listed for a polygon". For example, for the data used in the example above,  the aspatial data is stored in other shapefiles. So, no escape to end up with one array (file) of polygons and another for the variable we wish to plot.

**Comment by PaulWessel** [comment]
Considering what our segment headers can contain described [here](https://docs.generic-mapping-tools.org/latest/cookbook/file_formats.html#optional-segment-header-records), my proposal is to add **-M**:

gmt convert _table_ **-M**_mergefile_[**+d**|**g**|**l**|**t**|**w**|**z**]

Update the segment headers in _table_ so that there is a **-Z**_value_ entry based on the text records given in _mergefile_.  If modifiers **+d**, **+g**, **+l**, **+t** or **+w** are used the we set **-D**_dist_, **-G**_fill_, **-L**_header_, **-T**_text_ or **-W**_pen_ instead, respectively [**+z**].  If the number of entries in _mergefile_ does not match the number of segments in _table_ then we warn about the mismatch, but still perform the replacements until we run out of segments or records.

In this case, _table_ can be binary, netCDF, even shape file, but _mergefile_ will be an ASCII table.

**Comment by joa-quim** [comment]
Ok, but it needs to also look if previous **-G**, **-Z**, **-W** etc already exist in headers.
The input can be binary but then the output of this will have to be an ASCII copy because those binary formats can't store this type of info.

We also recently changed ``pscoast -E -M`` to store the 2 chars country ID in  header under **-Z**
```
$ pscoast -EPT -M | head
> -ZPT Portugal Segment 0
...
```
but doesn't the *val* in **-Z***val* has to be numeric?
I now also think that is dangerous because if one plot such polygon file and use a cpt then it will always try to paint the polygons.

**Comment by PaulWessel** [comment]
Yes, of course it would replace whatever **-G -D -Z** etc was there.
Do you have a need to store this in binary? You could use gmt convert **-a** to write a shape file.
I think **-Z** argument can be anything used to lookup colors - I cannot recall if our CPT for categories uses text or not but that was the idea. Does not the danger go away with

`gmt convert your file -Wmerger | gmt plot ...`

This is to fix a data problem, no? We could have **-M** remove **-Z** if no merge file given ,etc.

Time for the commute.

**Comment by joa-quim** [comment]
Yes, I also thought the pipe is a solution to not make a copy of the original, but they don't work in externals.

I don't want to store in binary nor convert to shapes. Just trying to avoid data copies, which this solution does not help with.

**Comment by PaulWessel** [comment]
So you have no internal Julia representation of a dataset with segments and headers then.

**Comment by joa-quim** [comment]
Sure I have, but if you send in a dataset to GMT to change the headers you'll get a copy or some other memory shuffling. One cannot simply resize the header segments that are interspersed with the data segments.

**Comment by PaulWessel** [comment]
We cannot change original memory you pass in, but you get a duplicate passed out with the revised headers, no?  GMT builds the new structure from the input. Anyway, I am looking at psxy and psxyz and both have that -Z option of course.  So the question then is can -Z take a file and then pop off one value at the time and use that for the CPT lookup.  I guess that is not so bad after all.  But I think the gmtconvert scheme is also needed as a way to affect more complicated things as segment-specific pens or labels.

**Comment by joa-quim** [comment]
Yes, one should get a **copy** of the updated dataset. Regarding the Z question, the answer is an obvious yes. The plots above were done that way. As I mentioned I have an implementation of **-Z***file*. It's just not backward compat because logic became too convoluted to my quick trial.

**Comment by PaulWessel** [comment]
Do you want to start a branch on this?  I think it should be pretty simple to use GMT_Read_Data to read a file if that is what the argument is, then instead of the fixed z-value we serve up the next z-value from that data set until we run out.

**Comment by joa-quim** [comment]
That's what I do.
Oddly does not work from julia. I was forced to save temporary file and read it in **-Z** instead of ingesting a vector directly.

**Comment by joa-quim** [comment]
Addressed by #2839

**Comment by PaulWessel** [comment]
Not the title of this issue says 3rd column but code does first column.

**Comment by joa-quim** [comment]
>Not the title of this issue says 3rd column but code does first column.

Not a good example. I wrote that title when I thought in using the 3rd column in input data for painting. But then realized that it would tie the data with a particular color representation (not to mention that all 3rd values would have to be the same), which was exactly what I was trying to avoid.
