### ISSUE TITLE
Bug in psscale with -B+l and -Q

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#2943]
The axis label is superimposed to the numbers of the scale.

![psscale_bug](https://user-images.githubusercontent.com/17908951/76957116-0b5a5600-68f4-11ea-8448-f6cf0814d1ca.png)

```
gmt makecpt -T0/5/1 > color.cpt -Q
gmt psscale -Dx0/0+w6/0.618c -Ccolor.cpt > "psscale_bug.ps" -Ba+l"Axis Label" -Q
```
Win10
GMT version 6.0.0 (64-bit)

**Comment by PaulWessel** [comment]
Can confirm the problem.  Use **--MAP_LABEL_OFFSET**=_somedistance_ for now as a workaround.

**Comment by PaulWessel** [comment]
Seems like a few problems here.  According to **-Q**:

> Select logarithmic scale and power of ten annotations. All z-values in the CPT will be converted to p = log10(z) and only integer p values will be annotated using the 10^p format [Default is linear scale].

However, given **-B** in general supports both 10^p and the raw annotation format the user selected, I think the man page needs to be corrected.  Yet, if we use **-B**a1p in the case above we get 10^p annotations but the label still overprints part of the annotations.  Thus, there are two problems:

1. Correct the **-Q** paragraph and refer to **-B** for selecting 10^p or other types of annotations for log axis.
2. Correct bugs in **psscale** re-implementation of the **-B** axis usage so that it is consistent with **psbasemap**.  

Implementation wise, the best solution would be for the linear axis function _gmt_xy_axis_ to handle this internally.
