### ISSUE TITLE
blockmin and blockmax

### ISSUE THREAD

**Issue by sabinz** [GenericMappingTools/gmt#2965]
Hey team,

In many cases I have come across scenarios where I'd love to be able to return the min or max value from a given XYZ cell. So rather than running blockmedian/blockmode/blockmean, it would be amazing to do blockmin or blockmax. One key area where I think this will be useful is when we compute seafloor age-grids. Sometimes we get overlapping isochrons of very different ages, and blockmin or blockmax could really reduce the artefacts that we get during interpolation. I could do this with brute-force, but it would be really cool to have a GMT tool to do it. I know you are all swamped with requests and so on, but just putting out my idea here. (Or in the best case scenario, perhaps what I'm after is already out there...)

Thanks for all your wonderful work! 

Cheers,
Sabin

**Comment by PaulWessel** [comment]
Hi @sabinz. **blockmedian** already can return the min and the max per cell:

> -E[b]
> Provide Extended report which includes s (the L1 scale of the median, i.e., 1.4826 * median absolute deviation [MAD]), l, the lowest value, and h, the high value for each block. Output order becomes x,y,z,s,l,h[,w]. [Default outputs x,y,z[,w]. For box-and-whisker calculation, use -Eb which will output x,y,z,l,q25,q75,h[,w], where q25 and q75 are the 25% and 75% quantiles, respectively. See -W for w output.

So you could use `gmt blockmedian -E -o0,1,4,5` to get lon, lat, min, max for instance.

Since I have your attention, please post general questions to [the forum](https://forum.generic-mapping-tools.org).  Hope all is well down under - stay safe.

**Comment by sabinz** [comment]
Oh WOW! That's amazing, I didn't find that in my previous searches, so I'm glad I asked... Neat! Thanks, Paul! Ok, apologies, I wasn't aware of the separate forum and Github. Also, believe it or not, still debugging the plate motion model, so will get back to the Plate ID table for you in the next couple of weeks while I settle into a new work-from-home schedule. Sydney is starting to shut down in phases, but I believe too slow to do anything effective, and we're heading into a similar (or worse) scenario as Italy. Hope you guys are OK in Hawaii!

**Comment by PaulWessel** [comment]
Thanks, I think we are on the same 1.35x multiplier per day that is seen across the world, but we started slightly later.  Expect cases to ramp up the next week.  We are sequestered at home doing online teaching and zoom meetings.  Toilet paper is sold out because idiots hoard these things.  Best, Paul.
