### ISSUE TITLE
Planning periodic zoom meetings for GMT developers and enthusiasts

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2981]
**Description of the desired feature**

We expect to set up periodic meeting for the GMT developers, and we wish this to be an orderly affair:

- A meeting agenda should be posted on our website X days before the meeting
- The zoom meeting will be open to anyone, possibly with some restrictions
- The meeting will be recorded and made available afterwards
- There will be minutes from the meeting that summarizes actions taken
- The meeting should have a prescribed length (e.g., 1 hour max).

This issues will take feedback on several factors that need to be determined:

1. What is a reasonable meeting frequency: Every week seems too stressful (especially now that every day is a long zoom meeting, perhaps every 2 or 4 weeks.  This may change once the postdoc has been hired and makes progress.
2. What is a reasonable meeting time? With 10 hours between Hawaii and GMT (the other GMT), it will be inconvenient for some.  Since 5 pm GMT is 7 am Hawaii-time while 7 am GMT is 9 pm, it would seem best to have a meeting as early in the morning as reasonable in Hawaii (e.g. 7-9 am) which means 5-7 pm in Europe).  Thoughts?
3. If the zoom invitation is wide open we may get crazy people connecting and trying to [ruin the meeting](https://blog.zoom.us/wordpress/2020/03/20/keep-the-party-crashers-from-crashing-your-zoom-event/),  Who should get the link? Only people on GitHub?
4. Can there be a separation between those who can actively participate (i.e., speak and present) versus others who can only view (in real-time)?

There are probably other concerns - those with more experience with zoom meetings please chime in! Pinging @GenericMappingTools/core, @GenericMappingTools/gmt-contributors and @GenericMappingTools/python-contributors.

**Comment by KristofKoch** [comment]
May I ask what is the scope of these meetings?

**Comment by PaulWessel** [comment]
The scope is broad but any particular meeting should stick to a published agenda. For instance, we will need to hire a postdoc so discussing that is likely to be one of our first agenda items.  We decided we want to keep these meetings open to all interested, but donʻt expect that many to subject themselves to it.  We do encourage power-users like yourselves to be involved.

**Comment by leouieda** [comment]
Hi @PaulWessel thanks for getting the ball rolling on this.

> What is a reasonable meeting frequency

We could take the mean and do every 3 weeks? That way it moves around a bit with less of a chance for consistent clashes.

> What is a reasonable meeting time?

7am Hawaii seems good if that fits with your schedule. It wouldn't accommodate our asian and oceania colleagues but no timezone would. We can also alternate times between meetings so that people can at least make every other one.

> Zoom trolls

This is a tricky problem. We want people to be able to participate but we also don't want random people trolling the meetings. A few ideas:

1. Start every meeting with everyone muted and no video. The admin can then choose who can speak. I've seen people talking about having a "waiting room" and the admin then lets individual people in.
2. Have random meeting IDs and only post them to the forum 10 minutes before the meeting starts.
3. Make the meeting private but extend invitations liberally to people who ask on the forum.

We will probably need a combination of these and will have to learn as we go, I guess.

There are more tips here: https://www.zdnet.com/article/how-to-prevent-your-zoom-meetings-being-zoom-bombed-gate-crashed-by-trolls/ 

For the scope and format, this is what I've seen others do with some success:

1. Start with a general update from everyone (go around and each says what they've been up to). It should be short and people can put what they did in the agenda as well. Not only technical, can also be personal/fun/etc. We are a team and need these interactions to really get newcomers on board.
2. Go over outstanding items from the agenda that need to be discussed in this setting (i.e., could not be solved easily in the PR/forum/issue). This to include here are big ideas, technical challenges, API design, tricky PRs.
3. Have assigned roles:
    * Moderator: is in charge of making sure the meeting moves along. If discussion is going on for too long, interrupt and suggest moving to a separate meeting/PR/issue. Make sure everyone has the chance to speak and no one person dominates.
    * Scribe: Take notes while people are talking.
4. These roles can (should?) rotate between the team.
5. Make sure we schedule something fun as well from time to time, not only work related.

**Comment by joa-quim** [comment]
Monthly meetings should be OK, though when we stat them we may want to have a higher frequency at the beginning.

I wouldn't worry much (yet) with trollers. If that happens, Zoom meetings can be set with passwords. Don't know if possible but perhaps we could create a category in the Forum visible only to users above a certain *Karma* level. Users that have not used the Forum, at least to present themselves, are unlikely to be interested in our meetings. Meeting passwords would posted there, if needed.

**Comment by leouieda** [comment]
@joa-quim I like that idea. That might solve a lot of these issues. We can always elevate people manually if needed.

**Comment by PaulWessel** [comment]
Let's get the ball really rolling by planning the first meeting.  To have some time to make a short agenda and assign initial roles, what about next week, say, Thursday April 9 at 7 am HST?

**Comment by akshmakov** [comment]
I am someone isolated from the GIS community, but I am keen enthusiast developer who has managed to contribute a commit or two to a gmt project in years past. 

My main interaction with this team so far has been through github only and I am not aware of forums or other GIS community resources. 

I would love to re-engage with the project through participating in Zoom and meet the major contributors and get a feel for where I can plug in again. 

Thanks a bunch, looking forward to this.

**Comment by joa-quim** [comment]
Well, I'm not planning to go anywhere on the next couple of weeks so anytime by the end of the day (GMT+1) is good for me. We could even do it next weekend.

**Comment by joa-quim** [comment]
@akshmakov we are not that much GIS people either. You welcome to show up.

**Comment by leouieda** [comment]
@PaulWessel that works for me

**Comment by PaulWessel** [comment]
Any restrictions on @seisman's schedule?

**Comment by seisman** [comment]
It works for me, too. I have a pretty flexible schedule.

**Comment by PaulWessel** [comment]
Open to suggestions how we organize and post

- Meeting announcement and agenda
- Meeting minutes
- Zoom recording

**Comment by joa-quim** [comment]
- Use the Announcements category in Forum to post the agenda and time/link
- Agenda itself: PostDoc, Geometries, ...
- Why do we want to record de meetings? I don't really see a reason.

**Comment by leouieda** [comment]
> Use the Announcements category in Forum to post the agenda and time/link

Yep, that seems like the best place. Either there or Governance.

> Agenda itself: PostDoc, Geometries, ...

Best thing would be start a Google Doc or [HackMD](https://hackmd.io/) and include the public link in the forum post. Then we can start putting things in there and take notes during the meeting.

> Why do we want to record de meetings? I don't really see a reason.

Putting this up on our YouTube serves a couple of purposes:

1. People who can't attend can still see what was discussed/decided. So there is more transparency and less pressure to attend meetings every time if the timezone is not favourable.
2. We can point to these when reporting to NSF :slightly_smiling_face: 
3. We can look back on the progress if needed when preparing for talks, etc.
4. It lets more people see our decision making process and makes the core team feel more human than GitHub bots pushing code.

**Comment by leouieda** [comment]
We can start a post announcing the time and date. Then add the link to the agenda and zoom closer to the time of the meeting.

**Comment by joa-quim** [comment]
Well, honestly, I don't find any of those reasons compelling.
But I'm not opposing.

**Comment by PaulWessel** [comment]
They may not be compelling for our own needs, but it sure is interest in NSF to see how sustainable software might work, so the "data" we provide on this is essential.  The grant has come in installments and the first year chunk is here.  2nd and 3rd year will come provided we perform badly.  So I think there are plenty of reasons to doing the max openness approach.  The downside is we may have to shave and/or shower before each meeting.

**Comment by PaulWessel** [comment]
Need organizational help, please.  I have an edited 52 minute MP4.  I can upload to the GMT YouTube channel and get a link.  We should have a nice clean list somewhere of

> Date  Minutes  Recording
> 2002-04-09   google-doc-link   youtube-link

with links to the google doc and youtube recording.  Do we make sure a table with a new header on teh main generic-mappint-tools site, or is this a DEVELOPER_MEETINGS.md file in the top dir of GitHub?

**Comment by leouieda** [comment]
Probably better to not have it in this repository. I would say either on a "governance" repo or on the website.
