### ISSUE TITLE
Auto legend is stuck when plotting symbols of varying sizes/colors

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2982]
Run the command below to reproduce the issue:
```
gmt begin legend png
gmt coast -JM10c -R105/123/3/24 -Baf -Glightblue
gmt plot -Sc -Gred -W0.5p,black -lEvent << EOF
121.60  18.50 0.4
121.50  18.00 0.5
121.00  14.40 0.6
121.10  13.60 0.7
EOF
gmt legend -DjTL -F -V
gmt end show
```
The verbose message is:
```
legend [INFORMATION]: Processing input text table data
legend [INFORMATION]: Reading Data Table from Stream 7fff90c56dd0
```
and legend is waiting for some input.

In this script, the symbol sizes are specified in the 3rd column of the input data. It's tricky for GMT to guess a suitable symbol size for the legend entry. In this case, GMT should report an error like:
```
Option -l: modifier +s is needed to specify the legend entry size for varying symbol sizes.
```

**Comment by seisman** [comment]
Auto legend is also stuck with varying symbol colors:
```
gmt begin legend png
gmt coast -JM10c -R105/123/3/24 -Baf -Glightblue
gmt plot -Sc0.4c -Crainbow -W0.5p,black -lEvent+s0.2c << EOF
121.60  18.50 0.4
121.50  18.00 0.5
121.00  14.40 0.6
121.10  13.60 0.7
EOF
gmt legend -DjTL -F -V
gmt end show```

**Comment by seisman** [comment]
Also for varying symbol types:
```
gmt begin legend png
gmt coast -JM10c -R105/123/3/24 -Baf -Glightblue
gmt plot -S0.4c -Crainbow -W0.5p,black -lEvent << EOF
121.60  18.50 0.4 c
121.50  18.00 0.5 t
121.00  14.40 0.6 a
121.10  13.60 0.7 i
EOFgmt legend -DjTL -F -V
gmt end show
```

**Comment by PaulWessel** [comment]
So those are all cases where the auto-legend does not add an entry the the file, so when you force a **legend** call there will be no input file and it expects info from _stdin_ and thus hangs.  I am not sure what we should do in these cases:

1. Give warning that **-l** was used but no items passed the requirements and thus no info written.
2. Same, but write an empty file so that the **legend** call won't hang [but we don't know that a **legend** call will follow at the end].
3. In modern mode, do not read from _stdin_ in **legend** [this seems overly restrictive].
4. If different symbols sizes, colors, types, add one legend entry per symbol [but we have no way of setting text field, so way show 5 different sized/color symbols with no label?]

I think only the first (warning) is reasonable?

**Comment by PaulWessel** [comment]
Or, can we be more clever? Perhaps the trailing text can be taken as label in the above cases and we add one legend item per record?

**Comment by PaulWessel** [comment]
E.g., in the above examples, if you had

```
gmt plot -S0.4c -W0.5p,black -l << EOF
121.60  18.50 c Pizza
121.50  18.00 t Burgers
121.00  14.40 a Thai
121.10  13.60 i Japanese
EOF
```

then there are all added one after the other as legend items, with the trailing text as label.  That seems pretty helpful.  If there is no trailing text, then we probably should skip the line.

**Comment by seisman** [comment]
> 1. Give warning that **-l** was used but no items passed the requirements and thus no info written.

It makes more sense to raise an error since users explicitly use the **-l** option and expect to see an entry.

For the variable size case, the error message should instruct users to use the modifier **+s**. However, for the variable color and symbol cases, auto-legend can do nothing.


> Or, can we be more clever? Perhaps the trailing text can be taken as label in the above cases and we add one legend item per record?

Looks clever, but it's very limited, as we can't have two records with symbol type **c**. I think we should admit that the auto-legend feature only works for simple cases, i.e. only one entry for one command. For complicated cases, users should design their own legend file instead.
