### ISSUE TITLE
Frame overflow

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3032]
```gmt basemap -JL-24.9/16.55/16.3/16.7/20 -Baf -BWSen -R-25.09/-24.85/16.772/16.924 -png lixo```

![image](https://user-images.githubusercontent.com/537321/78594184-bbf6ae00-783f-11ea-8612-bc80107640dc.png)

**Comment by PaulWessel** [comment]
Well, that is fun.  How did that happen? Must be some special cases since all our tests work.

**Comment by PaulWessel** [comment]
Getting back to this one.  While this looks deceptively like a regular rectangular plot, in fact it is another windshield-wiper plot where the south and north axis are circles around the projected north pole.  For this tiny region, the west and east boundaries meet at the projected N pole about 170 meters away.  The algorithm determines the radii to the top and bottom of the south checker frame (since the frame is thick the radii are different).  Then we compute the angles of the west and east boundararies towards teh N pole.  These are both very close to -90 degrees ± a tiny bit. Because the E and W checkerboard lines are also think, we need to draw those arcs a tiny bit extra at either end and for either radii.  So we take the frame width (5p) and converts that to an angular offset so we can add/subtract from the ~ -90 degrees and draw the arc.  These offsets are about 0.0006 degrees.  OK, so off we go to draw a postscript arc in PSL_plotarc.  By this time we have added 360 to get positive angles, so we draw from 269.94543580522731 to 270.01480196377656 with a radius of 7942299 PostScript units (~168 meters). We print out the angles with %g.  I am pretty sure we are loosing important decimals that are needed with this near infinite radius.  Betting I will post back here in 5 minutes to congratulate myself on spending a fine Saturday doing this.

**Comment by PaulWessel** [comment]
Yes, that was it.  Change all %g statements writing floating points like angles to PS to %.12g.  Running tests since perhaps subtle changes to the origs before making a PR.

**Comment by joa-quim** [comment]
Yep, I've learned my %.12g lesson in an hard way as well.
