### ISSUE TITLE
psxy -Z only fills, no outline

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3124]
As can be seen in the ``psxy/variable_z.sh`` to paint and outline the polygons it's necessary to add the **+f** flag. But man says
> To just set the fill or outline, append +f or +l, respectively [both].

**Comment by PaulWessel** [comment]
Hm, yes the two bottom panels are switched - the output should be the other way.

**Comment by PaulWessel** [comment]
So perhaps this is a user confusion thing.  The **+fl i**s the default, meaning draw the outline and fill the pen **with the color from the CPT z lookup**.  So hard to see since pen and fill have the same color; change to -W3p and it is clear at the corner.  If you want just fill set via **-Z** and another pen color drawn by **-W** then you need to add **+f** only so the pen color does not change,  So in fact the example is correct, and it picks up the pen width from **-W** but color from _z_.

**Comment by joa-quim** [comment]
This is too complicated. **-Z** should set the fill only. Outline is a **-W** job. Why would we want to have an fill + outline with same color set by **-Z**?

**Comment by seisman** [comment]
Close this issue?
