### ISSUE TITLE
Possibly padding from externals is screwing at times

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3196]
This came out from a Julia [issue](https://github.com/GenericMappingTools/GMT.jl/issues/357)
It doesn't happen with linear projection, nor if the **-R** is that of the grid limits
```
G = gmt("grdmath -R70/130/-5/55 -I0.3015075376884 X Y MUL =");
grdimage(G, region=(70, 130, -5, 47), figsize=15, proj=:Mercator, name="stripes.png", show=true)
```

and I can reproduce it in Matlab as well

```
G = gmtmex('grdmath -R70/130/-5/55 -I0.3015075376884 X Y MUL =');
gmtmex('grdimage -R70/130/-5/47 -JM15 -Baf -BWSen -P > lixo.ps', G)
```

![stripes](https://user-images.githubusercontent.com/537321/80641621-0cd37e00-8a5d-11ea-9a87-8071a5c34b22.png)

**Comment by PaulWessel** [comment]
Guessing it is related to the incompatible -R setting:

```
gmt grdcut -R70/130/-5/47 t.grd -Ga.grd
grdcut [WARNING]: (n - y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdcut [WARNING]: n reset from 47 to 46.8592964824
```

Will have to debug as to what damage this causes internally

**Comment by PaulWessel** [comment]
Close to figuring this out.  When we read a subset from a memory grid we simply increase the pads since we do now have write-permission on the grid.  All that works well (north pad becomes 27 instead of 2).  But in grdimage, somewhere after projection, the north pad is reset to 2.  That cannot possibly be helpful as the G->data is of the same size as the original grid.

**Comment by PaulWessel** [comment]
Fixed that issue so pad is not reset if already manipulated.  But same result in image....Now for yet another EXCOM zoom meeting...

**Comment by PaulWessel** [comment]
Restarting the bug hunt on this after various side-shows.

**Comment by PaulWessel** [comment]
To summarize the observations:

Actions that do **not** cause stripes:

1. Any subset with linear projection
2. Shrink east boundary inward
3. Shrink sound boundary inward

What **does** cause problems (with map projection):

1. Shrink west boundary inward
2. Shrink north boundary inward (case above)

Since no subset and map projection takes the memory grid through the resampling to Mercator without any trouble, the issues is clearly related to some bad interaction from

- Changing west or north
- Projection this subset

It makes no difference if I carefully select 47.7638190955 as the north latitude (to match the grid exactly) or not.  Since the grid first row is at north, it makes sense that west and north both fail since they both will have a changed leading pad that reflects the change in region (data is still there but pad has changed).

My plan is to try to make a much smaller grid that still fails, then carefullly step through the projection of the padded subset. Unable to make it much smaller, but this has some benefits:

```
G = gmtmex('grdmath -R70/130/-5/55 -I1 X Y MUL ='); 
gmtmex('grdimage -R70/130/-5/40 -JM15 -Baf -BWSen -P > lixo.ps', G)
```

![lixo](https://user-images.githubusercontent.com/26473567/80847249-a8263980-8baa-11ea-8ec9-5c2cb06c70fd.png)

It has grid increments of 1 not 0.301... so not a case of grid-node mismatch etc.
It screws for a single row, and it looks like the color is constant across.
