### ISSUE TITLE
Bug with -JG North/South Pole and -B0 and issues with MOVIE_WIDTH

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#3341]
I create an animation of the earth rotating from the south pole to the north pole following the example of the manpages of [Movie](https://docs.generic-mapping-tools.org/latest/movie.html) and I found: 

1) A bug with respect the figures of the South/North Pole. The border (only happened with -Bg) is slightly separated from the edge of the map (see example below).
2) An issue with movie. When I use %MOVIE_WIDTH% to set the width of the figure, the frame is cut in the sides and left out of the animation. The width is just for the map. Maybe this could clarify in the docs.

```
Movie.bat
gmt math -T-90/90/1 -o1 T = "angles.txt"
gmt movie "globe.bat" -Nglobe7 -T"angles.txt" -Agif -C15cx15cx100

Globe.bat
gmt pscoast -Rg -JG-65/%MOVIE_COL0%/%MOVIE_WIDTH% -Ggray -Sdodgerblue2 -Cgray -N1/0.2,- -Bg -X0 -Y0 -W1/
```

**Actual outcome**
![globe7_000](https://user-images.githubusercontent.com/17908951/82128336-c0907980-9790-11ea-8270-4f5f5cfee3b2.png)

![globe7_018](https://user-images.githubusercontent.com/17908951/82128346-d736d080-9790-11ea-9d8c-13634007f570.png)

**System information**

* Operating system: Win 10
* GMT version (`gmt --6.0.0`):

**Comment by PaulWessel** [comment]
Thanks for this test! I will address the two concerns:

1. By default for geographic maps that can do it, the frame setting (**MAP_FRAME_TYPE**) is set to _fancy_.  However, for the azimuthal projections that can only be applied for the polar version (latitude is ±90). So that is why it suddenly tries to draw the fancy border, and because there is no **-Baf** there is not black/white checkerboard, only the extra circle (that also gets clipped a bit due to finite pixel size (half that line is outside the canvas, and the other half is probably resulting in zero pixels inside at the tangent points).  I think all I can do is to add some text in the movie documentation to recommend setting **MAP_FRAME_TYPE**=_plain_ when making geographic maps with changing projection centers.  If you rerun your movie with that setting it will be better.
2. Yes, the **MOVIE_WIDTH** (and **MOVIE_HEIGHT**) are the dimensions of the movie _canvas_ and not the projection width.  To fit you would need **-X**0 **-Y**0.  I will clarify that as well and see how well we explain the use of since the default 2.5c is usually too far in.

These changes are address in #3342.
