### ISSUE TITLE
histogram sometimes select deprecated syntax

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3445]
```
$ gmt histogram  @v3206_06.txt -F -T250 -W2p,blue -B -pdf plot
histogram [WARNING]: Cannot tell if -T250 -W2p,blue is new or deprecated syntax; selected new.
$ gmt histogram  @v3206_06.txt -F -T-6000/0/250 -W2p,blue -B -pdf plot
histogram [WARNING]: Cannot tell if -T-6000/0/250 -W2p,blue is new or deprecated syntax; selected deprecated.
histogram [ERROR]: Must specify either fill (-G) or lookup colors (-C), outline pen attributes (-W), or both.
```

If I understand it correctly, **-T** is the new option since 6.0. Thus, if **-T** is used, it should always be new syntax, right?

**Comment by PaulWessel** [comment]
No, -Tcol was used throughout GMT up through GMT4.  That is why this is tricky, since -T2 is either 2nd column  or an increment of 2.
I could delay until we know how many columns in the data file but many cases like -T1 would not help.  See the extensive comments in the pshistogram_new_syntax function.

**Comment by PaulWessel** [comment]
However, looks like I am not detecting that -W is indeed a pen ,which is a clear new mode indicator.  I am looking for a trailing c,i,p but here we have a color.  I will look for a comma as well.
