### ISSUE TITLE
test/grdimage/grdimage_img_tif.sh failed in recent CI jobs

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3473]
Here is the gm diff file:
![image](https://user-images.githubusercontent.com/3974108/84599223-76a5bc80-ae3e-11ea-9817-5ed9d25a4d70.png)

**Comment by PaulWessel** [comment]
Noticed that yesterday too and asked @joa-quim to check.  The PDF looks fine so these are tiny differences, possibly related to one of his changes.

**Comment by joa-quim** [comment]
It still passes for me on Win. My changes dealt with padding and this failure is not on the borders.

**Comment by PaulWessel** [comment]
@seisman, does it fail in the Win CI or just the Linux or macOS CI?  There is no FFT here so not a difference in FFT libs.  Projection should be stable. But it is a grdimage -A call so no projection in building the TIFF so no padding whereas before there was a pad.  Wonder why that matters or gives different results.

**Comment by seisman** [comment]
It failed on all platforms.

**Comment by PaulWessel** [comment]
Is it possible for @seisman to use git magic to see what the changes in grdimage is between the last branch that passes and first that fails?  While the failure is really benign it might be good to understand what it is.  Over the last year there have been similar situations where I basically ahve just updated the PS since I could not see anything.  But sounds like if we do that it would fail on WIndows.

**Comment by joa-quim** [comment]
Must have been 00ba0c9e20f28a1ae0badac23bf450f33974af1c but how come it works for *my windows*?

**Comment by seisman** [comment]
Yes, it failed after commit 00ba0c9e20f28a1ae0badac23bf450f33974af1c.

**Comment by PaulWessel** [comment]
We have accepted the new plot (which looks fine) as the new original
