### ISSUE TITLE
gmt clear fails on Win if session dirs are not empty

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3476]
```
gmt clear sessions
c:/j/.gmt/sessions: Directory not empty
```

**Comment by PaulWessel** [comment]
Is this something new or have you run this successfully (with non empty sessions dir) before?

**Comment by joa-quim** [comment]
Suspect it's new. I have it by default when starting a Julia session and started to see this recently.

**Comment by PaulWessel** [comment]
The way this work is that we get a list of the dirs (gmt6.*) in sessions, then for each one we call gmt_remove_dir which will get a list of all the files in that dir, delete the files one by one, then delete the empty directory.  This assumes there is no subdirectory in any gtm6.* dir because we are not creating any directory in the current session dir.  You are not creating any subdirs in a gmt6.* subdir are you in Julia?

**Comment by joa-quim** [comment]
I'm not creating anything from Julia, just calling ``gmt clear sessions``. And the the dirs in *sessions* all have NO sub-dirs. Only the regular files in them.

**Comment by PaulWessel** [comment]
Sorry, hard to debug for me on Win.  Can you run that command in debug and tell me what part complains?

**Comment by joa-quim** [comment]
Another later, still trying to restart the *grdimage alpha* work.

**Comment by joa-quim** [comment]
This could never have worked on Windows.
Code ``cd`` to ``.gmt/sessions`` and search for ``*.*`` skipping all subdirs
```
if (FindFileData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) continue;	/* Skip sub-directories */
```
which actually contain all data we want to delete. At the end when it tries to remove the ``sessions`` directory it fails because it contains the non-empty ``gmt6.xxxx`` sub-dirs.

**Comment by PaulWessel** [comment]
That is not how I read it: **clear** first finds all gmt* directories, then it calls _gmt_remove_dir_ on each of them.   That function cd's into that directory and gets a list of files that it removes, one by one.  Now that the dir is empty it can cd back up and remove the empty directory.  Clearly, those steps are taken since it does work on *nix.  Your FindFile line above is used _inside_ each gmt* directory to skip any subdirs inside those.  It is not doing that listing in .gmt/sessions but in a .gmt/sessions/gmtsubdir.
If you debug and step through  the code in your debugger, what is it really complaining about?

**Comment by joa-quim** [comment]
> If you debug and step through the code in your debugger, what is it really complaining about?

I did use it ofc.

```
uint64_t gmtlib_glob_list (struct GMT_CTRL *GMT, const char *pattern, char ***list) {
#ifdef WIN32
	uint64_t k = 0, n = 0;
	size_t n_alloc = GMT_SMALL_CHUNK;
	char **p = NULL, **file = NULL;
	if ((p = gmtlib_get_dir_list (GMT, ".", NULL)) == NULL) return 0;
```
returns a ``p[0] = NULL`` because it never cd'ed into the dirs implied by ``*pattern``

**Comment by PaulWessel** [comment]
OK, so it tries opendir on the current directory "." and that fails for you?
Sorry, another f***g zoom in 5 miinutes.

**Comment by joa-quim** [comment]
It does not try to opendir anything.
I wonder if we shouldn't simple do a sytem call on ``rmdir /s API->session_dir``. So much simpler
The shit is that I would like to have a clear sessions option to delete only older sub-dires. See
https://github.com/GenericMappingTools/GMT.jl/issues/378

**Comment by PaulWessel** [comment]
Well, the code would be a lot shorter and simpler if we could just do

```
#ifdef WIN32
printf (cmd, "rmdir /s %s", API->session_dir);
#else 
printf (cmd, "rm -rf %s", API->session_dir);
#endif 
if ((err = system (cmd))) {
message
}

```
Do you seen any trouble with this approacl @seisman ?

**Comment by PaulWessel** [comment]
Deleting directory tries is not well supported by the regular C APIs.

**Comment by seisman** [comment]
> I have it by default when starting a Julia session and started to see this recently.

I don't think it's a good idea to delete the session directory when starting a Julia session. It may destroy other GMT processes.

`rm -rf %s` is dangerous, unless we're confident that `API->session_dir` is always assigned to the correct path.

**Comment by PaulWessel** [comment]
We could be more specific (if that is OK in Windows), such as

rm -rf sessiondir/gmt?.*

which would target gmt6.#### files.  This brings up an issue.  I don't think it is super helpful to have the 6 in gmt6.xxxxx as eventually it will be 7.  Should we take this opportunity to rename that to  gmt_session.xxxxx and then do rm -ft <sessiondir>/gmt_session.* instead? ? That should be less dangerous since we are more specific.

**Comment by seisman** [comment]
> We could be more specific (if that is OK in Windows), such as
> 
> rm -rf sessiondir/gmt?.*
> 
> which would target gmt6.#### files

Yes, it's much safer.

>  Should we take this opportunity to rename that to gmt_session.xxxxx and then do rm -rf sessiondir/gmt_session.* instead? ? 

Yes to me.

**Comment by PaulWessel** [comment]
Hi @joa-quim, can Win do a similar rm, delete, or rmdir call of sorts on the list of directories

sessiondir/gmt_session.*

?

**Comment by joa-quim** [comment]
New ``gmt --show-userdir`` can be used to clear the contents of ``~/.gmt/sessions``. That's why I added it and it also allows other environments to be more picky on deletion. I'm about to commit a change in julia that deletes only ``gmt6.xxxx`` older than 1 hour (thanks to @htyeim)

And also thought on that ``6``. Yest we should get rid of it. It will screw us when we release a GMT7

**Comment by joa-quim** [comment]
Don't know how to do ``sessiondir/gmt_session.*`` on Win. Maybe ``rmdir /s /q sessiondir/gmt_session.*`` works

**Comment by PaulWessel** [comment]
From [this link](https://stackoverflow.com/questions/97875/rm-rf-equivalent-for-windows) maybe

rd /s /q directory

?

**Comment by PaulWessel** [comment]
Also https://www.ghacks.net/2017/07/18/how-to-delete-large-folders-in-windows-super-fast/

You have to test and tell me.

**Comment by joa-quim** [comment]
``rmdir /s /q directory`` works, What doesn't is ``rmdir /s /q blabla.*``

**Comment by PaulWessel** [comment]
Back to square one then.  Perhaps you can cobble together a #ifdef WIN solution since it is a oneliner on Unix.

**Comment by joa-quim** [comment]
But it's a one liner on Win too. 
``
sprintf(del_cmd, "rmdir /s /q %s/.gmt/sessions", GMT->session.HOMEDIR);
system(del_cmd);
``

**Comment by PaulWessel** [comment]
So @seisman said this

> unless we're confident that API->session_dir

Aren't we? We are the one setting it.  So in that case we could must delete the entire session dir as @joa-quim just posted.

**Comment by PaulWessel** [comment]
@joa-quim it is a oneliner if you dont try to add protection by insisting the directories to be removed must start with gmt_session.  That was @seisman point I think.

**Comment by joa-quim** [comment]
That would require finding all gmt.*** that are directories. Too much work (don't know how to do it) for very little. ``GMT->session.HOMEDIR/.gmt/sessions`` is already a unique GMT dir

**Comment by PaulWessel** [comment]
It is unique and I cannot see how users can conspire to do damage.  I suppose if you set

set GMT_USERDIR=C:windows/superimportantfiles

and created a sessions dir in there with all your bank information, and we delete that directory then you deserve it.  Remember, we are not deleting GMT->session.HOMEDIR/.gmt/sessions, but GMT->session.USERDIR/sessions.

**Comment by PaulWessel** [comment]
I want to get back to the initial reasoning for this.  I notice that I end up with stray old gmt6.#### directories in my session dir.  Sometimes that is because ctest with 20 threads collide, but other times it is probably scripts that crash and maybe exit, so there is no gmt end to remove them? Not sure.  However, since the user has no way of salvaging anything from the session dir (e.g., a partly built PS file), might it be better to implement a scheme where a failing module removes the specific gmt* session dir on its way out?

**Comment by joa-quim** [comment]
That would clear this all issue indeed.

**Comment by PaulWessel** [comment]
So if people on the command-line use the gmt --new-script they get one with **-e** set:

```
gmt --new-script
#!/usr/bin/env -S bash -e
# GMT modern mode bash template
# Date:    2020-06-16T13:29:59
# User:    pwessel
# Purpose: Purpose of this script
export GMT_SESSION_NAME=$$	# Set a unique session name
gmt begin figurename
	# Place modern session commands here
gmt end show
```

My understanding (that @seisman can correct if wrong) is that a script with -e that has a call returning an error quits and does not run through the following comments.  That is ideal I think since the following modules would not find a session dir after we remove it in a crashing module.

Not sure if there is an equivalent of -e for a DOS batch job?

**Comment by joa-quim** [comment]
Probably not. And we have the externals too that are not running shell scripts.

**Comment by joa-quim** [comment]
Another useful thing would be that when a modern session starts it checks if the ``gmt_session.xxxx`` where ``xxxx`` is the same as the newly starting session, remove the old one. From Julia, repeating ``gmtbegin()`` in same Julia session generates the same GMT session number.
