### ISSUE TITLE
doc/scripts/GMT_movie_progress.sh failed after PR #3477

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3479]
`doc/scripts/GMT_movie_progress.sh` fails after PR #3477 was merged.

**Actual output:**

![image](https://user-images.githubusercontent.com/3974108/84701896-c7dbac00-af23-11ea-90a8-0be55f58cf01.png)

**Expected output:**

![image](https://user-images.githubusercontent.com/3974108/84701912-ce6a2380-af23-11ea-8a6c-ae5bd6caaaac.png)

**Comment by PaulWessel** [comment]
I cannot immediately see how this affects **movie**.  Only **psbasemap** is used in this script, no **grdimage**, so it must be related to the changes in gmt_init.c.  However, looks to me those changes happen in _gmtinit_begin_module_sub_ which sets the rgb to white.  That function is called at the end of _gmt_init_module_.  We then have the module call _GMT_Parse_Common_ where the -B+g stuff is parsed.  So that is where beige is set and the _gmt_plotcanvas_ does its thing.  Then the paint bool is set to false at the end of _gmt_end_module_ which is called by _gmt_end_ at the end of the Session.  What am I missing?

**Comment by PaulWessel** [comment]
Two upcoming zoom meetings make it hard for me to do this but we need to fix these issues and run tests before merging in branches that break thinks.

**Comment by PaulWessel** [comment]
The problem has to do with how @joa-quim  added things to _gmt_end_module_.  if you look at the rest of that function you will see there is a shuffle between two structures GMT and Ccopy, a removal of GTM and a duplication from Ccopy, etc.  This is done to preserve settings between module calls.  And GMT may call another module at any time, such as happening inside the single psbasemap call because movie indicators were selected, forcing another psbasemap call.  What you put at the end violates all that.  I will see what I can do but I have another zoom.
