### ISSUE TITLE
grd2kml/grdcut warnings

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3492]
I am now seeing this in one of my julia tests
```
grdmath -R0/10/0/10 -I1 X -fg = a.grd

grd2kml a.grd -Naiai -I+
grdcut [WARNING]: Something went wrong - 2 extended nodes not set to NaN
grdcut [WARNING]: Expanded grid region implies the grid is no longer geographic
grdcut [WARNING]: Expanded grid region implies the grid is no longer geographic
grd2kml [NOTICE]: Extended grid size is by 512 by 512, tile size is 512 x 512
grd2kml [NOTICE]: Level 00: Tile size:        512 x 512 d Tiles:   1 by   1 =     1     1 mapped   0 empty [Original grid used]
grd2kml [NOTICE]: Done: 1 tiles (0 JPG and 1 PNG) written to directory aiai
```

**Comment by PaulWessel** [comment]
Looks like we are using gmt_M_grd_x_to_col in places without realizing what that function does: It returns the column number of the nearest node in the x-direction.  There is a 0.5 ofset in this equation to deal with the fact that the first pixel node is 0.5*xinc from the west boundary.  However, here in grdcut we are passing a previous w/e/s/n boundary for the original grid so that is for pixel grids off by 0.5.  Using those coordinates in gmt_M_grd_x_to_col means we land exactly half-way between pixel nodes and the rounding will go in our disfavour 50% of the time...

A quick grep shows other places where gmt_M_grd_x_to_col is given west+k*inc type coordinates and we hope to recover k or k+m, but for this to work with pixel grids we would have to pass west+(k+0.5)*inc for gmt_M_grd_x_to_col to return the right column.  Same for y of course.  What is unusual about grdcut here is that it actually checks and reports the problem by comparing the number of nodes set to zero before and after we extend the grid and fill the new nodes with NaN.  So here, there are 11 zeros before extension and 13 afterwards...

**Comment by PaulWessel** [comment]
Looking at all occurrences of _gmt_M_grd_x_to_col_ there are three files where we possibly are passing the wrong coordinates:

1. gmt_remote.c in determining which SRTM tiles to get
2. grdinfo.c in determining tiles (-D)
3. grdcut -N (@joa-quim's case)
4. grdcut -S

I will test these with both pixel and gridline grids to see if there are bugs in the other three cases as well.

**Comment by joa-quim** [comment]
Why is it still giving those warnings? There is no **-V** and nothing wrong with the command.
```
grd2kml a.grd -Naiai -I+
grdcut [WARNING]: Expanded grid region implies the grid is no longer geographic
grdcut [WARNING]: Expanded grid region implies the grid is no longer geographic
grd2kml [NOTICE]: Extended grid size is by 512 by 512, tile size is 512 x 512
grd2kml [NOTICE]: Level 00: Tile size:        512 x 512 d Tiles:   1 by   1 =     1     1 mapped   0 empty [Original grid used]
grd2kml [NOTICE]: Done: 1 tiles (0 JPG and 1 PNG) written to directory aiai
```

**Comment by PaulWessel** [comment]
The warning is because we end up with a region such as 0/512/-90/422 so we must turn off the "geo" flag and it because a Cartesian grid.  if you were doing gmt grdcut -R0/512/-90/422 myglobal1x2degreegrav.grd -Gnew.grd it is not unreasonable you get that warning.  Now, from within grdkml maybe less useful but then grdcut would need to check who is calling it.

The rest is info for the user.  It may take an hour to process a global high-res grid.

**Comment by joa-quim** [comment]
But the grid is ``-R0/10/0/10`` how come we end up with a ``0/512/-90/422``

**Comment by PaulWessel** [comment]
All NaNs except for your tiny box.  That is how the quadtree shit works.

**Comment by PaulWessel** [comment]
Remember. grd2kml is not to place an image in Google. psconvert does that.  grd2kml builds a quadtree.
