### ISSUE TITLE
psrose (rose) cannot make plots without frames

### ISSUE THREAD

**Issue by tianzeliu** [GenericMappingTools/gmt#3615]
I just found that `psrose (rose)` cannot make plots with frames. Even when I use the option -B+n it still plots a circular frame.

**Comment by PaulWessel** [comment]
It seems reasonable that **rose** should follow the same defaults as other maps.  Historically, it is doing its own frame plotting so that is why this issue appeared.  I think we want this behavior:

1. **-B+n**.  No circular frame, gridlines, or WESN labels.  Just the sector plotting should show.
2. **-B**0.  This should just draw the outline of the frame (circle or half-circle)
3. Default (no **-B** given):  Should be the same as **-B+n** I think.  Nobody expects a basemap in grdcontour if no -B is given either.

Current, no **-B** gives this interesting plot:

![map](https://user-images.githubusercontent.com/26473567/86668334-3e515400-bf8e-11ea-829a-bc6e7a053302.png)

Any objections to this plan, @GenericMappingTools/core ?

**Comment by PaulWessel** [comment]
The code clearly has an automatic mode where it turns on part of the machinery but not the circle or radial grids, for instance, only azimuthal.

**Comment by PaulWessel** [comment]
Apart from the clear goals above, I am finding other problems in **rose**.  In our _gallery.sh_ test script we have a typo regarding gridline intervals in azimuth: `-Byg190`, all the other places we use -`Byg90`, so a "1" slipped in.  But it does not matter since **psrose** simply _overrides_ that with a 30 degree selection if you did not specify an _annotation_ interval (never mind we do not annotate anyway except for the W,E,S,N labels).  So this is another bug: Ignoring the users gridline specification.  I know **rose** is old and has some quirks, but no other program automatically draws gridlines, so I think we must declare this a bug and fix it.  The goal must be for **-B** to work the same across the suite.  I assume @seisman agrees with this stand, yes?

**Comment by seisman** [comment]
Yes, sounds reasonable to me.

**Comment by PaulWessel** [comment]
Fixed by #3618.
