### ISSUE TITLE
Remove old netcdf bug workaround

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3920]
> This is a reminder to eventually remove the work-around code ingmt_nc around line 982 that was introduceddue to a bug in NetCDF. Search for https://bugtracking.unidata.ucar.edu/browse/NCF-187 in gmt_nc.c to find it
> 
> The NetCDF _FillValue bug (upstream bug report: https://bugtracking.unidata.ucar.edu/browse/NCF-187) was fixed in source on 2015-04-02. The current NetCDF version (4.3.3.1), released in February 2015, is the last with this bug.

It should now be safe to remove the renaming trick.  Putting this here so we do it.

**Comment by seisman** [comment]
FYI, CentOS 6 has 4.1.1 and CentOS 7 has 4.3.3.1.

**Comment by PaulWessel** [comment]
So 5 years later, old repos still have old stuff.  Sigh.

**Comment by holishing** [comment]
My comments below is just a possible solution for those "stable" distributions with this problem, I haven't try it though.

CentOS 6 is going to EOL in November 30th, 2020, we don't have to consider it soon.
`netcdf` in CentOS 7 may wants related bug-fix patch and file it in [CentOS Bug Tracker](https://bugs.centos.org/), if it is patched successfully and that patch accepted by CentOS maintainer, we can reconsider removing workaround.  (Although I don't know where the workaround is)

Because the bug URL link above is missing, there is related commit about netcdf NCF-187 bugs:
- https://github.com/Unidata/netcdf-c/commit/6a6e8c08a6ca684cf46c99400622555955495088
- https://github.com/Unidata/netcdf-c/commit/ab18a2e17cf8e6edcc660b410c844d0bbfa906e6

**Comment by seisman** [comment]
One more note: Ubuntu 14.04 provides netcdf 4.1.3, which will be EOL in 2022/04.

**Comment by seisman** [comment]
It would be helpful if @PaulWessel can provide more information about the bug, for example:

1. when was the bug introduced in netcdf (the links in the top post is broken)
2. the patch to fix the bug

then we may ask "Orion Poplawski" (the maintainer of both netCDF and GMT) to see if EPEL would like to apply the related patch.

**Comment by PaulWessel** [comment]
The gmt_nc.c code has comments related to this:

> /* netCDF-4 has a bug and crash when * rewriting the _FillValue attribute in netCDF-4 files
>   https://bugtracking.unidata.ucar.edu/browse/NCF-187
>   o work-around it we implement the renaming trick advised on NCF-133
>   Edit: This work-around should eventually be removed because the bug was fixed as of 2015-04-02 (any version >4.3.3.1 should be fine).
> */

Since one of the lines (here the double precision)

	nc_put_att_double (ncid, z_id, "_FillValue", z_type, 1U, &header->nan_value);

crashes in Netcdf < 4.3.3.1, the workaround specified by Unidata was to rename the fill attribute from _FillValue to _fillValue, update the value, then rename the attribute back...

**Comment by joa-quim** [comment]
Let it be part of history. It's not bothering anything. No motivation to spend time seeing if a change doesn't break anything.
Close? (tic, toc, tic, toc, ...)

**Comment by PaulWessel** [comment]
I agree.  We close this issue now.
