### ISSUE TITLE
grd2cpt/equalarea.sh fails on master branch

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3940]
The test fails on all platforms, with a RMS=0.0035, slightly greater than the 0.003 threshold.

Here is the diff image with the diff highlighted by black.

![equalarea](https://user-images.githubusercontent.com/3974108/90028481-b72b8600-dc87-11ea-98ba-b9d04ac2d26f.png)

**Comment by PaulWessel** [comment]
Interesting.  I ran release build checks and passes.  What might be the difference in those setups? Differences in qsort?

**Comment by PaulWessel** [comment]
I've updated the script in master to write the cdf.txt file.  Could you please run it again and share the cdf.txt file from the failing script, @seisman ?

**Comment by seisman** [comment]
cdf.txt from macOS CI: [cdf.txt](https://github.com/GenericMappingTools/gmt/files/5076827/cdf.txt)

**Comment by PaulWessel** [comment]
One notable difference is that the z-values in cdf.txt from the CI are all **integer** meters in elevations while mine is in multiples of 0.5 meter.  Per the 05m remote grid, the values are in 0.5 m so for some reason the CI is using an older version of the DEM when we simply used the integers as is as meters?  Here are the first 10 lines of the two files pasted together - mine on left:

```
-5519	1.8945577267e-06	-5519	1.8945577267e-06
-5470.5	3.7891154534e-06	-5470	3.7891154534e-06
-5454	5.68418727198e-06	-5454	5.68418727198e-06
-5448	7.5790039773e-06	-5448	7.5790039773e-06
-5422	9.47329863266e-06	-5422	9.47329863266e-06
-5420	1.13737523861e-05	-5420	1.13737523861e-05
-5417.5	1.32663853947e-05	-5418	1.32663853947e-05
-5388.5	1.51609438035e-05	-5388	1.51609438035e-05
-5375.5	1.70616804098e-05	-5376	1.70616804098e-05
-5364.5	1.89572492673e-05	-5364	1.89572492673e-05
```

Because of this, there are subtle differences in the cdf values as well into the file.  I checked, your file has no decimal elevations:

`awk '{print $1}' ~/Downloads/cdf.txt | grep '\.'`

This may explain the failures of that imagepluscpt Madagascar case as well.  Why integer meters on CI?

**Comment by seisman** [comment]
The remote files were cached in the CI on 20200702. Did we update the grids after that?

**Comment by PaulWessel** [comment]
No, server files seems to be from June 1.  I just removed my files in .gmt and obtained a new set and it has 0.5 scale.

**Comment by PaulWessel** [comment]
Key line in grdinfo output for the file:

S90E000.earth_relief_05m_p.nc: scale_factor: 0.5 add_offset: 0 packed z-range: [-21418,14354]

**Comment by seisman** [comment]
Running `grd2xyz` on CI gives:
```
gmt grd2xyz @earth_relief_05m -R0/5/0/5
0.0416666666667	4.95833333333	-3478
0.125	4.95833333333	-3490
0.208333333333	4.95833333333	-3322
0.291666666667	4.95833333333	-3236
0.375	4.95833333333	-3416
0.458333333333	4.95833333333	-3422
0.541666666667	4.95833333333	-3410
0.625	4.95833333333	-3280
0.708333333333	4.95833333333	-3083
0.791666666667	4.95833333333	-2998
0.875	4.95833333333	-2984
```
It seems the cached grids are out-of-date.

**Comment by seisman** [comment]
After updating the CI caches, the test passes.

**Comment by seisman** [comment]
After updating the CI caches, there are some new failures:
```
	201 - ex33/ex33.sh (Failed)
	202 - ex34/ex34.sh (Failed)
	223 - anim04/anim04.sh (Failed)
	359 - grdcontour/contours.sh (Failed)
	373 - grdcontour/varpens.sh (Failed)
	399 - grdfill/constfill.sh (Timeout)
	400 - grdfill/nnfill.sh (Timeout)
	402 - grdfill/splinefill.sh (Timeout)
	417 - grdimage/autointense.sh (Failed)
	485 - grdview/autointense.sh (Failed)
	492 - grdview/texture.sh (Failed)
	523 - modern/imagepluscpt.sh (Failed)
```
I have similar failures locally.

**Comment by PaulWessel** [comment]
I need to check this; there seems to be some inconsistencies.  My 01m tiles in my .gmt do not have 0.5 scaling, whereas the original full-size grid from which they derive, do.  The step in-between are making JP2 etc.  But you would think the tiles we recover need to reflect the original setup.

**Comment by PaulWessel** [comment]
Looking at one of my 01m_p tiles the command was (I removed the full path for clarity)

`grdconvert S60W120.earth_relief_01m_p.jp2 -GS60W120.earth_relief_01m_p.nc=ns -fg -Vq --IO_NC4_DEFLATION_LEVEL=9 --GMT_HISTORY=false -Z+s0.5+o0`

So unlike the initial script that downfilters and writes the global grids, there is no =ns+s0.5+o0 given, so we store as integers.  That command happens inside GMT during download, so that is a bug to fix.  The -Z scales the JP2 integers to meters, but then we just write those out as is.

**Comment by PaulWessel** [comment]
I got these (leaving off the known failures):

	201 - ex33/ex33.sh (Failed)
	202 - ex34/ex34.sh (Failed)
	223 - anim04/anim04.sh (Failed)
	359 - grdcontour/contours.sh (Failed)
	373 - grdcontour/varpens.sh (Failed)
	492 - grdview/texture.sh (Failed)
	523 - modern/imagepluscpt.sh (Failed)

Three of yours are timeout so took too long I guess? That leaves the **autointense** scripts as the difference.

**Comment by PaulWessel** [comment]
WOuld you like to update the PS for ex33,34, anim04,contours,varpens,texture,imagepluscpt for now? I want to finish testing anim07 before I do others.

**Comment by seisman** [comment]
OK.
