### ISSUE TITLE
Baddly breaking in externals

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3987]
Something in #3848 broke badly the externals.
Either this in Matlab
```
G = gmtmex('grdmath -R0/10/0/10 -I0.1 X Y MUL =');
gmtmex('write lixo.grd -Tg', G)
gmtmex('write lixo.grd -Tg', G) 
```
or this in Julia
```
julia> G = GMT.peaks();
julia> gmtwrite("lixo.grd", G)
julia> gmtwrite("lixo.grd", G)
```
work for the first writing but hangs completely on second and one has to kill the processes.

**Comment by PaulWessel** [comment]
Hm, OK, will take a while today as I have meetings etc.  Feel free to diagnose if you have time.

**Comment by joa-quim** [comment]
I fear it can be a Win only shit.

**Comment by joa-quim** [comment]
OK, here is what's happening.

- I'm in a camping with no internet and that had happening often so my ``gmt_data_server.txt`` is older than 1 day.

- Obviously without internet gmtremote_get_url() fails to update the ``gmt_data_server.txt`` but by doing so it doesn't remove the ``c:\TMP\gmt_data_server.txt.new.download`` file, and most importantly it doesn't CLOSE it.

- Next time the program is run ``gmtlib_file_lock()`` really honors the comment
``if (!LockFileEx(hand, LOCKFILE_EXCLUSIVE_LOCK, 0, 1, 0, &over)) /* Will block until exclusive lock is acquired */`` and the process is blocked infinitely because  ``c:\TMP\gmt_data_server.txt.new.download`` is still open.


Now the other issue is ``GMT_Read_Data()`` should not have called ``gmt_refresh_server()`` in first place because it's not dealing with any @file.

**Comment by PaulWessel** [comment]
Thanks, will work on this when I get back. Good test, that camping trip.

**Comment by PaulWessel** [comment]
You said accessing a memory file @GMTAPI@ triggered all the gmt_refresh and curl, etc? So maybe I have a naive check for "@" as first character somewhere without excluding these mem files.

**Comment by joa-quim** [comment]
Yes, this all happened with a simple ``gmtwrite("lixo.grd", G)``

**Comment by PaulWessel** [comment]
I am looking at the two functions  _gmtremote_get_url_ and _gmt_download_file_ in gmt_remote.c.  They have a lot of code duplication I would like to eliminate.  There reason there are two is this:

1. _gmtremote_get_url_ is only used to get the hash table and the dataserver table. Unlike _gmt_download_file_ it adds a 10 second timeout, meaning if it takes that long we quit.  Cannot do that on a large grid.  Also, it has a bit different error messages, and it sets the refresh flag to true so the same process wont do this again.
2. _gmt_download_file_ is used to get cache and remote data files, so no timeout.  It also has option to check the file size first and skip large files.  It also starts off by checking the GMT_Defaults setting for download etc and skips download if not allowed.

I think I can make them a bit more similar.  Some of the checks from _gmt_download_file_ should also be in _gmtremote_get_url_.  The file size and timing could be function parameter settings. In fact, I think I will try to make a single function that combines these, since it is just way too much duplicated code otherwise.

**Comment by PaulWessel** [comment]
Improvement committed as #3998.
