### ISSUE TITLE
gmt_geo_to_xy_line crash when GMT->current.map.dlat = Inf

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4055]
```
gmt begin
gmt subplot begin 3x3  -Blrbt -M0 -F5/0+w1,dashed
plot [ERROR]: Option -R parsing failure. Correct syntax:
        -R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
          Append +r if giving lower left and upper right coordinates
        -Rg or -Rd for global domain
        -R<grdfile> to take the domain from a grid file
plot [ERROR]: Offending option -R0/1.9685/0/0

gmt coast  -Rd -JG30/30/? -Bg -c0,0 -Gred -Da
```

Last command crashes inside ``gmtplot_map_lonline()``, on the 
``GMT->current.plot.n = gmt_geo_to_xy_line (GMT, llon, llat, nn);``
because ``llon, llat`` are NULL. That happens because ``GMT->current.map.dlat = Inf`` in the ``gmtlib_lonpath()`` call and the arrays are not allocated.

Not obvious where to do the right check for this and reurn an error code.

**Comment by PaulWessel** [comment]
Are you leaving something out here? I see a call to subplot and then plot complains? So this is because of the +1,dashed option which ends up calling plot, but you have a 0 height for the panel?  I understand you have a projection below but that is going to give you a circle so you could do -F5/5+w1,dashed perhaps?

**Comment by PaulWessel** [comment]
The only solution I can think of is to defer the drawing of the outline until subplot end.  However, that could not work if anyone wanted to paint instead +g.

**Comment by joa-quim** [comment]
Well, the point here is that it shouldn't crash. Just errors if it has to. The code is generated by
```
		if (haskey(d, :width))
			out *= string(d[:width], '/')
			if (!haskey(d, :height))  out *= '0'	# Allow this for geog cases
			else                      out *= string(d[:height])
			end
		end
```
Isn't ``5/0`` allowed?

**Comment by PaulWessel** [comment]
Dont know for sure without looking - and have meeting in 3 minutes - but 5/0 might be allowed in some -J settings but I dont see it listed for -F.

**Comment by PaulWessel** [comment]
I've started to add some checks here but all subplot begins starts with laying down at least a blank psxy -R -J -O -T so that all future panels are overlays. The subplot dimension (individual or overall) has to be known, it cannot be 0.
So I can add a hard error check if width or height is zero and exit.  Not much else that can be done.

**Comment by joa-quim** [comment]
Curiously, this one crashes for the exact same reason  (``GMT->current.map.dlat = Inf``)
```
gmt pscoast -Rd -J+proj=tobmerc+width=12c -Bg -Gred -V -png map
```
[tobmerc](https://proj.org/operations/projections/tobmerc.html) is an *equal-area Mercator*.

**Comment by joa-quim** [comment]
Not solved. The main issue is that ``gmt_geo_to_xy_line()`` crash in ``gmtplot_map_lonline()`` because ``gmtlib_lonpath()`` did not allocate the *llon,llat* arrays. And as added ``pscoast -Rd -J+proj=tobmerc+width=12c`` also triggers that situation.

**Comment by PaulWessel** [comment]
But gmt subplot now returns an error. What module is complaining about the lon,lat arrays?

**Comment by PaulWessel** [comment]
I man, I get that crash with

gmt pscoast -Rd -J+proj=tobmerc+width=12c -Bg -Gred -V -png map

but this issue was about subplot.

**Comment by PaulWessel** [comment]
I can comment out the line 
	`//GMT->current.map.n_lon_nodes = GMT->current.map.n_lat_nodes = 0;`
at the top of gmt_proj_setup since there is no case for this projcetion.  However, I dont think -Rd -Rg will work as it blows at the poles no? This is

`gmt coast -Gred -R-180/180/-89.9/89.9 -J+proj=tobmerc+width=12c -Bg -V -png blow`

![blow](https://user-images.githubusercontent.com/26473567/91378243-ab79ac80-e7bb-11ea-8cf8-375a75422968.png)

**Comment by joa-quim** [comment]
Yes, this is still a Mercator. But the main point is not on how to avoid the error but instead preventing the crash. Every time there is a crash, it kills the Julia session (and others) so crashes is something we must prevent at all costs. The Fuzzy-testing that Kurt talked you about is a crash hunter.
