### ISSUE TITLE
grdcut -S produces wrong grids for tiled grids

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4206]
```
$ gmt grdcut @earth_relief_06m -Goutput_06m.nc -S45/30/500k+n
$ gmt grdinfo output_06m.nc -C
output_06m.nc	39.8	50.2	25.5	34.5	-78.5	2407.5	0.1	0.1	104	90	1	1


$ gmt grdcut @earth_relief_05m -Goutput_05m.nc -S45/30/500k+n                                                                 
$ gmt grdinfo output_05m.nc -C
output_05m.nc	-180	180	-90	90	-74.5	2415.5	0.0833333333333	0.0833333333333	4320	2160	1	1
```

**Comment by PaulWessel** [comment]
Good one.  So -S is a strange proxy for -R.  Well inside the module we convert -S into a -R subset and use that to read the data.  By that time, the gmt_module_init function has already defaulted to -Rd (since no -R is given) and created the list of tiles.  When the list of tiles is opened we end up reading the full data set.  Your example command would be painful if 15s was used I think.

I think this module option -S is very unique and only happens here.  Yet, we need that translation from -S to -R to happen earlier, before tile list is generated.  I think the only option is to detect that the module is grdcut and that -S was used and then deal with the -R stuff then.  We would build the internal wesn so we only get tiles that make sense.

Seems like a reasonable plan? The -S -> -R is independent of the grid etc.
