### ISSUE TITLE
histogram can be extremely slow

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4230]
In Julia I can compute the image histogram directly from the Image type, and
```
julia> I = mat2img(rand(UInt8,2000,2000), noconv=1);

julia> @time histogram(I, I=:o);
  5.070120 seconds (201 allocations: 3.831 MiB)
```
Now, if I change the data type the times double
```
julia> I = mat2img(rand(UInt16,2000,2000), noconv=1);

julia> @time histogram(I, I=:o);
  9.762903 seconds (202 allocations: 8.642 MiB)
```
With a true Landsat image the timings are awful. In Mirone I compute the histogram of this image almost instantaneously. 
```
julia> fname = "C:\\SIG_AnaliseDadosSatelite\\madeira\\LC08_L1TP_208037_20140110_20170426_01_T1_2014-01-10\\LC08_L1TP_208037_20140110_20170426_01_T1_2014-01-10_B4.TIF";

julia> I = gmtread(fname);

julia> size(I)
(7891, 7761)

julia> @time histogram(I, I=:o);
 69.001616 seconds (203 allocations: 117.144 MiB, 0.01% gc time)
```

I'm using ``GMT_Create_Data(API, GMT_IS_MATRIX|GMT_VIA_MATRIX, ...`` to transmit the data into GMT and keeping the original data type, but given the results above I don't know if that is being respected.

**Comment by PaulWessel** [comment]
histogram expects a single data column, so not sue what is happening if you pass a big matrix. Do you mean passing I(:) using matlab syntax?

**Comment by joa-quim** [comment]
[Yes](https://github.com/GenericMappingTools/GMT.jl/blob/master/src/pshistogram.jl#L107)

**Comment by joa-quim** [comment]
A bit of investigation shows that it calls [this function](https://github.com/GenericMappingTools/gmt/blob/master/src/pshistogram.c#L157) for **each** data point. Wow, that's a **lot** of computations for each point. And in top of it, it had to sort the entire input array. For images we easily have millions of points. Sorting tat is not cheap.

A side effect is that changes the input (sorts it), so for externals the image/grid would be screwed.

As an experiment I managed to trick ``pscountour`` by computing the histogram beforehand in Julia (trivial for integer types and ``bin=1``) and telling it to compute an weighted histogram, where the weights are the histogram itself and the same big Landsat image that took ~ 70sec now (and this includes the PS fig generation)
```
julia> @time histogram(I, show=1);
  1.826065 seconds (309 allocations: 520.094 KiB)
```

**Comment by PaulWessel** [comment]
Agree that we need to check if external or not so we dont mess with readonly memory.
Not sure if that function causes 70 second runtime. Would you be able to test by adding some timer statements.  I think we usually end up finding that there is slow i/o, no?  For that we need a new strategy for handing i/o that would minimize too many checks.  While I did add some improvements, its is not enough.  For instance, instead of having function pointers for reading a record, we could instead try to have a higher level selection so that the entire file is read by a function that knows what to do without checking each record.

**Comment by joa-quim** [comment]
It’s not the IO. I run it with -V and could see that most of the time was spent after first verbose messages were print. The real culprit is the algorithm. For cont bin with we can have much simpler as faster algorithms to compute the histogram that don’t require sorting.

**Comment by PaulWessel** [comment]
Yes agree on that.  I think ad added that also because for variable bin sizes it is required.  OK, will have a look at this once finished with the map scale origin issue #4227.

**Comment by PaulWessel** [comment]
So the sorting happens in _pshistogram_get_loc_scl_ and is slow despite _qsort_, etc.  It is needed if **-N** requires it but it is always called and we report the results.  So some options here:

To remain backwards compatible:

- If **-V** is selected then we must sort so we can report mean median mode etc
- If **-V** is not selected but **-N** is used with argument 1 or 2 then we sort
- Else we don't.

I guess this is a good solution.  Agree?

**Comment by joa-quim** [comment]
Almost. I find that sorting is a very high price for a simple **-V**, which should report only what is being done without requesting any further calculus. Maybe move that to a higher **-V** level.

But isn't your algorithm in ``pshistogram_get_bin()`` dependent on on data being sorted? (confess that I don't fully understand how it works.

**Comment by PaulWessel** [comment]
I now have to algos, fixed interval or variable, so taht takes care of that dependency.
But I think -V is useful to learn about the data, you are actively **asking** for information.  I think this is reasonable, otherwise we are breaking backwards compatibility.  If you are concerned about speed you don't give -V.

**Comment by joa-quim** [comment]
Only half convinced. **-V** with externals will oblige a data copy too. That is a very very high price (for image or grid histograms) for a **-V** option.

For variable intervals an alternative algo would be to compute the distance to the center of each bin and assign according to the minimum distance. This is kind of similar to k-means clustering and would avoid sorting and data copy for externals when no **-N1|2** but no idea on the speed of it.

**Comment by PaulWessel** [comment]
OK, I did not deal with the external yet so don't approve the PR.  I will add that.
We would have to break backwards compatibility then to not sort the array if -V is given.  Late lunch starting.

**Comment by PaulWessel** [comment]
Wait a minute.  We read input one record at the time in histogram, so input data is copied into our locally allocated data array.  Thus, your memory array is not compromised if sorting takes place.

**Comment by joa-quim** [comment]
That's not good news. Images (or grids) can be pretty big.
Can you add an option to ingest input already binned? A Mx2 array where first col holds the bin boundaries and second the countings? That would make my hack *official* and duplicating it is negligible because it's always a small dataset.

**Comment by PaulWessel** [comment]
I can look at that.  But let's keep that (which will requires some sort of option flag) separate from this which fixes a bunch of stuff anyway.

**Comment by joa-quim** [comment]
Right. And the other more general thing is that the IO for external's data should be different. Lots of the tests applied while reading data files are very likely not needed when reading from memory and pointer copies could avoid data duplication.

**Comment by PaulWessel** [comment]
If you look at libraries like Lapack, many functions till take some matrix and vector and typically return the solution via the input vector and state in the docs that the input matrix will be destroyed (i.e., overwritten).  So if you care about those you make a copy before calling.  The question then is should GMT behave the same?  If you want to call histogram with an array but you want to use it later, perhaps **you** make copy and pass that instead of us fussing to learn and know what should and should not be touched?  I dont think we can always know.

**Comment by PaulWessel** [comment]
Part of the answer to your question lies in the C refactor.  If you were to call a future `GMTAPI_histogram (double *data, uint64_t n_data, double *bins, uint64_t bins, double *counts)` from Julia then you would be in charge of the i/o; same with Python and perhaps down the road Matlab.  The complications you have are all due to GMT doing the i/o whether you have a file or a ready-to-go array.  I think trying to improve things under the current system can be done, such as yanking all the rec-by-rec i/o (in place like **histogram** and many other modules) as it is a bit easier to import an external array at the per-table level than at the per-record level.  In either case, the issue of whether all these functions should allow true read-only memory or be allowed to destroy the passed memory via sorting of clobbering of some kind could also be discussed.  It adds complexity inside GMT if we have to have two paths for GMT allocated memory and external memory.  Again, many libraries state they will clobber some of the input arrays.  Would be interesting to hear the perspectives of @leouieda and @seisman on this as well.

**Comment by joa-quim** [comment]
... and it's not only data duplication. It's type conversion too. This ``histogram`` example is enlightening of the issue. If we want to compute the histogram of uint8 images, the data is converted to doubles when stored in the internal copy. That's a 8x fold. if we want GMT to behave more and more as a library this aspects are very important.

And here we are again in our old discussion of RAM/Disk vs programmer time

**Comment by PaulWessel** [comment]
Yes, agree on the type conversion.  You could imagine we instead had `GMTAPI_histogram (void *data, uint64_t n_data, enum datatype, double *bins, uint64_t bins, uint64_t *counts);` were we internally have a switch system so that each case is handled directly.  So you just pass your byte array in and set datatype to **GMT_CHAR** and off you go with no conversion.
Because the refactor frees us from the i/o aspect it does allow us to focus a bit more on efficiency.  It is really hard to do with the current i/o-based system, but a lot easier if we do as suggested here.  Not all algorithms need to deal with that wide range of input types.  I.e., I don't think we want GMTAPI_surface to accept char data for gridding since those calculations requires float for sure.

**Comment by PaulWessel** [comment]
Perhaps histogram is a good candidate for a first example of the refactoring.

**Comment by joa-quim** [comment]
Shell we ping her (@meghan) 😄 ?

**Comment by PaulWessel** [comment]
So I have told Meghan she is our unanimous choice and I am dealing the the oppressive RCUH paperwork [like calling supervisor to confirm stuff - done yesterday] before we can actually present an offer and negotiate over timeline.  So I think best (from a HR perspective) to just wait a bit.  We plan to chat next week and hopefully RCUH won't spend too long time to "approve" our process.

**Comment by joa-quim** [comment]
Tried only now. Yes faster, but still much slower then my Julia version
```
# This one computes the histo inside GMT
julia> @time histogram(I[:], T=1, show=1);
  9.675408 seconds (492.23 k allocations: 143.094 MiB, 0.04% gc time)

# and this computes it in Julia nd sends it in to plot
julia> @time histogram(I, T=1, full_histo=true, show=1);
  1.407632 seconds (346 allocations: 772.656 KiB)

# And this runs the histo function twice to compute also nice boundings for contrast enhancement
# via histogram stretch when converting to UInt8. All in a single command. This is the beauty of GMT.jl
julia> @time histogram(I, auto=true, show=1);
  2.917943 seconds (1.52 k allocations: 846.578 KiB)
```

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/93836280-19f64100-fc7a-11ea-913f-52a8f660abfd.png)

**Comment by PaulWessel** [comment]
Sure, and most of those 9 seconds is "reading" into GMT.  Was 6+ seconds on my macPro, maybe more on your laptop.

**Comment by PaulWessel** [comment]
Since histogram is no longer extremely slow as we changed so that the sorting/median/mode calculations happen when requested, shall we close this one? Further speedup lies elsewhere I think (C refactor).

**Comment by leouieda** [comment]
I agree that this seems like a good candidate for experiments on what a GMT API could look like. Clobbering the input is probably fine as long as it is very explicit in the documentation that this happens. Perhaps having an option for not doing it and making a copy (set to true by default) would be useful. That way the default is secure and users and set it to false to get a memory/speed boost if they know what they are doing. This is true for a lot of the C extensions in Python.

**Comment by PaulWessel** [comment]
OK, there are pos and cons here. A histogram function is a very generic thing and not something people might go looking for in GMT (compared to gridding, for instance).  However, I agree it is also a very simple thing to do and could serve as a model for what _gmt_lib_function_ should look like, etc.  It may be simple to do for someone with less C skills like Meghan to tackle.  I am sure we will explore the balance between what basic functionality shall be in that function vs what extra is done in the current module (apart from i/o).  I.e.,, how many of the module options must be passed into the function and how many are simply for the module to use to prepare the call.  Kind of fun!

**Comment by leouieda** [comment]
Also worth remembering that we don’t need (or want actually) a 1:1 mapping of modules to functions. Most modules should probably more than one function. A good rule of thumb is that if you need a flag to modify the type of output (grid vs points, PS vs data), then you probably want 2 functions (with perhaps an underlying private function in common).

**Comment by joa-quim** [comment]
Solved as much as it ca be, I think.
