### ISSUE TITLE
Surface -R -I affected by input type. 

### ISSUE THREAD

**Issue by cg-david** [GenericMappingTools/gmt#428]
**Description of the problem**

Hi @all. 
So I have been using GMT block*whatever and surface successfully a lot and wrote some batch files with it. I still face one particular problem all the time. I have been able to work around it by trial and error a few times, but I can't find the error I make in the input. I basically have an area of interest, which I define with -R and a grid increment with -I. 
If I keep -R constant but change the input of -I to either meter or seconds, surface will interpolate in one instance, but doesn't find a solution for the other instance. Same for grid area. Sometimes I have to give -R very precise coordinates (say until 10^-5 precision), sometimes I only round to the next integer lat lon value and crop the grid. 
How do I successfully use surface with any input? Or asked differently: What mistake am I doing again?

Thanks in advance for your help!

**Full script that generated the error**

0.) Initial command. Works well.
```
gmt blockmedian InXYZ.xyz -R73.40000/73.47000/-0.34000/-0.25000 -I0.161697s/0.161699s > $tmp -V
gmt surface $tmp -R73.40000/73.47000/-0.34000/-0.25000 -I0.161697s/0.161699s -T1 -GGridOut.grd -V
```
1.) Changed Increments to 5m - gives error (1)
```
gmt blockmedian InXYZ.xyz -R73.40000/73.47000/-0.34000/-0.25000 -I5.0e/5.0e > $tmp -V
gmt surface $tmp -R73.40000/73.47000/-0.34000/-0.25000 -I5.0e/5.0e -T1 -GGridOut.grd -V
```

**Full error message (1)**

```
blockmedian: Processing input table data
blockmedian: W:    73.400000 E:    73.470000 S:    -0.340000 N:    -0.250000 n_columns: 1558 n_rows: 2003
blockmedian: N read: 1281531 N used: 1281531 outside_area: 0 N cells filled: 130455
surface: Grid domain: W:    73.400000 E:    73.470000 S:    -0.340000 N:    -0.250000 n_columns: 1557 n_rows: 2002 [gridline registration]
surface: Warning: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface: Hint: Choosing -R   73.399056/   73.470989/   -0.341034/   -0.248966 [n_columns = 1600, n_rows = 2048] might cut run time by a factor of 712.25144

```

2.) Changed Increments to 7.5m. Works well.  
```
gmt blockmedian InXYZ.xyz -R73.40000/73.47000/-0.34000/-0.25000 -I7.5e/7.5e > $tmp -V
gmt surface $tmp -R73.40000/73.47000/-0.34000/-0.25000 -I7.5e/7.5e -T1 -GGridOut.grd -V
```

3.) Decreased Area to almost actual area of XYZ points - gives error (3)  
```
gmt blockmedian InXYZ.xyz -R73.40796/73.46730/-0.33071/-0.25471 -I7.5e/7.5e > $tmp -V
gmt surface $tmp -R73.40796/73.46730/-0.33071/-0.25471 -I7.5e/7.5e -T1 -GGGridOut.grd -V
```

**Full error message (3)**

```
blockmedian: W:    73.407960 E:    73.467300 S:    -0.330710 N:    -0.254710 n_columns: 881 n_rows: 1128
blockmedian: N read: 1281531 N used: 1281531 outside_area: 0 N cells filled: 84828
surface: Grid domain: W:    73.407960 E:    73.467300 S:    -0.330710 N:    -0.254710 n_columns: 880 n_rows: 1127 [gridline registration]
surface: Warning: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface: Hint: Choosing -R   73.407286/   73.467974/   -0.331519/   -0.253833 [n_columns = 900, n_rows = 1152] might cut run time by a factor of 394.45
```

4.) Changed Increments to 7.5m equivalent in seconds - gives error (4)  
```
gmt blockmedian $xyzD -R73.40000/73.47000/-0.34000/-0.25000 -I0.242545s/0.242548s > $tmp -V
gmt surface $tmp -R73.40000/73.47000/-0.34000/-0.25000 -I0.242545s/0.242548s -T1 -G$grdD -V
```

**Full error message (4)**

```
blockmedian: N read: 1281531 N used: 1281531 outside_area: 0 N cells filled: 84920
surface: Grid domain: W:    73.400000 E:    73.470000 S:    -0.340000 N:    -0.250000 n_columns: 1039 n_rows: 1336 [gridline registration]
surface: Warning: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface: Hint: Choosing -R   73.398653/   73.471415/   -0.340472/   -0.249528 [n_columns = 1080, n_rows = 1350] might cut run time by a factor of 447.18163
```

**System information**

* Operating system: Linux (elementaryOS, Ubuntu 18.04 based)
* Version of GMT: 5.4.3

**Comment by PaulWessel** [comment]
A few comments from me:

- Technical: Specifying grid increments in distance units (meters, km, etc) for geographic (lon, lat) grids triggers a conversion from the given increment to the equivalent increment in degrees.  This is done differently for longitude and latitude of course and depends on chosen ellipsoid, but ultimately is a great-circle approximation.  For latitude we do h->inc[GMT_Y] / DIST_M_PR_DEG while for longitude we do h->inc[GMT_X] / (DIST_M_PR_DEG * cosd (0.5 * (h->wesn[YLO] + h->wesn[YHI]))).  The resulting degree increments may not exactlly match what you entered explicitly with the 's' unit identifier.  So, there may be rounding off in ways you don't want, resulting in prime numbers at times.  You can improve this via -Q but with the never-ending decimals in some increments that is still a challenge.
- Philosophical: I personally would never grid geographic (lon/lat) data and use length units as increments, due to the above conversion.  I find it much cleaner to specify intervals in spherical degrees or seconds.  That way I control the grid dimensions directly and all is well.  Alternatively, if I am far from Equator and concerned about the difference in lon and lat increments in degrees I would project all data to a local projection (e.g., UTM or whatever) to yield meters, and then I would grid using meters as the increment.  I strongly suggest you use one of those approaches.  I also personally dislike "ugly" increments like 0.161697s and prefer something that is easily divisible into a full degree.  If this choice is dictated by a desired increment in meters then better to go the projection route I think.

**Comment by PaulWessel** [comment]
Are there more comments on this from @cg-david ?

**Comment by PaulWessel** [comment]
I have added the essence of my Feb 14 comment to the surface man page as a Note.
