### ISSUE TITLE
colorbar triangles are unclosed

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4303]
Here is a screenshot of `doc/scripts/GMT_App_M_2.ps` after I changed the foreground color to yellow: 

![image](https://user-images.githubusercontent.com/3974108/95515746-1c4fdf00-098c-11eb-99c8-77ab32a32433.png)

Closed triangles may look better.

**Comment by PaulWessel** [comment]
So I immediately implemented the "fix" of duplicating the first coordinates and plotting a closed 4-point triangle instead.  But then I learned why I had not done that before: 

![Untitled](https://user-images.githubusercontent.com/26473567/95521152-97050400-0964-11eb-8457-594ab5cdcd43.png)

Because of the beveled joints it now sticks outside the width of the whole bar.  The solution is to fiddle with the geometry and adjust the two x-coordinates so that it fits perfectly.  This depends on angles and pen widths.  I think that is the best solution, no?

**Comment by seisman** [comment]
> The solution is to fiddle with the geometry and adjust the two x-coordinates so that it fits perfectly.

Yes if it's not too much work.

**Comment by PaulWessel** [comment]
I think we only need to fiddle with -L<gap> is used, right? The regular setup works as intended and it does shrink its coordinates to fit perfectly.  FOr the one with the gap we do want to close the triangle and change the coordinates further so that it does not stick outside.

**Comment by seisman** [comment]
> I think we only need to fiddle with -L is used, right? The regular setup works as intended and it does shrink its coordinates to fit perfectly. FOr the one with the gap we do want to close the triangle and change the coordinates further so that it does not stick outside.

Yes
