### ISSUE TITLE
Sometimes subplot begin requires -J

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4318]
```
gmt begin ex01

gmt subplot begin 2x1  -T"Low Order Geoid" -Rd  -Blrtb -M0.5 -A -Fs16/0
text [ERROR]: Could not parse -nan(ind) into Geographical, Cartesian, or Temporal coordinates!
text [ERROR]: Option -R parsing failure. Correct syntax:
        -R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
          Append +r if giving lower left and upper right coordinates
        -Rg or -Rd for global domain
        -R<grdfile> to take the domain from a grid file
text [ERROR]: Offending option -R0/6.29921/0/-nan(ind)
```

Besides the error message being incomprehensible, **-J** is not requested in subplot's manual and several examples work with out it in the ``subplot begin`` command.

**Comment by PaulWessel** [comment]
Cannot give 0 dimension without -J.  We can add a better test and message

**Comment by PaulWessel** [comment]
I think the auto -J may happen too late here, will check

**Comment by joa-quim** [comment]
But neither ex03 or ex06 need -J. It's because they are Cartesian?

**Comment by PaulWessel** [comment]
They both specify panel width and height.

**Comment by PaulWessel** [comment]
Sorry, I see you are looking at ex01 but it has **-JH**16c on the subplot begin line.  I assume what you mean is in that case the default geo-projection **-JQ**15c should kick in.  I will see if that is possible.

**Comment by PaulWessel** [comment]
I think the problem is that users may place **-J** options in the panel calls and therefore we cannot know if we should add some automatic geo-projection earlier.  For Cartesian we usually set **-Fs** (or **-Ff**) and do not need to add **-J** later since it auto-defaults to Cartesian scaling in the panel.  Perhaps it is possible to say that if you give a zero panel height in **-Fs** and no **-J** then we shall supply a **-JQ** option with the same width as you gave in **-Fs**.  This would make it an error to give a **-J** in the panels once you have said "auto-height" via **-Fs**_width_/0.  Makes sense?

**Comment by seisman** [comment]
I prefer to report an error for @joa-quim's case, i.e., both **-J** and **-R** are required if auto-height is set.
