### ISSUE TITLE
histogram doesn't give correct region if list of bins is given

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4368]
Example input data: [test.txt](https://github.com/GenericMappingTools/gmt/files/5433548/test.txt)

Using `-T-3/7/1`, the automatic x range is from -3 to 7, determined by the **-T** option. It looks reasonable.
```
gmt histogram test.txt -T-3/7/1 -Gblue -Bxa1f -Byaf -png map
```

![image](https://user-images.githubusercontent.com/3974108/97091084-15b99c80-1607-11eb-9c7a-281e9ebb51a7.png)

Instead of using `-T-3/7/1`, the following command gives a comma-separated list of coordinates. In this case, the automatic x range is from -1 to 6. It seems the x range is determined from the input data, not the **-T** option.
```
gmt histogram test.txt -T-3,-2,-2,-1,-1,1,1,2,2,3,3,4,4,5,5,6,6,7 -Gblue -Bxa1f -Byaf -png map
```
![image](https://user-images.githubusercontent.com/3974108/97091119-629d7300-1607-11eb-83b9-6d1a19461cbd.png)

**Comment by PaulWessel** [comment]
WIll have a look.  I think I agree pre-exploration that either -T option should set up the same bins and that should not be "shrunk" by lack of data in some bins.  But clearly -T begets -R here so will need to see what is actually happening.

**Comment by PaulWessel** [comment]
Note I think **-T** for bin boundaries should be -T-3,-2,-1,1,2,3,4,5,6,7 not -T-3,-2,-2,-1,-1,1,1,2,2,3,3,4,4,5,5,6,6,7.  In fact, the latter should give some sort of error for repeated knots.  Makes no difference to the plot though.

**Comment by PaulWessel** [comment]
I believe -Tlist need to check for a few things: monotonically increasing values.  We use this to get list of contours as well and I cannot think of any practical reason why one would say -C10,-10,40  instead of -C-10,10,40.  But perhaps we could just sort the array before returning it and not worry about that.  However, -C10,10,20 should either given an error or a warning (and skipping) the repeated value.

**Comment by seisman** [comment]
> Note I think **-T** for bin boundaries should be -T-3,-2,-1,1,2,3,4,5,6,7 not -T-3,-2,-2,-1,-1,1,1,2,2,3,3,4,4,5,5,6,6,7.

You're right. I think I misunderstood how the 1D array works. `-T-3,-2,-1,1,2,3,4,5,6,7` is correct, but `-T-3,-2,-1,0,1,2,3,4,5,6,7` gives me a wrong plot:

![image](https://user-images.githubusercontent.com/3974108/97092322-2bcc5a80-1611-11eb-8c02-d70b7728802b.png)

**Comment by seisman** [comment]
`-T1,2,3,4,5` also doesn't work.

**Comment by PaulWessel** [comment]
OK, almost done with the corrections.  This involved adding one more optional flag to _gmt_parse_vector_: **GMT_ARRAY_UNIQUE**.  If this bit-value is passed then any array produced (via list or file) will be sorted and duplicates removed.  Most places where **-T**_list_ is used it either makes no sense to have repeated (and unsorted) values, or it would cause a crash (**sample1d** calls _GMT_intpol_ which would crash if no increment).  Looking at where _gmt_parse_array_ is used I get this:

```
./filter1d.c
./geodesy/earthtide.c
./gmtmath.c
./gmtregress.c
./grdinterpolate.c
./makecpt.c
./potential/gmtflexure.c
./potential/grdflexure.c
./potential/talwani2d.c
./pshistogram.c
./sample1d.c
```

I think the only place we should _not_ pass GMT_ARRAY_UNIQUE is with gmtmath, since we even have that as an example of using Fibonacci numbers:

`gmt math -o0 -T0,1,1,2,3,5 T =`

Both contour programs also calls _gmt_list_to_array_ directly for a list of contours, which also should be unique. So I will add `| GMT_ARRAY_UNIQUE` to all the others.  Seems OK with you, @seisman?  Your other **-T** examples work for me, including the one where I missed you were skipping 0.

**Comment by seisman** [comment]
> So I will add | GMT_ARRAY_UNIQUE to all the others. 

Sounds good to me.

> Your other -T examples work for me, including the one where I missed you were skipping 0.

Do you mean that `gmt histogram test.txt -T-3,-2,-1,0,1,2,3,4,5,6,7 -Gblue -Bxa1f -Byaf -png map` works for you?

But, I see those debug messages:
```
histogram [DEBUG]: Found readable file test.txt
histogram [INFORMATION]: Reading Data Table from file test.txt
histogram [DEBUG]: GMT_Begin_IO: Input resource access is now enabled [record-by-record]
histogram [DEBUG]: Source col types: (Number)
histogram [DEBUG]: ASCII source scanned: Numerical columns: 1, Trailing text: N, Record type: Numerical only
histogram [DEBUG]: GMT_End_IO: Input resource access is now disabled
histogram [INFORMATION]: 1050 points read
histogram [INFORMATION]: The histogram has multiple (3) modes (peaks)
histogram [INFORMATION]: Extreme values of the data :	-1	5.9
histogram [INFORMATION]: Locations: L2, L1, LMS; Scales: L2, L1, LMS	2.30295238095	3.5	3.7	2.31273690671	1.03782	0.88956
histogram [INFORMATION]: min/max values are :	-1	5.9	0	0
histogram [INFORMATION]: Use w/e/s/n = -1/6/0/nan and x-tick/y-tick = 1/nan
histogram [DEBUG]: Projected values in meters: -1 6 0 nan
histogram [DEBUG]: Auto-frame interval for axis 0 item 0: d = 1  f = 0.2
histogram [INFORMATION]: Auto-frame interval for x-axis (item 0): f0.2
histogram [INFORMATION]: Map scale is 0.000466667 km per cm or 1:46.6667.
```
