### ISSUE TITLE
Categorical Scientific Colour Maps

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/gmt#4403]
**Description of the desired feature**

So I just read Fabio and others' Nature Comms paper at https://doi.org/10.1038/s41467-020-19160-7 and noticed that there are categorical versions of his colour maps (e.g. `batlowS`)! They seem to have been added in version 6, but the PR at #3649 didn't add them into GMT (only the cyclic ones like romaO were added).

[![Scientific Categorical Colour Maps](http://img.youtube.com/vi/XJcnxmGrxVY/0.jpg)](http://www.youtube.com/watch?v=XJcnxmGrxVY "Scientific Categorical Colour Maps")

The relevant page is at http://www.fabiocrameri.ch/categorical.php, and the full list of missing categorical colour maps are:

batlowS, devonS, davosS, osloS,lapazS,actonS,lajollaS,bilbaoS,grayCS,tokyoS,turkuS,ba-makoS, nuukS, hawaiiS, budaS, imolaS

Is it a matter of adding a few more entries to the script at https://github.com/GenericMappingTools/gmt/blob/49669eebc255945f8dc052d70fcb324bde4e7729/admin/build_scientific_colors_cpt.sh to pull these categorical CPTs in from https://doi.org/10.5281/zenodo.4153113, or would it be more work than that?

**Are you willing to help implement and maintain this feature?** Maybe

**Comment by PaulWessel** [comment]
OK, I thought we had a CI job that checked if their version increased (@seisman ?).  I guess we should update the list for 6.2 or master asap.

**Comment by seisman** [comment]
> I thought we had a CI job that checked if their version increased

Yes, but it checks http://www.fabiocrameri.ch/colourmaps.php, not http://www.fabiocrameri.ch/categorical.php. 

The colourmaps shows the latest version is 6.0.4, which is already included in GMT.

**Comment by weiji14** [comment]
> The colourmaps page shows the latest version is 6.0.4, which is already included in GMT.

Yes, GMT is currently using version 6.0.4 of the colourmaps, but the categorical ones in that version weren't added.

> Yes, but it checks http://www.fabiocrameri.ch/colourmaps.php, not http://www.fabiocrameri.ch/categorical.php.

Side note, maybe better to check the Zenodo DOI record at https://zenodo.org/record/4153113?

**Comment by seisman** [comment]
> Side note, maybe better to check the Zenodo DOI record at https://zenodo.org/record/4153113?

Not a bad idea, but it definitely needs more programming efforts and some knowledge about the zenodo API.

**Comment by PaulWessel** [comment]
Looking at his categorical CPTs, such as budaS.cpt and it starts:

```
0.000000 179 1 179 0.010101 255 255 102
0.010101 255 255 102 0.020202 205 133 126
0.020202 205 133 126 0.030303 188 78 144
...
```

Looks like color varies per sliace so what is the "category here? I guess we must pick each unique color in the order given and that is it.

**Comment by seisman** [comment]
> Looks like color varies per sliace so what is the "category here?

Bug of SCM?

**Comment by PaulWessel** [comment]
Maybe he does not know how we write categorical CPTs.  Anyway, there are 100 unique colors there so I just use then with z = 0, 1, .. like our others.
Running updated script now and seems fine.  No changes between new and old version of the ones we have except oleron which I have to manually edit since there is no z = 0 slice where the hinge is.  I made a note in the script.

**Comment by PaulWessel** [comment]
I will add more comments in the script, regarding these special cases:

1. _oleron_ is the _only_ one with a hard hinge (for sealevel topo use) and requires currently a manual fix - I will see if I can script that away.
2. There are four CPTs that end in "O" that are _cyclical_, meaning the start and end on the same color.  They have been adjusted a bit from their O-less versions which do not end on the same color.  So while `gmt makecpt -Ww` can create a cyclic CPT (it adds the **CYCLIC** header flag in the CPT so modules know what to do), we currently do not have them listed.  We should add these four since they are different, and possibly add the **CYCLIC** flag.
3. With the influx of categorical CPTs we should restructure Appending M scripts to keep all of them on a single group page.
4. Likewise, we may wish to place the cyclic (wrapped) CPTs there as well.  gmt makecpt can turn any CPT into a cyclic CPT and it does not care if there is a discontinuity.  In fact, that is a feature.  We should look at the discussion of CPTs in the cookbook and see if we cover cyclic/wrapped CPTs well.
5. If the number of CPTs we ship keep increasing then we may wish to think about a different way to display them in **gmt makecpt** as well as the docs, perhaps by category, etc.

**Comment by PaulWessel** [comment]
Correction, we _do_ ship the four cyclic "O" cpts but we do not list them in App M.  So mostly an issue of presentation in App M and maybe adding the CYCLIC keyword.

**Comment by PaulWessel** [comment]
OK, all conversions now work well and the script now deals with the _oleron_ special case so nothing to remember.
As for App M layout, we currently have three scripts 1a [half our cpts], 1b [other half], 1c [SCM all].  How about this for new arrangement:

- 1a: First half of our traditional cpts, minus any categoricals
- 1b: The other half
- 1c: SCM regular (not O or S)
- 1d: All categorical CPTs (our two plus SCM S)
- 1e: Cyclical CPTS (O from SCM)

That should make things a bit cleaner and better separated for starters. Does that sound OK, @joa-quim and @seisman (before I start doing it).

**Comment by PaulWessel** [comment]
Also, since we are no longer making PDF documentation, can't we combine all our regular cpts into one longer figure?  Since these are also used in the tests, do we run into any trouble by having a very tall figure, @seisman ?  Way easier if I can just build the figures up as far as they need to go rather than worry about page sizes...

**Comment by seisman** [comment]
> Since these are also used in the tests, do we run into any trouble by having a very tall figure, @seisman ?

I think no trouble at all.

**Comment by PaulWessel** [comment]
OK, great, so revised layout is then

- 1a: Our traditional cpts, minus 2 categoricals [44]
- 1b: SCM regular cpts (not O or S) [24]
- 1c: All categorical CPTs (our two plus SCM S) [18]
- 1d: Cyclical CPTs (O from SCM) [4]
