### ISSUE TITLE
Have a distinct color set to use in plot (and themes)

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4500]
Like in Matlab and others, it would be useful to have a set of distinctive colors to be used in a multi-lines plot. Something like a
```
COLOR_SET=green,darkgreen,lightgreen,moregreen,etc
```
which could be referred as **-W1,color1**, **-W2,color2**, etc or even automatically via some clever trickery in modern mode.

**Comment by PaulWessel** [comment]
Could they come from the categorical CPTs? But yes, I can see a user want to control which colors rather than whatever the CPT has.  So perhaps

**COLOR_SET**=_categorical-cpt_|_list-of-colors_

with a GMT defaults of categorical(.cpt).  As for usage, this is presumably (like in matlab) used when you give many lines and just want them different.  So perhaps -Wpenwidth,auto, where the auto-keyword means substitude the ordered list from COLOR_SET as we cycle through the segments. I can see an issue with segment versus table (file) though.  Let's say your "red" line is broken into several segments due to data gaps, yet you still want all of those segments red.  We could do the above on a per table or per segment, or perhaps need to handle this with -wpenwidth,auto[-segment|table] with default to table?

**Comment by joa-quim** [comment]
*=categorical-cpt* would complicate things because user would have to have a categorical cpt to make it work. I think it's preferable to have it simple like (colors used by Matlab)

**COLOR_SET**=#0072BD,#D95319,#EDB120,#7E2F8E,#77AC30,#4DBEEE,#A2142F

the *auto* is good for modern but wont work for tables in classic, but it would for segments.

**Comment by PaulWessel** [comment]
User already has categorical.cpt because it is one of the GMT master cpt - hence it is suitable default.  But we can discuss what is a suitable default here.

Not sure I follow you on the classic/modern point - I see no reason to limit this to modern (except the auto legend stuff).

**Comment by joa-quim** [comment]
I don't want to limit to modern (on the contrary, classic is what I use most of times in the Julia post-modern) but on classic *auto* cannot work because it doesn't know what color was already used in a previous plot, and setting it in gmt.history does not seem a good idea.

**Comment by PaulWessel** [comment]
I see, so you want this to go across many gmt calls to plot? Why not do them all at once?  That is when the auto-color is handy.  If you do them separately then might as well do -W separately as well.

**Comment by joa-quim** [comment]
I use to have the ideas in the shower but this time I had it half-asleep on way to bed.
If we used an option to set the psfile instead of the redirecting ``>>`` we could store the ``gmt.history`` inside the psfile.

**Comment by joa-quim** [comment]
> I see, so you want this to go across many gmt calls to plot?

Yes.

> Why not do them all at once?

That might not always be possible (different tables?)

> If you do them separately then might as well do -W separately as well.

and that's when my *color1*, *color2*, ... comes in. User should not need to know the color set colors for that.

**Comment by PaulWessel** [comment]
There seems to be several events that would break/interrupt the auto coloring.  In classic mode, someone may run psxy with -X -Y to move elsewhere.  Do we start over?  I guess as long as -Wwidth,auto is given then we continue, but how do you start a 2nd plot with auto in classic?  How does it work in subplots? I can imagine a user may wish to have it loop over the colors across panels or to restart on a per-panel basis.  So we need to think this through a bit more.  I dont see how

`COLOR_SET=green,darkgreen,lightgreen,moregreen,etc`

vs

`COLOR_SET=categorical`

enters in this.  We would need to know the next index to use for a color across modules and whether it should be reset.

**Comment by PaulWessel** [comment]
BTW, we already store stuff like clip level in gmt.history so I do not see a problem with storing a color index value.

**Comment by joa-quim** [comment]
> but how do you start a 2nd plot with auto in classic?

But that's what I've been saying. In classic *auto* is only for multi-segments. Every new *plot* starts from color1. That is why saving the color index in history is not a good idea because new plots would start with apparently random colors. The story is different in *modern* where the index could safely be stored in history because that history is deleted at the end.  For subplots, each is a new figure and starts with color1.

Another question is if the auto colors would aplly only to lines or to symbol fills as well, specially if lines and symbols are used in the same fig.

Don't understand your ``-X -Y `` case. If no line plotting then no color shift.

**Comment by PaulWessel** [comment]
OK, converging I think:

**Classic:**

- psxy[z] can cycle through the colors via tables and segments but it is reset per module call.

**Modern:**

- For subplots, each auto-color cycle is reset per panel.  This makes most sense to me.
- The current color-index is stored in the relevant gmt.history.* file so we can continue across module calls

**Unresolved:**

- Distinction between segments and tables.  There surely are cases where we want all segments in a table to have the same color, while at other times it should change per segment.  That is why I proposed auto[-segment|table].
- In modern mode, how is the cycle reset if you run it across a few modules but then you want to start a new sequence? Not possible? I.e., only one cycle per modern figure?  The -X -Y detection was an attempt to notice you are moving away from the current plot window and take that as a sign to stop the cycle.

**Comment by joa-quim** [comment]
I have no solution for the cycle-with-tables-in-classic. That is why in classic I would restrain it to multi-segments only.

In modern a new sequence is only allowed in subplots, otherwise in same figure colors always wrap around. Except maybe if a **-W1p,green** is used, which if *auto* is active would not increase the color index.

I would love to have also a mechanism also for classic (I anticipate some suffering if I want to implement it in Julia), but I don't see how. Saving in history is no good because it will not know if next is another plot or an append. My idea to have some history stored at the begin of a PS file came from this. Only there we know if it's a starting PS or an appending one.

**Comment by PaulWessel** [comment]
I am looking at this from the command-line usage point where after all this will be implemented, and there people will have many tables (e.g., table_*.txt), each with many segments, and they want to call

`gmt psxy table_*.txt -W0.5p,auto -Baf -JX15c/10c -P > plot.ps`

There has to be a way to indicate color-per-table or color-per-segment.  We have several similar decision-points in GMT, such as **gmt info -Aa**|**f**|**s**, **gmt convert -Itsr** (hm, I need to add a backwards fix here to let it be **-Ifsr** instead), etc., so selecting between tables and segment is a recognized issue.  With psxy[z] overflowing with options there is no room for a "-A"-like option in these.  However, -W0.5p,auto could default to color-per-segment as you prefer, and -W0.5p,Auto could mean color-per-table (if you don't like the long-form auto[-segment] and auto-table; I think when we go long we will want to do that here as well, so might as well do it now).

Since any module knows if it is starting a new plot or doing an overlay in classic mode, it could reset that index in the history file.  I dont see a problem with this approach.

We can decide if a -W1p,green also should reset the color-cycle or simply skip and not increase index.  I do not see a strong default here anyway.

**Comment by joa-quim** [comment]
OK, I clearly prefer ``-W0.5p,auto-table`` then ``-W0.5p,Auto``.

Right, by looking at the -KO dance modules will know that and I agree it can be used to talk with the history. But still a missing **-K** at the end (user error) will leave the history file in an kind-of error state.

**Comment by PaulWessel** [comment]
Well, we certainly are not going to guess what user errors means - so that is of no concern.  if they are concerned about their -O -O then that is a reason to go modern.

**Comment by joa-quim** [comment]
And while at it, we need also a **COLOR_CPT**=*turbo* to make it easy for people select one of those ugly modern CPTs in *themes*

**Comment by PaulWessel** [comment]
Currently, the default CPT is turbo and it is not a user-changeable setting.  Perhaps it should be, via **COLOR_CPT**.

**Comment by joa-quim** [comment]
Yes, that's the idea.

**Comment by PaulWessel** [comment]
I've implemented this but still on weekly family zoom so not made a PR yet.

**Comment by PaulWessel** [comment]
Some undecided issues remain, @joa-quim:

For legends, we will need to call _gmt_add_legend_item_ for each new color line or polygon. Some rules:

- We plot max _n_colors_ items.  Plotting 300 lines with 4 colors will give 4 legend entries.
- Legend item _label_ can come from segment header labels (`> -Llabel`), or perhaps **-l**_label1_,_label2_,...,_label2_, or if label contains a C format for integers we will fill in the running number, e.g., **-l**"Line %3.3d"?

**Comment by meghanrjones** [comment]
This can be closed, yes?

**Comment by joa-quim** [comment]
Yes, I guess we can close it now.
