### ISSUE TITLE
Plot title with subtitle on a newline

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/gmt#4557]
**Description of the desired feature**

There should be a way to plot a title on two lines instead of just one. Carried on from discussion at https://forum.generic-mapping-tools.org/t/how-to-plot-title-with-a-subtitle-on-a-newline/1121

### Current state

Using newline `\n` doesn't work on GMT 6.1.1:

```bash
gmt basemap -R0/1/0/1 -JX1 -Baf+t"Title\nSubtitle" -png map
```

![image](https://user-images.githubusercontent.com/23487320/101553425-7830f580-3a19-11eb-8284-5b03192bc203.png)

### Desired state

The "subtitle" should be on a second line.

It might be nice to have slightly different font sizes for the main title and subtitle. But making the newline `\n` work will do for now :smile:

**Are you willing to help implement and maintain this feature?** No

**Comment by PaulWessel** [comment]
Think you can use @%font%...@%% to change the font to your liking.  I don't think we want a fixed system unless we assume there is at most one \n and it truly is a title/subtitle 1-2 system.  But I do think your suggestion makes it simpler to implement (again, assuming anything after the first \n is a subtitle set at a smaller size, say 0.8*FONT_TITLE or a new FONT_SUBTITLE defaulting to 0.8...

**Comment by PaulWessel** [comment]
Perhaps @joa-quim and @seisman have opinion on the font-setting issue for multiple lines? I am bored and eager to code this up before afternoon coffee.

**Comment by seisman** [comment]
Sometimes people just want to split a long title into two lines. The second line doesn't have to be a subtitle. I believe it will surprise people that the second line has different font size.

**Comment by joa-quim** [comment]
I agree with Dongdong, but easy to have both. Use a double ``\n`` (``\n\n``) to have a subtitle.

**Comment by PaulWessel** [comment]
Yes, I like that, or perhaps \r for continuation of title (same font) and \n for smaller subtitle.  None of those characters are actually used when we typeset the PS so we could just assign those two functions and be done with it (a second \n just means the subtitle continues on more than one line with no further font changes.

**Comment by joa-quim** [comment]
Can we make it ``r`` => ``\continue`` and ``\n`` => ``\subtitle``? (or ``#continue`` if ``\c`` causes troubles)
``\r`` & ``\n`` are very natural to our *C-ish* thinking but we want to go for *longoptions*

**Comment by PaulWessel** [comment]
We could do both - easy to check for unique things like \continue, \subtitle.  But we also want \r, \n.  OK, only leftover item to discuss is FONT_SUBTITLE versus a fixed 0.8 (or some factor) of FONT_TITLE.  Preferences?  I an already see a feature request coming to make smaller subtitles than whatever factor we pick, hence FONT_SUBTITLE is OK with me.

**Comment by joa-quim** [comment]
Yes for an optional FONT_SUBTITLE. The other feature request I would foresee is "Make my subtitles *Italic*".
But can we also have both here? *I.e* default to 0.8 * FONT_TILE but allow other FONTs.

**Comment by PaulWessel** [comment]
Hm, I think all we can do is default to 0.8 with same font and you can change, just like the other FONT_*.  Making a new scheme just for this font is not great.  And anyway, you can always use @%font% as well.

**Comment by weiji14** [comment]
Let's not over-engineer this yet :sweat_smile: The scaling idea is nice but I think having `FONT_SUBTITLE` as something like `18p,Helvetica,black` will do for now (a scaled down version of [`FONT_TITLE`](https://docs.generic-mapping-tools.org/latest/gmt.conf.html#font-parameters)). If someone wants to change the TITLE and SUBTITLE font, they can always `gmt set` both. And with italics, they could do `FONT_SUBTITLE=18p,Helvetica-Oblique,black` or similar.

**Comment by PaulWessel** [comment]
Testing this in branch sub-titles. Since it is hard to get actual \r and \n characters into the string I cheated (at least for now) and use ^ and ~ instead, respectively.  With that, these things work:

**Breaking up a long title:**

`gmt basemap -R0/10/0/10 -Baf -B+t"My extremely long title and awkward title^must go over two lines^or perhaps three even" -png three`

![three](https://user-images.githubusercontent.com/26473567/101594133-3e1e1000-3995-11eb-8e9c-367640fe792f.png)

**Title with subtitle(s):**

`gmt basemap -R0/10/0/10/0/10 -JZ3i -Baf -B+t"My extremely long title and awkward title:~Must go over two lines~or perhaps three even" -png sub`

![sub](https://user-images.githubusercontent.com/26473567/101594154-470ee180-3995-11eb-9967-38633409c889.png)

Some technical comments:

1.  I chose a line-spacing of 1.1 times the font size here
2. The new **FONT_SUBTITLE** is set to 20p while title is 24p.  Seems perhaps it should be 18?
3. Using \r and \n means users have to do either "\\\\r and \\\\n" or '\r and \n' due to quoting rules. Even then, inside GMT these are \ two-char sequences which makes splitting words harder than if we had 1-char symbols.  Same if we did `#break` and `#subtitle`. No need if ^ and ~ were acceptable.  I know I am being a bit lazy here - what you think?
4. To avoid complications I do not allow both ^ and ~ in the same title.

**Comment by joa-quim** [comment]
1. Looks perfect
2. Shouldn't the **SUBTITLE** be a percentage of **TITLE**? Figures for posters require larger font sizes.
3. I even prefer ``^`` and ``~`` to ``\n`` & ``\r`` which are very programmer specific lingo. But *longoptions* will require > 1 char keys.

**Comment by PaulWessel** [comment]
2. We already have the +fontsize option to scale all fonts proprtionally.  I do not want SUBTITLE to be any different from the other 4-5 font options we have.
We can worry about adding longer keys later - note these are not program options, just escape sequences.  If we can agree on what those should be (e.g., #break; #sub; ?) then I can do that coding, but for now the shorthands ^ and ~ seems OK to me too.

**Comment by PaulWessel** [comment]
OK, once I have wrapped out the outline for the NASA proposal I can implement stuff like `#break;` and `#sub; `if that is OK with you fine folks.

**Comment by meghanrjones** [comment]
What about ```#linefeed``` and ```#subtitle```? I'm also fine with ```#sub```, but people might expect different behavior for ```#break```.

**Comment by PaulWessel** [comment]
Those are clearer, and the implementation beyond 1-char codes will be the same.  I guess I probably will need to allow things like

`This is my main title:#subtitle;Starting a long subtitle here#linefeed;that continues on the next line`

I.e., people should be allowed to initiate a subtitle (once only) but after that `#linefeed; `should used to break lines (versus my initial implementation that basically have you use `#subtitle;` to break lines in the subtitle - which I think would be confusing).  So `#linefeed;` will be used for both multi-line titles and multi-line subtitles.

**Comment by meghanrjones** [comment]
Can you clarify whether this implementation works only for -B+t or for any string parsing (e.g., text)?

**Comment by PaulWessel** [comment]
The _PSL_plottext_ function cannot be expanded to do this since it does not know more than the given font size.  So this was specifically implemented to deal with plot titles only.  If we were to make this a general-purpose multi-line function then it will bring up other issues, such as the alignments (no longer necessarily centered) and what subtitle font means if this is required in the middle of a string passed to **pstext**.  And we already have **pstext -M** for paragraph setting which basically can be used for similar things.  So I am leaning towards making this a title feature only.

**Comment by meghanrjones** [comment]
Sounds good, I agree about the potential issues and that there are easier alternatives when dealing with pstext relative to title. Just wanted to check that ```#subtitle``` made sense for the scope of the feature, which is does.

**Comment by joa-quim** [comment]
Other options ``<Enter>`` and ``<Subtitle>`` (case insensitive). I think people are more used to the ``<>`` pair (xml, etc)

**Comment by GD-A** [comment]
I might be hated for saying that ... but why not working toward a convergence to LaTeX syntax (again) ?

> -B+\title{ One line \\ two lines \\ three lines}+\subtitle{ a subtitle }

?

**Comment by joa-quim** [comment]
Yes, you are in serious risk that the sky falls over your head. 😄

**Comment by PaulWessel** [comment]
Well, given the syntax for title is **-B+t**_title_ we cannot replace GMT modifiers (**+t**) with a different syntax (**+\title**) since the vast majority of GMT modifiers have nothing to do with Latex or text.  So it has to remain **-B+t**_string_, but what is inside the _string_ is (still) up for debate.  FYI, when GMT will offer longer keyword/value from the command line then **+t** will become **+title**=_title_.  Which begs the question, perhaps the subtitle part could be solved by adding **+s**_subtitle_ (and eventually **+subtitle**=_text_.  That would eliminate the need for an escape sequence for subtitles, just need one for breaking long lines.

Using backslashes in text given on the _commandline_ is not straightforward and may require careful quoting or escaping, hence that route is not great for that reason.  For most mortals not versed in Latex, I think `#linefeed; `and `#subtitle; `are pretty good but perhaps there are even better ones if we brainstorm more.  I think the are both a bit on the long side, which is why I suggested `#break; `and `#sub; `but the latter is not obvious.

**Comment by PaulWessel** [comment]
Hm, looks to me adding **+s**_subtitle_ to **-B** for the _frame_ would simplify this whole thing, just requiring multi-line support for both title and the optional subtitle.  Agree with that, @GenericMappingTools/core ?

**Comment by PaulWessel** [comment]
This would allow us to use the shorthand `^` for multiline breaks in title and subtitle, and perhaps` #break;` would be acceptable to you as the single long-form command needed?

**Comment by meghanrjones** [comment]
That works for me, unless there's a reason to have mutually exclusive modifiers for frame and axes parameters in -B. Currently it seems like there's no overlap, so +s would be the first with subtitle and upper/right axis label for frame and axes respectively.

**Comment by PaulWessel** [comment]
Yes, there will not be a parsing conflict because frame and axes are processed separately.  Furthermore, **+s** requires you to also set **+t** since you cannot have a subtitle without a title.

**Comment by joa-quim** [comment]
👍  **+s**ubtitle

**Comment by seisman** [comment]
> This would allow us to use the shorthand ^ for multiline breaks in title and subtitle

What if users want to have the character `^` in the title? How do they escape it?

**Comment by PaulWessel** [comment]
They use #break; instead

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa

**Comment by seisman** [comment]
I mean, if I give a title `This is a title (Y=a^X+b)`. Will GMT split it into two lines?
```
gmt basemap -R0/10/0/10 -JX10c/10c -BWSen+t'This is a title (Y=a^X+b)' -png map
```

**Comment by PaulWessel** [comment]
Well you would do y = a@+X@+ + b, no?

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa

**Comment by PaulWessel** [comment]
Or the octal code for hat

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa

**Comment by weiji14** [comment]
Would it be easier if we had a [character escape sequence](https://docs.generic-mapping-tools.org/6.1/cookbook/features.html#character-escape-sequences) for newline? E.g. `@^` or something else indicates a line break.

**Comment by PaulWessel** [comment]
Yes, I can do `@^` or `#break;`, and perhaps we don't actually need #break; unless anyone feels @^ can appear in useful text.  I have already implemented the hard part so now know what to do.  I will switch from ^ to @^ first and people can tell me if `#break;` is still needed.
