### ISSUE TITLE
Fix missing links in some man pages

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4615]
There are several man pages that writes things like in the entry for an input grid.  This is from grd2cpt:

*grid*
	Names of one or more grid files used to derive the color palette
	table. All grids need to have the same size and dimensions. (See
	**GRID FILE FORMATS** below).

However, there is nothing below.  What is meant I think is a link to _explain_grd_inout.rst__.  I think this used to be a section and the above was a reference to a section (that include file starts with the subtitle **Grid File Format**s).  The **GRID FILE FORMATS** string appears in these rst files:

```
./grd2cpt.rst
./grd2kml.rst
./grdcontour_common.rst_
./grdedit.rst
./grdfft.rst
./grdfilter.rst
./grdgradient.rst
./grdhisteq.rst
./grdimage_common.rst_
./grdinfo.rst
./grdlandmask.rst
./grdmask.rst
./grdmath.rst
./grdproject.rst
./grdvector_common.rst_
./supplements/potential/gravfft.rst
./supplements/potential/grdflexure.rst
./supplements/potential/grdseamount.rst
./supplements/potential/grdslice.rst
./supplements/potential/talwani3d.rst
```

while explain_grd_inout.rst_  only appears in ./gmt.rst.

**Comment by meghanrjones** [comment]
I am working on fixing this now. For most modules that default to reading standard input if no filename is given, the *table* or *grid* file is listed as a required argument (e.g., [gmtinfo](https://docs.generic-mapping-tools.org/dev/gmtinfo.html)). For [grdblend](https://docs.generic-mapping-tools.org/dev/grdblend.html), the *blendfile* | *grid1 grid2 ...* is listed as an optional rather than required argument. @PaulWessel, can you please clarify whether the blend file/list of grids for grdblend should be considered optional or required?

**Comment by PaulWessel** [comment]
I guess they should be treated in the same sense input files to psxy is required since a lack of file argument triggers reading from _stdio_.  In the case of **grdblend**, if no file given then it will try to read stdin for the blendfile information.  So input is certainly required in one way or another.
