### ISSUE TITLE
QR size and background

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#463]
Given the recently implemented QR code symbol (#452) I have questions about what is the correct size and background.  In the attached plot you can see three versions (background painted pink so you can see what the symbol looks like):

1. The bottom plot is what I implemented: I scaled and offset the EPS that @KristofKoch sent so that the black pixels fit exactly inside the 1x1 area for a 1 unit symbol size.  However, the original white area then bleeds outside.
2. The middle plot is the original EPS with no changes.  Here, the entire symbol, including the larger white background, matches the 1x1 size.
3. The top is like the bottom except that I removed the painting of the white background, so it acts as a transparent symbol.

![t](https://user-images.githubusercontent.com/26473567/53677852-d3d22a80-3c5a-11e9-9e9f-3d599e88b286.png)

There are no rules that says QRs must be black/white or even just have two colors.  I think we probably do not want it to have a hardwired white background.  If so, the top plot is probably what we want, or should it be like the middle plot without the white square (in which case a s unit size yields a "square" that is 85% only.  Comments?

**Comment by KristofKoch** [comment]
@PaulWessel, you are correct - there is no rule mandating the QR code being black/white. However there is a rule defining the threshold between the "dark" and "light" part of the symbol being the midway between the maximum and minimum reflectance of the entire symbol. Therefore I would recommend to stick to black and white for the symbol as this has the best contrast. 

The standard also mandates a "quiet zone" around the symbol four modules ("pixels") wide. This is where my QR code falls short by having a quiet zone only two modules wide. However, the scanners I tested seem to work fine with the narrower quiet zone. 

My expectation of how the QR code is sized would be the middle plot. I assume most users are not aware of the finer details of the required structure of a QR code. They might run into trouble by placing the top version over a noisy/low contrast background and end up with a non-working QR code. 

I chose the narrower quiet zone because I had similar thoughts as you, Paul: the symbol appears "too small" on a white background as the quiet zone blends into the plot. Maybe it is a solution to have a thin border around the quiet zone so the symbol size appears correct to the user? In this case the quiet zone could be widened to four modules as per standard. This allows for higher chances of a successful scan while, at the same time, avoiding user confusion about what appears to be a too small sized QR code on a white background.

Something like this mockup with a per-standard quiet zone maybe:

<img width="255" alt="gmt-qr mockup" src="https://user-images.githubusercontent.com/45796239/53692083-00389480-3d8a-11e9-920c-612a020b0653.png">

Your thoughts?

**Comment by KristofKoch** [comment]
Another thought – maybe just let the user know in the documentation how the QR code is sized (1x1 units with quiet zone) and give the multiplication factor to get the b/w pattern up to 1x1 units size. This way you could do away with the black border around the quiet zone I suggested above. Not very elegant but if you don't like the black border maybe a viable solution.

**Comment by PaulWessel** [comment]
We could considerer letting -G set the foreground color instead of black.

**Comment by KristofKoch** [comment]
@PaulWessel I think making `-G` available is a good idea. Then @joa-quim is able to make red QR codes if he fancies so. Joking apart, I think it is an easy way to let the user customize the QR code and offer the opportunity make it appear less harsh/massive. Also, nice use of the PS macro – should've thought of this myself.

**Comment by PaulWessel** [comment]
Because I cannot set both the foreground -G color of the QR symbol and deal with the white background I suggest we eliminate painting the white background.  That way the user will need to paint a white square of the same size if the background is not already white.  If that is too much work, we could create two QR symbols: QRo for opaque (white background) and QRt for transparent (no background painted) symbol.

**Comment by PaulWessel** [comment]
In order to close this issue, could I have @KristofKoch and @GenericMappingTools/core comment on this.  The choices are:

1. Have a single QR symbol that is transparent.  Up to users if they need to plot a white square beforehand.
2. Have two QR symbols called QR_opaque and QR_transparent.  The opaque would lay down the white square as part of the symbol while the transparent obviously does not.

**Comment by KristofKoch** [comment]
Hi @PaulWessel I favor the second choice with the two options. 

I guess most users are not aware how QR codes work. That’s why I would name the opaque one just *QR* and the transparent one *QR_transparent*.

**Comment by joa-quim** [comment]
I've no real opinion on this but if others can make red QR's, so should we.

**Comment by PaulWessel** [comment]
If you read the PR you would know that **-G** changes the color of the code and -W optionally draws a square outline.  I think @KristofKoch suggestion is good: QR and QR_transparent.

**Comment by joa-quim** [comment]
Yes, I revisited the **-G** bit and saw that bg color is guaranteed (BTW, prefer green).

**Comment by PaulWessel** [comment]
I will add the QR_transparent symbol and update the docs.

**Comment by PaulWessel** [comment]
Forgot to close this when the PR was accepted.  Both QR and QR_transparent has been implemented.
