### ISSUE TITLE
Feature suggests/Ideas. New type of issue for Github? 

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4833]
I think that maybe a new type of template issue (besides bugs and features request) could be add. It would include suggestions/ideas that someone could have for a future development but at the moment it is not needed (this would be the main differences with 'Feature request). Sometimes it happens to me and it could be good (for the developers) to clearly differentiate between ideas and needs.

**Comment by meghanrjones** [comment]
I created a feature development discussion in the discussions tab for now. It may be that the team decides to move these types of discussions to the forum in the future, depending on how it goes. My opinion is that the discussions tab and/or the forum is more appropriate than an issues template because issues are better when they are concrete and not indefinite.
