### ISSUE TITLE
Streamline steps for building and maintaining GMT

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/gmt#4840]
**Description of the desired feature**

The steps to build and run tests in GMT to produce new postscript (*.ps) files is not very intuitive for first timers. In particular, it's a little confusing having to jump between the [BUILDING.md](https://github.com/GenericMappingTools/gmt/blob/master/BUILDING.md) and [MAINTENANCE.md](https://github.com/GenericMappingTools/gmt/blob/master/MAINTENANCE.md) documents.

> Yes, I think from this it's clear from this PR that some revisions are needed to the building and maintaining (and possible contributing) documentation. When I started, I also found that I needed to bounce back and forth between building and maintaining documents a bunch. Perhaps some redundancy is needed for improved clarity. Would you want to open an issue for this?

_Originally posted by @meghanrjones in https://github.com/GenericMappingTools/gmt/issues/4838#issuecomment-783445471_

See also https://github.com/GenericMappingTools/gmt/pull/4838#issuecomment-782954781 and https://github.com/GenericMappingTools/gmt/pull/4838#issuecomment-782964119

Suggested changes:

- Consolidate BUILDING.md and MAINTENANCE.md together into one document, or maybe add some redundancy to both documents so that it will be clearer to first timers.
- Mention the convenience scripts at `admin/bashrc_for_gmt`(https://github.com/GenericMappingTools/gmt/blob/master/admin/bashrc_for_gmt) (added in #4529) in MAINTENANCE.md, and briefly mention how to use them

**Are you willing to help implement and maintain this feature?** Happy to review the Pull Request!

**Comment by meghanrjones** [comment]
The downside of keeping BUILDING.md and MAINTENANCE.md separate is that there will need to be more redundancy to make setup easier for new developers. But, I think it is necessary to keep them separate because the [GMT website](https://www.generic-mapping-tools.org/download/) links to BUILDING.md for instructions on how to build from source and there are likely many people who want to build from source without needing debugging flags, testing instructions, etc.

**Comment by PaulWessel** [comment]
Might it be an option to add a DEVELOPER.md that links to the two others but helps in describing the overall workflow?

**Comment by meghanrjones** [comment]
> Might it be an option to add a DEVELOPER.md that links to the two others but helps in describing the overall workflow?

Rather than adding a new document, we could add a 'setting up your environment' section (similar to PyGMT's section in their [contributing guide](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md#setting-up-your-environment)) and a more complete description of the overall workflow to [CONTRIBUTING.md](https://github.com/GenericMappingTools/gmt/blob/master/CONTRIBUTING.md).

**Comment by meghanrjones** [comment]
Related issue: #364
