### ISSUE TITLE
Module project produce wrong solution

### ISSUE THREAD

**Issue by zhaozhiyuan1989** [GenericMappingTools/gmt#486]
Just as follows:
```
$ echo 1 1 1 1  >tmp 
$ gmt project tmp -C126/42 -E146/40  
1	1	1	1	-116.677355546	22.5941516024	15.0121666457
$ echo 1 1 1 1 1 1 1  >tmp 
$ gmt project tmp -C126/42 -E146/40  
1	1	1	1	1	1	1
```
**System information**

* Operating system: Windows 10, Centos7
* Version of GMT: GMT6.0.0 GMT5.X

**Comment by PaulWessel** [comment]
Interesting, I get the correct result for your second case:
`1	1	1 1 1 1 1	-116.677355546	22.5941516024	15.0121666457	-16.8767137176
`
Sure you are using 6 from GitHub?  Or perhaps this is specific to Windows? [I'm on OSX]

**Comment by joa-quim** [comment]
Nope, it's an OSX specific (not detecting the problem). On Win debug build it crashes when freeing mem in ``write_one_segment()``.

In fact, for this case, memory is corrupted because on line (project.c) 598
``out = gmt_M_memory (GMT, NULL, n_items, double);``
``n_items = 7`` but in at the end of the next for loop ``out[k++]`` was accessed at position 11

**Comment by PaulWessel** [comment]
Sorry, I can recreate the problem. I had switched to 5.4 branch when I ran the above.  I get the same crash as you.

**Comment by joa-quim** [comment]
Good, after all there still some hope for that permissive compiler.
