### ISSUE TITLE
subplot wrong tag position

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4972]
**Full script that generated the error**

```
gmt begin subplot1
  gmt subplot begin 1x2 -Ff15c/3c -BWSen
    gmt subplot set 0 -A'(b)'
    gmt basemap -R0/10/0/10 -JX?/?
    gmt subplot set 1 -A'(c)'
    gmt basemap -R0/10/0/10 -JX?/?
  gmt subplot end
gmt end show
```
![image](https://user-images.githubusercontent.com/3974108/111355345-a8fa7980-865d-11eb-90a3-f9a2e656b3b1.png)

If I add **-A** to `subplot begin`, i.e., `gmt subplot begin 1x2 -Ff15c/3c -A -BWSen`. It works as expected:

![image](https://user-images.githubusercontent.com/3974108/111355474-c6c7de80-865d-11eb-84bc-5d7d4968ea40.png)

**System information**

* Operating system: macOS 
* GMT version (`gmt --version`): 6.2.0_f8cf99b_2021.03.15

**Comment by PaulWessel** [comment]
Maybe it is not clear from the docs but if you want to use the tag machinery you should indicate taht on the gmt subplot begin line. Since we do not check later if this was done the parameters taht subplot begin -A would set are empty, hence the default justification is BL I guess, with no offset.  I think the solution to this is to clarify the -A documentation for gmt subplot set and to check if -A was set if given later.

**Comment by seisman** [comment]
> clarify the -A documentation for gmt subplot set and to check if -A was set if given later.

Sounds OK to me.
