### ISSUE TITLE
histogram -N odd behaviour

### ISSUE THREAD

**Issue by gd-a** [GenericMappingTools/gmt#4992]
[For reference](https://forum.generic-mapping-tools.org/t/histogram-with-new-w-cyclic-option/1470/11?u=planetgus)

The equivalent normal distribution is not plotted correctly : 

```
gmt begin test01 png
gmt histogram  -JX10c test.txt  -T1 -BWSen -Bxa1Of1O+l"Months" -Byaf+l"Frequency"+u"%" -D+r -Z1 -N0 -wa -Glightblue -Wthinnest,black --FORMAT_TIME_PRIMARY_MAP=c
gmt end
```

![](https://forum.generic-mapping-tools.org/uploads/default/original/2X/2/267b68628cc9df923bb844021d99ef4add3fb90b.png)

[test.txt|attachment](https://forum.generic-mapping-tools.org/uploads/short-url/yoKybUabavuVCJQZZCyobon9EV.txt)

**Comment by meghanrjones** [comment]
I think @PaulWessel will disagree with me here, but in looking at the code and documentation I am not convinced that this behavior should be unexpected. GMT is taking the mean (6.14 for these data) and standard deviation (4.47 for these data) of f(x) for 0<x<12 and plotting the equivalent normal distribution.

**Comment by gd-a** [comment]
Maybe, but wouldn't it be more relevant to have the curve matching the data ?
Also If I shift the bar plot to be centred on winter (new cyclic feature), the curve changes...

**Comment by meghanrjones** [comment]
I view it as the `R=-5/7/0/12` is basically applying a phase shift to the data (range of 0-12 before and -5-7 after), which is making the mean change depending on whether the plot is centered on summer or winter. I'm not sure if that interpretation is correct - the option to use negative numbers in region with -w is not fully documented but rather used in one of the **-w** examples.

**Comment by PaulWessel** [comment]
Will look once back from vaccinations

**Comment by PaulWessel** [comment]
Thanks @meghanrjones, I agree that the issue has to do with the **-R** setting and the wrapping.  The first (wrong) plot does compute a mean half-way between the peaks etc.  It just does not know that this data is periodic and one cannot take the mean  like that when **-w** is on.  I am not sure what is the best, but an analogy with a circle would suggest I need to fit a _von Mises_ distribution to this rather than the normal distribution.  I.e., basically it is statistics of data on a circle.  I know how to do those things, so will see how to implement it.
