### ISSUE TITLE
Latex writing

### ISSUE THREAD

**Issue by gd-a** [GenericMappingTools/gmt#5032]
Hi,

I'm assigning a label expression to my y-axis (in subplot) and this works : 
```
"@[ \int_x \int_y \chi_x @["
```
But this doesn't : 
```
"@[ \int_{x} \int_{y} \chi_{x} @["
```

Not a major issue, here, 

but ` \int_{a}^{b}` is very different than `\int_a^b`

**Comment by seisman** [comment]
Using `{}` or not gives me the same results. I'm using bash on macOS.

Are you using Windows? Could you provide your script and the output?

**Comment by gd-a** [comment]
I'm actually using bash on macOs too ...

The command (working) : 
```
    gmt subplot begin 1x2 -Fs10c -M0.5c -A\(a\)+JTL+o-1c/.25c -BeSWn -JX10c -R-30/30/0/80 -Bxafg+l"@[\int_x \int_t \tau_x @[" -Byafg
```

(not working)
```
    gmt subplot begin 1x2 -Fs10c -M0.5c -A\(a\)+JTL+o-1c/.25c -BeSWn -JX10c -R-30/30/0/80 -Bxafg+l"@[\int_{x} \int_{t} \tau_x @[" -Byafg
```

**Comment by PaulWessel** [comment]
Working on this now.  Updates:

1. The backslashes survive into the subplot info file for either single or double quotes.  So that is good.
2. When **-Bx** and **-By** are given as above, we actually store the leading x and y in that file and then we append it to **-Bx** and **-By**.  So I see we end up with arguments to **basemap** like `-B"xxafg+l@[\int_{x} \int_{t} \tau_xyafg"` which surely is not good and I need to see if that duplication of **x** at the start messes things up so that the unnecessary **afg** is added at the end. However, the Latex part seems OK apart from the missing `@[` at the end...
