### ISSUE TITLE
curl wrongly linked to anaconda3

### ISSUE THREAD

**Issue by JouSF-1409** [GenericMappingTools/gmt#5055]
I used to run gmt6 in windows10 but now have to install one on manjaro recently.
the very first problem that I want to noticed here is the line in wiki:
```bash
sudo pacman -U *.pkg.tar.xz
````
for there ain't any pkgs names *.pkg.tar.xz but *.pkg.tar.zst or *.tar.xz
![DeepinScreenshot_select-area_20210401034938](https://user-images.githubusercontent.com/81711503/113202430-4f20c300-929d-11eb-8b9d-2288363ce1a1.png)

and the very core problem I meet afterwards is 
I have to use sudo to call gmt out like this
![DeepinScreenshot_select-area_20210401033836](https://user-images.githubusercontent.com/81711503/113201756-788d1f00-929c-11eb-9185-073b9ab387d0.png)

you may notice the 4 link in between address that curl is wrongly linked to /anaconda3/lib/libcurl.so.4 which is not available. Some are suggesting  conda remove curl, but I still want to know why and how.

**Comment by seisman** [comment]
> the very first problem that I want to noticed here is the line in wiki:
> 
> ```shell
> sudo pacman -U *.pkg.tar.xz
> ```
> 
> for there ain't any pkgs names *.pkg.tar.xz but *.pkg.tar.zst or *.tar.xz

@holishing Could you please verify it as you wrote the initial ArchLinux install instructions in #2153 (now in the wiki https://github.com/GenericMappingTools/gmt/wiki/Install-latest-GMT-on-ArchLinux).



> ![image](https://user-images.githubusercontent.com/3974108/113203782-75614700-923a-11eb-8dbf-e60478102b55.png)

A known problem of oh-my-zsh (see https://github.com/ohmyzsh/ohmyzsh/issues/9154). You have a few options:

1. Disable the `git` plugin of oh-my-zsh
2. Manually remove the `gmt` alias in the `git` plugin
3. Comment in https://github.com/ohmyzsh/ohmyzsh/issues/9154 and ask them to make the changes
4. Reset the alias at the end of your `.zshrc` file (may work or not)

> you may notice the 4 link in between address that curl is wrongly linked to /anaconda3/lib/libcurl.so.4 which is not available.

It happens when you have multiple curl libraries in your system. The CMake build system simply picks the first one it can find. So you have to tell GMT (or CMake) which one to link. Adding `-DCURL_ROOT=/path/to/your/curl/library` in the `PKGBUILD` file may work.

**Comment by JouSF-1409** [comment]
Thank you so much for your generous repo.
Last time I tried to fix it, I messed up with function locale and enable to balance back.
Now the curl problem is gone.

**Comment by holishing** [comment]
@JouSF-1409 
Archlinux change its default package compression method from LZMA2 ( `xz` ) to Z-standard ( `zst` )
https://archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/
I've updated related wiki page, thx for report
