### ISSUE TITLE
Default NoData value using gdal drivers

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#518]
Using e.g. ``grdconvert`` with a ``gdal`` driver (and not specifying ``=gd/N/N/N:<driver>``) the default NoData value is ``nan``. I've experienced software complaining and refuse to import the grid due to this. I guess it expects an integer to represent ``nan`` values. Is the choice of ``nan`` deliberate? Creating/converting rasters with ``gdal_translate`` apparently gives a default NoData value of ``-32768``. Why isnt this chosen as a default when calling using ``gdal`` drivers from ``gmt``?

```

#Bring a grid to the folder
$ gmt which -G earth_relief_30m.grd
~/.gmt/server/earth_relief_30m.grd

#Convert to ZMAP with gdal
$ gdal_translate -of zmap earth_relief_30m.grd earth_relief_30m_gdal.zmap
Input file size is 721, 361
0...10...20...30...40...50...60...70...80...90...100 - done.

#Convert to ZMAP with gmt
$ grdconvert earth_relief_30m.grd earth_relief_30m_gmt.zmap=gd:ZMAP

$ diff earth_relief_30m_gmt.zmap earth_relief_30m_gdal.zmap
5c5
<         20,       nan,          ,         7,         1
---
>         20,    -32768,          ,         7,         1

```

**Comment by joa-quim** [comment]
The use of ``NaN``s for NoData is surely a deliberate choice (if readers of float grid formats can't understand ``NaN``, that's their problem). Now, you are right that when one convert to integer types using ``NaN`` makes no sense. But the problem is that we need to know in advance if the data type of destiny format. I think we do pay attention to this when converting to tiff float but not sure.

**Comment by abanbj** [comment]
Great. Thanks for clearing that up joa-quim. I've been bashed before for making devs aware of stuff that should be avoided pr. (original) specifications for certain formats.

**Comment by joa-quim** [comment]
Just tried the zmap format and noticed that it's not an integer format (converted a grid with floats and got floats in the .zmap). So why would a ``-32768`` be a good ``NoData`` value? Still remember the time where a variable number ``9's`` as in ``99999`` were used for this.

Maybe the problem is due to fact that the zmap it's an ascii format? Or does it have its own NoData value like, for example, the Surfer format?

**Comment by abanbj** [comment]
Have no idea. Just thought ``gdal``'s NoData default value would be used also when called from ``gmt``.
