### ISSUE TITLE
Using `-i` to specify columns fail when more than 2 columns are read

### ISSUE THREAD

**Issue by hzfmer** [GenericMappingTools/gmt#5194]
**Description of the problem**
Plotting points from a file with locations and symbols can fail because the latter columns are not read.

**Full script that generated the error**
```bash
echo "5 5 0.1c t" > temp.txt
gmt plot -R0/10/0/10 -BWSne -Baf -JX4c temp.txt  -S -i0,1,2,3 -W1p,black -png test
```
This generates an empty frame, not to mention using other arbitrary order of columns selected from a number of columns.

However, reading all columns by default does work:
```bash
gmt plot -R0/10/0/10 -BWSne -Baf -JX4c temp.txt  -S  -W1p,black -png test
```

, which plots a triangle at the center.

**Expected outcome**

**System information**

* Operating system: Linux
* GMT version (`gmt --version`):
6.1.1

**Comment by PaulWessel** [comment]
Actually, this is a user error.  The trailing text column is called t.  If you want to address it you use t, e.g.

gmt plot -R0/10/0/10 -BWSne -Baf -JX4c temp.txt  -S -i0:2,t -W1p,black -png test

See the [documentation](https://docs.generic-mapping-tools.org/latest/gmt.html#icols-full) for the **-i** option for details.

**Comment by hzfmer** [comment]
> Actually, this is a user error. The trailing text column is called t. If you want to address it you use t, e.g.
> 
> gmt plot -R0/10/0/10 -BWSne -Baf -JX4c temp.txt -S -i0:2,t -W1p,black -png test
> 
> See the [documentation](https://docs.generic-mapping-tools.org/latest/gmt.html#icols-full) for the **-i** option for details.

Thanks! @PaulWessel 
I will change the label later. Thank you for your answer!


I  am still a bit confused about how the column number is counted.
It seems we cannot skip one column? Say we have one more column in the middle:
```
echo "5 5 100 0.1c t" > temp.txt
echo "5 7 100 0.1c c" > temp.txt

# This doesn't work 
gmt plot -R0/10/0/10 -BWSne -Baf -JX4c temp.txt -S -i0,1,3,t -W1p,black -png test;
```

Another case is:
```bash
echo "5 7 0.1c c 100" > temp.txt

# We don't need the exact trailing column; and this doesn't work
gmt plot -R0/10/0/10 -BWSne -Baf -JX4c temp.txt -S -i0,1,2,3 -W1p,black -png test;

# But the one below works
gmt plot -R0/10/0/10 -BWSne -Baf -JX4c temp.txt -S -i0,1,2,t0 -W1p,black -png test;
```

**Comment by PaulWessel** [comment]
I guess this particular combination (-S expecting both parameters and symbol code to be read from file, plus -i specifying specific columns, including trailing text) was never coded up.  So the failure is a "feature".  Before -i was introduced, a -S would mean we have no idea how many columns to read since the symbol could be a circle or an ellipse, requiring 1 or 3 columns.  However, in your case we do know you expect to only pass 3 coordinates plus symbol code, and then we would actually have to introduce checks that would complain if we read a symbol code that requires more than one data column. This dependency of -S on -i was never considered.  Finally, all these cases requires ascii files since symbol code is a text, so the reading is very specific for -S.  We can call it a bug but basically it is something not implemented.  I suggest I update the documentation for this case since I do not think we want to add the -S -i extra checks on number of columns.

**Comment by hzfmer** [comment]
@PaulWessel 

I see. Thanks for your explanation!
