### ISSUE TITLE
Broken PS file when setting dashed frame

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5237]
Found this bug when trying to answer this [forum post](https://forum.generic-mapping-tools.org/t/how-to-change-the-width-and-color-of-the-box-frame-in-psxy-plot/1693/7).

To reproduce the issue:
```
gmt begin test png
gmt basemap -R1960/2000/0/30 -JX5/8 -Bxa10f5 -Bya5f1 --MAP_FRAME_PEN=red,-
gmt end show
```
The command crashes for me with the following errors:
```
Error: /rangecheck in --setdash--
Operand stack:
   --nostringval--   0
Execution stack:
   %interp_exit   .runexec2   --nostringval--   setdash   --nostringval--   2   %stopped_push   --nostringval--   setdash   setdash   false   1   %stopped_push   1974   1   3   %oparray_pop   1973   1   3   %oparray_pop   1961   1   3   %oparray_pop   1817   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   setdash   --nostringval--   2   %stopped_push   --nostringval--   1818   2   4   %oparray_pop
Dictionary stack:
   --dict:736/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--   --dict:157/250(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 21471
psconvert [ERROR]: System call [gs -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/Users/seisman/.gmt/sessions/gmt_session.66120/gmt_0.ps-' 2> '/Users/seisman/.gmt/sessions/gmt_session.66120/psconvert_68850c.bb'] returned error 256.
end [ERROR]: Failed to call psconvert
end [ERROR]: gmtinit_process_figures returned error 79
```

However, if I change `MAP_FRAME_PEN` to `1p,red,-`, it works.

**Comment by PaulWessel** [comment]
How should we fix this type of issue? We call gmt_getpen to set the parameters but here no width is given.  There are pens for which there is a default thickness, like here, but other places where a pen is a pen, with no default.  And in modern mode with themes many pens are set to NaN so that they can get scaled correctly.

The simplest solution might be to remember if the given pen has nonzero attributes and then use those if new ones are not provided.  That should yield a NaN in the above case (then scaled according to size) while for -W in plot it may give the default pen width.  OK?
