### ISSUE TITLE
Is grdfill -N option available?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5246]
The [grdfill documentation](https://docs.generic-mapping-tools.org/dev/grdfill.html#optional-arguments) lists the **-N***nodata* option, but I don't see it in the synopsis or in the source code.

Please verify if **grdfill** has the **-N** option or not.

**Comment by PaulWessel** [comment]
Good catch.  I think the initial idea was that perhaps the user had flagged holes as values in the grid that were, say, -999 instead of NaN so -N-999 would then be used and the code would deal with that.  I still think that is a good idea.  The simplest way to implement it would be to have a quick loop up front to replace those -999 with NaN since the rest of the module expects NaNs.

The man pages also wrongly says that -As is experimental but it is fully implemented and we have test cases that shows it.

I guess none of this rises to the level of a fix needed brfore 6.2.0 so I will make two separate WIP PRs.
