### ISSUE TITLE
saple1d -T crash in Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5266]
This crashes in ``GMT_Create_Options`` because, I don't know why, the vector in **T** below, which is = 1:332, is converted to text and the **p** variable is declared as "1024", which is not big enough. However, increasing its size only transfer the crash further down when trying to access to a non-initializes *opt*. The main question, I think, is why the -T vector argument is converted to text?
```
t = gmtread("t.dat")
sample1d(gmtread("stack.dat"), T=t[1].data)
```
But this works
```
sample1d(gmtread("stack.dat"), T="1/332/1")
```

[t.zip](https://github.com/GenericMappingTools/gmt/files/6550279/t.zip)

**Comment by PaulWessel** [comment]
What is being fed to in the end? gmt sample1d ? -T?
I think there needs to be a -T? when there is a virtual file being given - do you/we handle that?

**Comment by PaulWessel** [comment]
Let's pretend that GMT_Encode_Options did the right think, setting up an option -T? so that a memoryfile can get placed there.  Then sample1d in the parser calls gmt_parse_array with the argument.  There are no check in that function for memory files.  Closest thing is

	/* 1b. Check if argument is a local file */
	if (!gmt_access (GMT, argument, F_OK)) {	/* File exists */
		T->file = strdup (argument);
		return (GMT_NOERROR);
	}

Since that fails it assumes it is not a file and starts doing min/max/inc stuff.  So clearly that would fail.  I will add that check and make a PR.

**Comment by PaulWessel** [comment]
That was it.  This works for me:

```
D = gmt ('read', '-Td stack.dat');
T = gmt ('read', '-Td t.dat')
q = gmt ('sample1d', '-T', D, T)
```

Please check GMT.jl and then we can approve and merge.

**Comment by joa-quim** [comment]
Still crash in Julia but, sorry, it's my fault. I happen to convert all args to **-T** to strings and this one is too long. Must add an option to ingest datasets as well.
```
julia> sample1d(gmtread("stack.dat"), T=t[1].data, Vd=2)
"sample1d  -T1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0, ...
```

**Comment by joa-quim** [comment]
But there is a side issue to this. If you look at ``stack.dat`` you'll see that it has NaNs and my hope was that they would be replaced by interpolated values. But they aren't (see your Matlab solution). Right, if I delete the rows that have 2nd column = NaN then interpolation does it's job but I was expecting not to need that step.

**Comment by PaulWessel** [comment]
Might this be controlled with --IO_NAN_RECORDS=skip? Basically, GMT isn't ignoring NaNs and often they are used to indicate segment changes.  I agree that sampling through to fill in where there are NaNs is a common thing so if this turns out to be too cumbersome (setting GMT defaults or other gymnastics) then perhaps sample1d need an option for it.

**Comment by PaulWessel** [comment]
Note that

`gmt sample1d stack.dat -Tt.dat --IO_NAN_RECORDS=skip > a.txt`

worked just fine for me with no fuss. Perhaps we just need to document this better with an example in sample1d.

**Comment by joa-quim** [comment]
Yes, that seems good enough.
