### ISSUE TITLE
gmtselect issue (gmt6)

### ISSUE THREAD

**Issue by mvanneste** [GenericMappingTools/gmt#5368]
All,
I have the following observation with gmtselect, using either an area (-R) or polygon (-F) on a file which has x y and a third column which can be mixed as a text string or number. The outcome is that sometimes the text strings are printed as NaN, and this seems to depend on the value in the first line.

The example underneath illustrates this issue. The only difference between the two tests is that I exchanged the first 2 lines, so the results should be identical. The result of test 1 gives me NaN instead of A and C, the result of test 2 is correct.

echo “Test 1”
echo “.5 .5 1” > temp
echo “.25 .25 A” >> temp
echo “1.7 .7 B” >> temp
echo “.7 .7 C” >> temp
gmtselect -R0/1/0/1 temp
Result:
0.5 0.5 1
0.25 0.25 NaN
0.7 0.7 NaN

echo “Test 2”
echo “.25 .25 A” > temp
echo “.5 .5 1” >> temp
echo “1.7 .7 B” >> temp
echo “.7 .7 C” >> temp
gmtselect -R0/1/0/1 temp
Result:
0.25 0.25 A
0.5 0.5 1
0.7 0.7 C

The bug here may be that the t in -i0-1,2t is being ignored.

* Operating system: linux
* GMT version: 6.0 and 6.2

(note: I am wondering if a similar behaviour may appear with grdtrack where one column of the input file may also have a mix)

**Comment by PaulWessel** [comment]
It should be gmt select temp -i0,1,t but anyway it does not work.  I think we need something like that to work as it is not possible for some gmt modules like select, which is reading record by record, to detect that a later record than the first has in fact trailing text rather than the number field found at first.  With -i0,1,t we would like it to use that knowledge rather than auto-figuring things out like now.

**Comment by joa-quim** [comment]
That's what I said in the [forum post](https://forum.generic-mapping-tools.org/t/gmtselect-issue-gmt6-6-2/1808/8), though I thought the syntax should be **-i0,1,2t**

**Comment by PaulWessel** [comment]
Actually, the way **-i** works it would not be a good place to tell a module that column 3 is text.  This is a job for **-f**2**s** I think (s for string since t is already taken for time), which we currently don't have. If **-f**2**s** were implemented it would mean x and y are whatever they are for this module, but after the 2nd column everything should be considered trailing text.

**Comment by joa-quim** [comment]
OK, but then what's the purpose of **-i**_col_**t**?

**Comment by PaulWessel** [comment]
See https://docs.generic-mapping-tools.org/dev/gmt.html#icols-full for that.  There is no 2t but there is a "column" called t.

**Comment by PaulWessel** [comment]
OK, while we are taking I have implemented _-f__col_**s**:

```
gmt select -R0/1/0/1 temp -f2s
0.5	0.5	1
0.25	0.25	A
0.7	0.7	C
```

**Comment by joa-quim** [comment]
I did read but the meaning of **t** is not obvious. Specially when it says *you must explicitly add the column t to retain the text.*. Which *column t*?

**Comment by PaulWessel** [comment]
"which column t" is nonsensical.  **t** refers to the entire trailing text **once it has been ingested into GMT.**  There are _n_ numerical columns (_n_ >= 0) plus optionally some trailing text. In a case like the one posted here, where the users third column cannot reliably be identified as trailing text based on the first column, we flag the third column as start of trailing text via -f2s and then all works consistently.

**Comment by joa-quim** [comment]
Sorry, but still far from clear. If one need to use **t** to retain the text why the **-in**? It seems **-in** equals no **t**.
>  Finally, -in will simply read the numerical input and skip any trailing text.

**Comment by PaulWessel** [comment]
OK, if it is unclear to you I will re-read it and see if I can improve it, but

1. Default action reads the whole record, including trailing text (if the module can use it - i.e., not in surface etc).  You never specify **t** to include trailing text, but you can use -in to skip it entirely.  Would not do you any good in the poster's case since col 3 was identified as data and you end up with those NaNs
2. On output, again trailing text is the default for most/all modules that pass records through (ie.., not block* etc). If you do not want text on output you use -on, and if you want a mix of columns you use t, e.g., -o2,3,t
3. If you have the above case and need to _explicitly_ say trailing text starts with column 2 then you use -f2s.

**Comment by joa-quim** [comment]
I may being particularly dumb tonight but when would we use **-it** then?

**Comment by PaulWessel** [comment]
I think you never use **-it**.  E.g.

```
echo 1 2 3 text | gmt convert -it
gmtconvert [ERROR]: Selection -it (just trailing text, no numerical input) is not allowed.  Consider using -ot instead, if available.
```

However, you _do_ use it if you select columns and want to include the trailing text:

```
echo 1 2 3 text | gmt convert -i2,1,t
3	2	text
```

versus

```
echo 1 2 3 text | gmt convert -i2,1  
3	2
```

**Comment by joa-quim** [comment]
Ah, finally got it. So instead of  
> used you must explicitly add the column t to retain the text

say something like:

> used you must explicitly add the t modifier to always retain the text on output

**Comment by PaulWessel** [comment]
OK, I can fix that.

**Comment by mvanneste** [comment]
Thanks for the swift response and actions! Impressive (as usual).

**Comment by mvanneste** [comment]
(Note: the same issue occurs with grdtrack)

**Comment by PaulWessel** [comment]
grdtrack uses the same -i, -f, -o as any other modules.  This is after the update?  What is the symptoms?

**Comment by mvanneste** [comment]
No, this is an observation before the updates, an example underneath. Also the column appear different

#!/bin/sh

gmtswitch gmt6

gmt grdmath -V -I.01 -R0/1/0/1 1 = test.grd

echo "0.1 0.1 A" > temp
echo ".7 .7 1" >> temp
echo "0.1 0.1 A" >> temp
echo "0.5 0.5 B" >> temp
gmt grdtrack temp -Gtest.grd
Result:
0.1          0.1          1              A
0.7          0.7          1              1
0.1          0.1          1              A
0.5          0.5          1              B

echo ".7 .7 1" > temp
echo "0.1 0.1 A" >> temp
echo "0.5 0.5 B" >> temp
gmt grdtrack temp -Gtest.grd
Result:
0.7          0.7          1              1
0.1          0.1          NaN       1
0.5          0.5          NaN       1

Maarten

**Comment by PaulWessel** [comment]
Works fine for me with master and the updates.
