### ISSUE TITLE
Make grid lines align with pi annotations

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5473]
This Julia script produces the shown figure where we can see that the vertical grid lines do not align with the annotations.

```
x = linspace(0,2π,50);

lines(x, sin.(x), ls="lineDiamond", legend=(label="sin(x)",), grid=(pen="gray90",), theme=("A2"), xaxis=(annot="pi2",), Vd=1)

["psxy  -JX14c/9.5c -Bpxapi2 -Bya -BWSrt -Bg --MAP_GRID_PEN_PRIMARY=gray90 -R-0.2/6.4/-1.1/1.1 -W0.75 -P -K > C:\\TMP\\GMTjl_tmp.ps", "psxy  -JX14c/9.5c --MAP_GRID_PEN_PRIMARY=gray90 -R-0.2/6.4/-1.1/1.1 -Sd0.13 -Gwhite -W0.75,black -K -O >> C:\\TMP\\GMTjl_tmp.ps"]
["S 0.375c - 0.75c - 0.75 0.89c sin(x)", "G -1l", "S - d 0.13 white 0.75,black - ", "S 0.375c - 0.75c - 0.75 0.89c cos(x)", "G -1l", "S - s 0.13 red 0.75,black - "]

lines!(x, cos.(x), ls="linesquare", legend=(label="cos(x)", pos=:MiddleCenter, box=:none), mc=:red, show=1)
```
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/124973409-64875500-e023-11eb-889f-f8ca4c8cb294.png)

**Comment by PaulWessel** [comment]
Because the auto-spacing for gridlines does not "know" that the annotation interval was set via pi steps. We will have to check that if pi-spacing is selected then that needs to be used for the auto-schemes.  However, since the only way to tell GMT that we want pi-intervals is via -B, and you do that for the annotation, why not also set it for gridlines?  E.g., -Bpxgpi8.

**Comment by joa-quim** [comment]
Not that important
