### ISSUE TITLE
Two ways to set annotation attributes in pscoupe

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#5486]
The two modules **meca** and **coupe** share many settings, such as **-S** and **-F**.  However, in pursuing a revision via #5341 I noticed that both documentation and code for **coupe** let users specify the same label attributes (font, justification, angle) via modifiers to either **-S** or **-F**, whereas **meca** only lets this happen via **-S**.  It is messy to have duplication of both parsing and documentation in two separate places, and only in **coupe**.

I propose we make **coupe** similar to **meca** and only let **-S** handle the label attributes.  What says @seisman ?

**Comment by seisman** [comment]
> both documentation and code for **coupe** let users specify the same label attributes (font, justification, angle) via modifiers to either **-S** or **-F**

You mean the **-Fs** option for **coupe**, right? 

Take the script https://github.com/GenericMappingTools/2021-unavco-course/blob/main/seismology/beachball-cross-section.sh as an example.

The output image with `-Sa1c` is:

![image](https://user-images.githubusercontent.com/3974108/126022424-8b074d5b-63c8-44e3-a069-28d40cdb504f.png)

If we change `-Sa1c` to `-Fsa1c`, the output image is:
![image](https://user-images.githubusercontent.com/3974108/126022440-ad381fea-cd0b-43ab-80fc-d0f75955ce3b.png)
However, the documentation says, the expected input parameters are:
```
lon lat depth string
```
but the actual given parameters are
```
lon lat depth strike dip rake mag string
```
So the actual behavior is inconsistent with the documentation. And in this case, using both `-S` and `-Fs` makes no sense.

**Comment by seisman** [comment]
I didn't run the old GMT4 or GMT5 **coupe** command, so I don't know if it should be considered as a bug or a documentation error.

I think we have two options:

1. Change the **-Fs** code to make the code consistent with the documentation. In this case, the input parameters are different when **-S** and **-Fs** are used, and we can't use the two options together.
2. Change the **-Fs** documentation (and maybe the code), so that the input parameters are always the same no matter **-Fs** is used or not. In this case, we can simplify the current **-Fs** syntax to **-Fs***symbol*, and **-S** is used to determine the input parameters, symbol size and label attributes.

The 2nd option makes more sense to me.

**Comment by PaulWessel** [comment]
I agree that option 2 makes most sense.  We will do this with backwards compatible so the code won't change, just the usage message and docs so someone's bad script will continue to run.
I will do this after I do the first-order massive upgrade to the variable terminal width...
