### ISSUE TITLE
Earth relief files and corruption during download

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#549]
I started a command downloading one of the earth relief grids. Midway, I killed the command. Issuing the same command again makes ``gmt`` think that the grid is downloaded (the file exists) and all good, when it's actually corrupted (aborted download). Not really an issue, but maybe nice for you to know. This may be a pitfall for inexperienced users.

```
$ grdcut @earth_relief_02m.grd -RGL,NO,IS,DK -Gbat.nc
^C
$ grdcut @earth_relief_02m.grd -RGL,NO,IS,DK -Gbat.nc
ERROR 4: `/home/user/.gmt/server/earth_relief_02m.grd' not recognized as a supported file format.
grdcut (api_import_grid): Not a supported grid format [earth_relief_02m.grd]
[Session grdcut (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
[Session grdcut (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
```

**Comment by PaulWessel** [comment]
We have discussed this case plus the situation when, say, earth_relief_15s gets updated in a few months then how will users get the new file?  We are thinking of maintaining a table on the server with a hash for each file and have that file be downloaded by the user during the first remote file call that day.  Then we can determine which files are out of sync (or plain wrong), remove them and redownload.  I think this is the recipe we agreed to @leouieda?

**Comment by leouieda** [comment]
:+1: that sounds right to me. Are there any possible security concerns with this?

**Comment by PaulWessel** [comment]
Hm, such as?

**Comment by leouieda** [comment]
Downloading a corrupted hash table, for example. I'm not sure if we need to have any concerns with this. Internet security is beyond my skill set. The user can be sure that the GMT source code is fine using a trusted download and checking the hash. But the hash table is downloaded from the GMT server and probably not checked at all. 

@ldldr you're the one with the most experience with this sort of thing. Do you see any possible problems?

**Comment by PaulWessel** [comment]
Meanwhile, while waiting for Godot (sorry, meant @ldldr) I have been playing with this a bit.  It seems we need a few things in the hash table: 

`Filename, M5D hash, file size.
`

We _do not_ want the user session to compute the M5D since running m5d on a 2 Gb file takes way too long.  So perhaps this recipe could work.  Say we run grdinfo @earth_relief_01:

1. Is gmt_m5d_server.txt > 1 day old? If so, get the latest file.
2. Compare the current and previous hash table and any file not listed in the current table or has a change in M5D, delete that file; this will force a re-download.
3. If file exist, get its size. If not matching the size in current hash table, delete the data file.
4. If file not in cache, get from server.

The idea is that once a day at the most, we update the hash table.  When that table is updated we perform the cleaning up in step (2).  Then, when we find a file locally we need to stat it and compare size to expected size.  This is our guard against a corrupted file such as @abanbj described above.  If sizes don't match, delete the file.  This last step happens each time we find a local copy of a desired file.  At this point there are two paths:

1. File exist and is of correct size and is in sync with the version on the server (within 1 day).  Use it.
2. File not available locally and we get it from the server, which gets the current version, followed by the size check.

Finally, guarding against a corrupted hash table: The first record in the hash table has the number of records to follow.  As we ingest that table as part of the above we will know if the record numbers match expectation.  If not we can take some action (warn, or re-download the hash table?).  I have no solution for other corruptions that might preserve the record count but mess up content - I think this would be pretty rare.

**Comment by abanbj** [comment]
My cryptographic alter ego just popped out and mentioned that ``md5`` was broken a lot of years ago. Maybe use a flavour of ``SHA`` instead? Because why not?

**Comment by PaulWessel** [comment]
We need to weight the extra work of changing what was implemented to the security risk.  Since this is all about public domain data sets available to all I dont see the risk.  Why would anyone go to the trouble of trying to replace any of these files with another with the same size and MD5 hash? Does not seem likely to me.

**Comment by abanbj** [comment]
I agree.

**Comment by KristofKoch** [comment]
Not exactly on topic but while you are in that part of the code – would you mind implementing some kind of error handling for a bad SOEST server? I was surprised by this once and couldn't figure out what the problem was. See closed #492

**Comment by leouieda** [comment]
> Why would anyone go to the trouble of trying to replace any of these files with another with the same size and MD5 hash?

One reason would be to trick GMT into downloading a malicious file to the user's computer.

**Comment by PaulWessel** [comment]
But would they not need access to our GMT server to place the malicious file there in the first place, overcoming authentication, etc?  The entire @remotefile scheme depends on the GMT server not being compromised, no?

**Comment by leouieda** [comment]
> The entire @remotefile scheme depends on the GMT server not being compromised, no?

Yes. And we have no safeguard against this. Which is why downloading the hash table from the server only serves for us to check for possible updates, not really for checking for corrupted files. Even if we use SHA256 instead of MD5. This is why I had recommended making the hash table a part of the GMT code so that it can't be changed without going through the repository and leaving a trace on the git log. But doing this requires releasing a new GMT version when we update the datasets. I view this as a positive but we would have to stream line the release process. 

Now that I'm thinking about it, this could potentially cause trouble for government employees using GMT if their IT teams raise red flags because of the remote file mechanism.

**Comment by PaulWessel** [comment]
I see your point.  Yes, it would mean distributing a gmt_md5.h include file with the source and update that file as things change, and then increment the version numbers and offer new releases more frequently.  Once releasing a new version is fully automatic (via CI flags etc) then there is not that much hassle for us.
But also this solution seems to imply that the user now has to calculate a md5 hash to detect that her downloaded data file differs from the updated md5 in the source, meaning we updated that data file with the new release and her file is now outdated.  That is different from my solution which provides the updated md5 hashes.  We would have to keep track of which user files still need to compute a hash, e.g., the first time @earth_relief_15s is accessed since the GMT release we must actually compute the MD5 which will add perhaps 30 seconds of calculation time - which will seem very long if all you did was running grdinfo on that file.  And then GMT learns the hash has changed and now download begins.  It also means md5, md5sum or whatever Windows calls it would be required.
As for government employees and remote files: Browsers are doing remote download all the time.  Not sure if there is a need to prevent users not to download a file but if so then turning off Internet would work, or set GMT_DATA_URL_LIMIT to 0.
We do have a safeguard against corrupted files on the SOEST server.  Only I can put files there, and if I wanted to be devious then I could also mess with gmt_md5.h as well.  I guess I still don't see the threat as very significant and warranting a very different implementation?

**Comment by leouieda** [comment]
Well, at this point I'm kind of guessing as to what a malicious person can or can't do. I'm no expert in security. We could just ignore this for now since the files are not being executed by GMT but they are being loaded into memory and the likely hood of an attack is low. As I said earlier, I'm trying to think of ways this could go bad and how we could mitigate it.  

> Only I can put files there

That is relying on the assumption that the server is perfectly secure and could never be hacked.

Package managers certainly have implementations for verifying downloads but I don't think we want to into that (GPG signing and what not). 

> Not sure if there is a need to prevent users not to download a file but if so then turning off Internet would work

We should include instructions for this in case people are concerned or need to be extra careful with security.

**Comment by joa-quim** [comment]
A GMT version per data files update is really not a good idea. And guys, we can download almost whatever we want by using the GDAL bridge /visicurl/ mechanism. So, let's keep this the simplest possible and move on.

**Comment by leouieda** [comment]
Fair enough. I'm probably being overly paranoid.

**Comment by PaulWessel** [comment]
We can make a mental note that when/if the gmt server is compromised we can consider our options.

**Comment by KristofKoch** [comment]
I was thinking about @PaulWessel's plan for file handling:

> Compare the current and previous hash table and any file not listed in the current table or has a change in M5D, delete that file; this will force a re-download.

I really like your approach making sure the user has the most current dataset. As the files are rather large you might want to consider users with limited bandwidth as well. Forcing a lengthy re-download on them at a most probably inconvenient point might not be a nice thing to do.

As I'm not as experienced as you guys, my crude idea might be not so bright but here it is:

* have GMT check for new file versions as outlined by @PaulWessel 
* keep a history of the old names/file sizes/hashes to compare against
* have an option where the user can choose if he wants automatic download (default) or manual download
* warn user when he isn't using the newest dataset and the option is set to manual download but make sure the old set is valid and run the command if the local dataset is valid (catches the @abanbj corrupted file case)

Also, what happens when the dataset changes its location? As most package maintainers are severely behind your release schedule there might be problems with users losing access to the datasets when using an older version of GMT from their preferred packet manager.

**Comment by PaulWessel** [comment]
We already have two GMT defaults that control whether or not files are auto-downloaded when GMT decides it needs to do so: 

1. **GMT_AUTO_DOWNLOAD**: Determines if GMT is allowed to automatically download datasets and files from the remote server selected via **GMT_DATA_URL**. Default is on but you can turn this off by setting it to off.
2. **GMT_DATA_URL_LIMIT**: Upper limit on the size of remote file to download [unlimited].

So I think the users have enough options to handle this situation (e..g, only get small files because no time, or turn off when having bad internet access).

As for data set changing location:  You mean locally? They are not under the package maintainers control (files are stored in your GMT user area, ~/.gmt) and since new GMT versions will continue to check the same hash file I do not see a problem; perhaps I am misunderstanding your point.

**Comment by PaulWessel** [comment]
The implementation as described has now been merged into master.

**Comment by KristofKoch** [comment]
@PaulWessel, I must admit I wasn't aware of these two GMT defaults. My apologies. I will RTFM more thoroughly next time.

**On data set changing location:** In the old forum lots of users ran quite outdated versions of GMT mostly installed through packet managers. You said elsewhere you plan to move away from the SOEST infrastructure. What happens if you move the data sets and the users don't have the newest GMT version with the new URL?

Sure, you could edit the default `GMT_DATA_URL`, but wouldn't it be easier to have the URL point to a server you control (generic-mapping-tools.org/something) by default and place a redirect there? `curl -L` follows the redirect and the data can live wherever it wants. No user interaction required which means less user support.

**Comment by leouieda** [comment]
@KristofKoch I don't imagine that we'll take down the server in one go. The most likely is that we'll migrate and only develop new stuff based on the new location but keep the server for a while to allow users to migrate. As you said, we can also setup redirects and communicate to the users that they can fix issues using `GMT_DATA_URL`. But at some point we have to require people to upgrade or do something. It's the same with GMT4 support.

**Comment by PaulWessel** [comment]
Now that we have purchased the generic-mapping-tools.org domain and have secured permission from the UH President to host that domain on the UH network, presumably it is possible for us to start using that URL instead of the SOEST URL pretty quickly.

**Comment by seisman** [comment]
Seems the issue has been fixed. Closed now.

**Comment by abanbj** [comment]
Hmm, I did this again and looks like gmt does not check the hash? Start download, kill it, then run the command again:

```
$ grdinfo @earth_relief_02m.grd
^C
$ grdinfo @earth_relief_02m.grd
ERROR 4: `/home/user/.gmt/server/earth_relief_02m.grd' not recognized as a supported file format.
grdinfo (api_import_grid): Not a supported grid format [earth_relief_02m.grd]
[Session grdinfo (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
[Session grdinfo (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
```

**Comment by PaulWessel** [comment]
Wow, you are brutal, @abanbj ! I will need to look, but perhaps the decision to only do a check on the hash once a day plays in here, i.e., it skips that step and goes directly to the file that it finds.  I am sure we don't want to add a check on the server each time we access a remote file.

The solution (down the road) is to add a SIG catching for Ctrl-C when downloading and if caught we delete what we did not finish downloading. I will have a look and then make an issue.

**Comment by abanbj** [comment]
I aim to please! Makes sense. Great Paul!

**Comment by PaulWessel** [comment]
Feel free to try the #1061 PR.  It worked for me on macOS.

**Comment by abanbj** [comment]
Tested and is sweet. Maybe also catch ``CTRL+Z``?

**Comment by PaulWessel** [comment]
What would that do?

**Comment by abanbj** [comment]
Suspending process (``SIGSTOP``), but I see now this cannot be intercepted by the program so it wouldnt help I guess.

**Comment by sajid-zaman** [comment]
[ gmt grdcut @earth_relief_01s -R53/84/26/39 -Gdem.grd
earth_relief_01s: Earth Relief at 1x1 arc seconds tiles provided by SRTMGL1 (land only) [NASA/USGS].]
I am stuck here, please let me know about the reference points. That's are correct or not

**Comment by anbj** [comment]
Questions in https://forum.generic-mapping-tools.org/ please.

**Comment by KristofKoch** [comment]
Hello @sajid-zaman! If you need help with your script please [ask your question in the GMT forum](https://forum.generic-mapping-tools.org).
