### ISSUE TITLE
Show only one figure format 

### ISSUE THREAD

**Issue by GeoChrisMilliner** [GenericMappingTools/gmt#5512]
When specifying multiple figure format, allow for showing only one type of format instead of all of them. 

For example:

`gmt begin worlds png, pdf, eps`

`gmt end show png`

I am unable to help implement this feature. 

Thank you.

**Comment by PaulWessel** [comment]
Thanks for the suggestion. We will look into this once the workshop is over.

**Comment by PaulWessel** [comment]
In considering what, if anything, we should do with this suggestion, I am looking at the options:

We have **GMT_END_SHOW** which is an optional environmental parameter than can be set to "off" and that deactivates any gmt end **show** statements.  It seems the easiest way to implement the user's request would be to allow that parameter to be "pdf" or "png,jpg" and then only those products listed are opened in the viewer [Default is all].  I certainly can see the usefulness of only opening the PNG and not worry about a bloated PDF since it is usually enough to just look at one flavor.
Do you agree that this is a reasonable thing to do and that this is a good way to implement it, @GenericMappingTools/core ?

**Comment by joa-quim** [comment]
Why not just only display the first format in the list? It will then be up to the user to select what to see.

**Comment by seisman** [comment]
> Why not just only display the first format in the list? It will then be up to the user to select what to see.

I like this idea!

**Comment by PaulWessel** [comment]
I do too, but it would be backwards incompatible with 6.2 and earlier.  But do we care in this case?

**Comment by PaulWessel** [comment]
We could call it a bug and then it is OK!

**Comment by joa-quim** [comment]
No incompatibility at all. It will produce exactly the same thing.

**Comment by PaulWessel** [comment]
> No incompatibility at all. It will produce exactly the same thing.

Not sure I follow.  If I do gmt begin map pdf,png it will currently open up two plots in the preview.  The proposed fix will reduce this to one.  I like that too but surely that is a change, no?

**Comment by joa-quim** [comment]
It's not a change in the sense that the two, pdf & png figures will still be created. The fact that user won't see it in double is just a detail. And anyway he/she would not see two because one would always overlay the other.

**Comment by PaulWessel** [comment]
We can implement this and claim a bug.  But the two would not overlap, at least not in macOS.  Here is what it looks after running

`gmt coast -RFR -Gred -B -png,pdf map`

![junk](https://user-images.githubusercontent.com/26473567/126412392-4f1bcda9-0724-479a-9083-76df126d85c4.jpg)

**Comment by joa-quim** [comment]
They do overlap on Windows.

**Comment by PaulWessel** [comment]
Fine, I think in either case we declare a bug and then there is no backwards compatibility.  I cannot imagine anyone complaining, no?
