### ISSUE TITLE
Movie. Improve use of -F

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#5522]
From the slack group of 2021 Unavco Course: 

> Federico Esteban: Is it -F (in movie) mandatory? I use movie with -M and without -F and I get all the frames (and they would be deleted if I used -Z).
> Paul Wessel: We may need to improve that.  I would agree that if no -F and a -M then it should be the same as -Fnone -M

**Comment by PaulWessel** [comment]
Looking at this some more I remember that **-F**_none_ is used to turn off the generation of the PNG frames.  So right now we have this situation with **-F**:

**mp4**: Create the PNGs then assemble them into a MP4 movie
**webm**: Create the PNGs then assemble them into a webm movie
**none**: Do not create the PNGs
Default: Create the PNGs but do not make a movie.

Note **-A** can be used with **-F** to create both the full MPG and an (optionally shorter version via **+s**) GIF.  Without **-F** we still produce the PNGs and hence **-A** work as well.

Users who do not wish to use FFmpeg to assemble the PNGs will want to create the PNGs and not the movies.  That is a valid requist and currently the default.  We could argue it if would have been better to have **-F**_png_ to only create the PNGs rather than **-F**_none_ to not create them.  Perhaps it is worth making the change:

`-Fpng|mp4|webm`

If no **-F** then no frames unless **-A** is set (all frames) or **-M** (one frame).  This would let use use -M without -Fnone.  It would also force the user to select a product via -Fpng if that is what they want.  I think this is a better system than what I implemented.

Thoughts, @GenericMappingTools/core ?

**Comment by PaulWessel** [comment]
Messy with **-A** and **-M** requiring certain settings in **-F** etc. I have decided to eliminate **-A** and merge it with **-F** in a more compact setup (backwards compatible of course):

**-F**_gif_|_mp4_|_webm_|_png_[**+l**[_n_]][**+o**_opts_][**+s**_stride_][**+t**]

A PR will come after some testing.

**Comment by Esteban82** [comment]
It would be possible to ask for multiple formats? I mean to get a mp4 and gif files.
