### ISSUE TITLE
Possibility of specifying grid spacing using grdview -Qsm option

### ISSUE THREAD

**Issue by GeohunterX** [GenericMappingTools/gmt#554]
**Description of the desired feature**

Using the grdview -Qsm option for high resolution data makes the draped mesh very dense and dark (even if specifying the pen it stays too dark due to high density in some cases). It would be very useful if one could specify the grid spacing seperately - without downsampling the grid itself.

**Are you willing to help implement and maintain this feature?** Yes/No
No - I would love to, but unfortunately I don't think my skills are good enough for this task...
![densegrid](https://user-images.githubusercontent.com/48683258/54777207-1c558600-4c12-11e9-8c27-9e1a1785454d.JPG)

**Comment by PaulWessel** [comment]
One reason why we do not have such an option is it leads to aliasing.  We don't want GMT to enable users to commit aliasing.  it is always better to filter and resample than just picking every n'th value.

**Comment by leouieda** [comment]
But in that case the mesh wouldn't drape the surface, right? I don't know if there is a big issue with aliasing if the mesh is always accompanied by the surface. They would be like grid lines in maps.

**Comment by PaulWessel** [comment]
Here, what you see is the mesh, composed of various 4-corner polygons that are drawn and optionally painted like here.  The mesh _is_ the surface. And because of hidden-line effects it is drawn a certain way.  It would not be hard to, say, only use every _n_'th point in x and y and skip the rest, but it would be hard to draw the full surface but only draw mesh lines less frequently (i.e., your gridlines analogy).  Not impossible but more work to figure out (plot the mesh patch, then occasionally plot some of its outline as they line up with the chosen mesh spacing).

**Comment by GeohunterX** [comment]
Oh yes, I see. I wasn't thinking of the problem of aliasing since I my idea was exactly what you mentioned @PaulWessel : plotting the surface in its original resolution and "draping" a mesh/grid with only every n'th node. This would prevent aliasing since the grid itself is also displayed as a surface.
