### ISSUE TITLE
Fix documentation for the grdhisteq -N option

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5591]
The behavior of the grdhisteq -N option when *norm* is appended is not currently clear. The documentation should be improved to clarify usage expectations and behavior.

_Originally posted by @PaulWessel in https://github.com/GenericMappingTools/gmt/issues/5563#issuecomment-892882183_

**Comment by PaulWessel** [comment]
Upon checking the usage message and the rst docs I think it is actually almost clear: We produce Gaussian z-scores (which theoretically range from -infinity to +infinity but here they are typically in the -4 to +4 range (the tails).  However, if **-N** is given a _norm_ then the output is normalized to range from -_norm_ to +_norm_. The problem is the docs says **-N**_norm_ yields ±1 but it gives ±norm.  Upcoming PR will fix the usage and RST docs.
