### ISSUE TITLE
Add link to the resources sidebar from plot module documentation

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#5603]
**Description of the desired feature**

In the caption to the figure showing custom symbols, there is a reference to "RESOURCES page (see sidebar)". This text should be replaced with an actual relative URL.  This is in the [plot](https://docs.generic-mapping-tools.org/dev/plot.html#s) module.

**Comment by soham4abc** [comment]
What will is the url that that needs to be replaced? would you please specify?

**Comment by meghanrjones** [comment]
This is the page that the link should go to: https://docs.generic-mapping-tools.org/latest/users-contrib-symbols.html. You can add a link to the page using restructured text internal links rather than absolute URLs ([more info](https://docs.generic-mapping-tools.org/dev/devdocs/rst-cheatsheet.html#internal-links)).

Here's an example of an internal link to that particular page:
```
:ref:`Symbols gallery <symbols_gallery>`
```

The  "RESOURCES page (see sidebar)" occurs in this source file: https://github.com/GenericMappingTools/gmt/blob/master/doc/rst/source/explain_symbols.rst_, so you'd need to update L296.

**Comment by soham4abc** [comment]
> This is the page that the link should go to: https://docs.generic-mapping-tools.org/latest/users-contrib-symbols.html. You can add a link to the page using restructured text internal links rather than absolute URLs ([more info](https://docs.generic-mapping-tools.org/dev/devdocs/rst-cheatsheet.html#internal-links)).
> 
> Here's an example of an internal link to that particular page:
> 
> ```
> :ref:`Symbols gallery <symbols_gallery>`
> ```
> 
> The "RESOURCES page (see sidebar)" occurs in this source file: https://github.com/GenericMappingTools/gmt/blob/master/doc/rst/source/explain_symbols.rst_, so you'd need to update L296.

Thanks a lot, working on this issue right away.. if possible please assign.
