### ISSUE TITLE
Error if using the "jpeg" as the format suffix

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5669]
**Full script that generated the error**

```
gmt begin map jpeg
	gmt basemap -R0/10/0/10 -JX10c -Baf
gmt end show
```

`jpeg` is used but the generate plot is "map.jpg".

**Full error message**

```
The file /Users/seisman/workspace/map.jpeg does not exist.
docs [ERROR]: Opening local files via open map.jpeg failed with error 256
docs: No such file or directory
end [ERROR]: Failed to call docs
end [ERROR]: gmtinit_process_figures returned error 79
```

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): 6.3.0_c9da416_2021.08.11

**Comment by meghanrjones** [comment]
"jpeg" is not a supported graphic format; gmt begin expects "jpg". Do you think it should work as written or just have a better error message?

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/gmt/blob/76fa3ccc16f747748711d0e16e5b6e9b1bd4652e/src/gmt_gsformats.h#L32

`jpeg` is a valid graphic format, although it's not well documented.

**Comment by PaulWessel** [comment]
So I assume what happens is that when **psconvert** is called there is no longer a jpeg or tiff variant and the j becomes jpg and that clashes with the session name, etc.  I can have a look this afternoon. Is jpeg as a name widely used? I know Apple Photos will write that but why is it so hard to stick with one extension?  Anyway, we will fix this issue.

**Comment by PaulWessel** [comment]
So reading a big about this jpeg vs jpg. It really should be .jpeg of course (and .tiff) but for eons this has been abbreviated to three characters due to DOS/early Windows limitations that no longer are relevant.  Still, it is very common to see .jpg on all OS. I noticed that if I run the above command with tiff or tif it works in both cases, yet the output file is called *.tif in both cases.  This is because tiff and tif reduce to 't' and that is passed to **psconvert** who will create the .tif extension [it has no knowledge of the t originating as tiff].  However, if jpeg is used it is reduced to j (as is jpg) and in both cases **psconvert** produces a .jpg file.  Clearly there is an issue in docs which cannot find the .jpeg file it expects somehow.

So, I assume we want this behavior: File extension should match exactly the requested graphics argument (jpeg -> .jpeg, etc).  The only exception is PNG which is the uppercase flag to set transparent png.

I think **gmt end** who is doing the calling to **psconvert** knows what the original extensions are and that is the place to insert a file rename call for those two cases.  OK?

**Comment by PaulWessel** [comment]
Hi @joa-quim, there are two ways for me to fix this problem via psconvert:

1. I can add J and T as "new" format flags in **-T** and they would supply the full jpeg and tiff extensions
2. We could add a modifier (e.g., **+l** for long) that turns off the 3-char extension limitation.

Seems to me it would be simpler to use **-TJ** than to say **-Tj+l** for long.  So I suggest we do J and T.  What you think? The alternative is to continue to let **psconvert** only know about 3-char extensions and handle this via a rename in **end**.

**Comment by seisman** [comment]
I'm wondering if it's simpler to only allow 3-char extensions even people use "jpeg" or "tiff".

"jpeg" and "tiff" are the formats, but the extensions are always "jpg" and "if".

**Comment by PaulWessel** [comment]
Well, that is the issue, no: The extensions are not always that.  On mac they are .jpeg for instance, at least Apple creates those.

**Comment by joa-quim** [comment]
I'm sorry if I fail to understand the extension issue. Extension in most cases (but not all) mean nothing for machines. Only for humans. Macs even tried to get rid of extensions and Windows even copied that stupid move by hiding known extensions from displayed file names in file manager. ``*.jpeg`` or ``*.jpg`` should be exactly the same from user experience perspective. It's not exactly the same with ``*.tiff`` and ``*.tif`` where there is, sometimes used assumption that ``*.tiff`` means a *geotiff* file, whereas ``*.tif`` not. But this is not a convention assumed by us (though I do) so let's just ignore it.

But we have a true issue because Dongdong's example raises an error. The best solution for me is just deal with it under the hood and have **gmt end** do the renaming. Don't complicate it with further flags.

**Comment by PaulWessel** [comment]
OK, I will do the gmt end solution and leave psconvert as is.
