### ISSUE TITLE
gmt plot without options not working in modern mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#57]
**Description of the problem**
This bug was first reported in issue http://gmt.soest.hawaii.edu/issues/1206, and was fixed in [r19961](https://gmt.soest.hawaii.edu/projects/gmt/repository/revisions/19961). However, the bug appear again now. 

**Full script that generated the error**

```
gmt begin test pdf
gmt plot -JX10c/10c -R0/10/0/10 -Bafg -W2p,blue << EOF
0 0 
3 3
EOF
gmt plot << EOF
4 4
6 6
EOF
gmt end
```

**Full error message**

The second `plot` just prints usage to terminal.

**System information**

* Operating system: macOS
* Version of GMT: 6.0.0_6a11ef0

**Comment by PaulWessel** [comment]
Hm, you did say it worked before but I am not sure why, or perhaps another change in the code broke it.  The problem is this: gmt plot with no arguments (i.e., give usage message) and gmt plot << EOF are identical to the program; the redirection is not felt by gmt.  So how would we know that you expect to read form stdin when gmt plot is typed?  Also, there are some modules (gmt info comes to mind) that is happy to work without arguments and will process gmt info << EOF just fine.  This module requires the -? option to print its usage...

Some possible things we could do:

1. We could decree that in modern mode, a module without options needs -? to print its usage, otherwise it expects to read stdin with the default settings. 

- Pro: This makes sense for modern scripts since nobody wants a usage message in the middle of a script (like seisman's example).  Outside of modern mode, things would remain the same since classic should be unchanged.
- Con: Not sure what the cons are.  Maybe it means a user could not type gmt begin and then do an interactive session (to benefit from simplified syntax) but then would be unable to type "gmt module" and get the usage message.  Even running gmt via Python or Julia in a Jupiter notebook would not want to see usage messages as you would have links to the documentation, no?

2. We could decree that all modules must have at least one option to run in modern mode, else give usage.  In this case, seisman would have to supply the default pen explicitly (e.g., -Wdefault), and users of gmt info << EOF would have to supply -Aa to make the module run as it does in classic mode.

- Pro: It would be common behavior for all modules, under modern mode only.
- Con: A few commands with very specific selections (such as seisman's 2nd plot command and maybe the plan gmt info) would need to add options not needed in classic mode.  However, there are no modern scripts so again we are not violating anyones modern script.

Seems to me either of these would solve the problem and leave classic mode along, but they are different implementations.  It seems to me that option 1 basically leaves the module functioning alone and only adds the single new requirement of -? to see the usage in the middle of a modern mode session, so that would be my choice.

Happy to entertain other thoughts here.

**Comment by joa-quim** [comment]
I think that 1) is the only that makes sense because it says it makes no sense to print the usage message in the middle of a script.
