### ISSUE TITLE
Incorrect colorbar annotations if colorbar is the only elements in one panel

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5723]
**Description of the problem**

**Full script that generated the error**

```
gmt begin map
	  gmt subplot begin 2x2 -Ff5i/3i -M0.5c/0c
		    gmt subplot set 0
		    gmt grdimage @earth_relief_01d -JQ180/? -Rg -Ba60g60 -BWseN
		    gmt subplot set 1
		    gmt grdimage @earth_relief_01d -JQ180/? -Rg -Ba60g60 -BWseN
		    gmt subplot set 2
		    gmt grdimage @earth_relief_01d -JQ180/? -Rg -Ba60g60 -BWseN
		    gmt subplot set 3
		    gmt colorbar -Dx0.4i/0.8i+w1i/0.1i+h+jTL -Crelief -Bxaf
	  gmt subplot end
gmt end show
```

**Actual outcome**

![map](https://user-images.githubusercontent.com/3974108/131602001-dca60006-7893-4d12-8239-36cadb6682e5.png)

If I remove `-Bxaf` in the `colorbar` command, the output figure looks correct.

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): 6.3.0_469d64e-dirty_2021.08.28

**Comment by PaulWessel** [comment]
I will label this as user error.  There is no **-R -J** settings for that panel since there is no common **-R -J** settings for the entire subplot, just individual panels.  So when we get to that last panel, we are in the dark.  The **-B** option requires some context here that is not present.  If you move **-Rg** to the subplot begin command then all is well - or if you add -R -J to the last panel.  It works without **-Bxaf** since without **-B** **colorbar** will do its own thing based on its dimension (not **-R -J**).  The **-B** requires **-R -J** to be active.
