### ISSUE TITLE
'Edit on Github' link broken on https://docs.generic-mapping-tools.org/latest/rst-cheatsheet.html

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#5752]
The 'Edit on Github' link is broken on https://docs.generic-mapping-tools.org/latest/rst-cheatsheet.html.
Don't know if this applies to other pages as well.

Do not know how to fix it.

**Comment by seisman** [comment]
The link is broken because we moved the ReST file from `doc/rst/source/rst-cheatsheet.rst` to `doc/rst/source/devdocs/rst-cheatsheet.rst` in PR https://github.com/GenericMappingTools/gmt/pull/5589.

The documentation you're viewing is for the GMT 6.2.0 release, and it's no longer updated after we made the release. Thus links may be broken and we can't fix them.

If you want to edit the documentation source files, you'd better visit the dev documentation instead, for example, https://docs.generic-mapping-tools.org/dev/devdocs/rst-cheatsheet.html

**Comment by anbj** [comment]
So https://docs.generic-mapping-tools.org/latest is not latest - it's actually the GMT 6.2.0 release? The name confuses me.

**Comment by Esteban82** [comment]
Latest refers to the official releases. So 6.2 right now.

**Comment by Esteban82** [comment]
Dev is the development version that would be the next official release (6.3).

**Comment by seisman** [comment]
![image](https://user-images.githubusercontent.com/3974108/133007568-99fbbaf4-19a9-4265-876a-697c7047f29e.png)

In the version switcher, you should see that "latest" means "6.2.0"

**Comment by anbj** [comment]
Ah, I see.

Thanks!
