### ISSUE TITLE
Adding colorbar changes the width and height history

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5761]
**Description of the problem**

The issue was first found in https://github.com/GenericMappingTools/pygmt/pull/1428#discussion_r706820635.

**Full script that generated the error**

The following script works as expected. `-Xw+2c` shifts the plot origin based on the width of the left plot.
```
gmt begin map
    gmt grdimage @earth_relief_01d -B0
    gmt grdimage @earth_relief_01d -B0 -Xw+2c
gmt end show
```

![map](https://user-images.githubusercontent.com/3974108/133353120-85ced9b0-eabd-4581-84ff-8616f3623f68.png)

However, if we add a colorbar in the left-side plot, `-Xw+2c` no longer works. I guess that calling the `colorbar` command changes the width and height settings in the gmt.history file. Is it intentional? Do we need to save the colorbar width and height?
```
gmt begin map
    gmt grdimage @earth_relief_01d -B0
    gmt colorbar -DJML
    gmt grdimage @earth_relief_01d -B0 -Xw+2c
gmt end show
```

![map](https://user-images.githubusercontent.com/3974108/133353032-c31a62b6-ebea-4988-97f6-3440b966e3ec.png)

**Comment by PaulWessel** [comment]
I think we have no defense against this.  The w and h shorts for -X -Y is based on the previous plot.  We could possibly ignore embellishment commands (colormap, scale, etc) in this so that it would remember the previous real plot but not sure if that is a great idea in general, but perhaps it is.  We can discuss that.  The modules that take -DJ etc are colorbar, logo, legend, image, and I can see that perhaps colorbar and legend perhaps should not count, a user may very well place a full plot via image, and not sure if very many uses logo.  But even if in the above case we remember that w is the grdimage width, if the user did -DJMR then it still would fail since we would have to add even further to the right...

So perhaps best is to clarify the scope of w and h in the documentation so there are no surprises?

**Comment by meghanrjones** [comment]
I'll update the documentation for w and h based on the interpretation that we can't adjust for this case in the code.
