### ISSUE TITLE
Ocean values are not filled for earth_relief 01s or 03s

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5876]
**Description of the problem**

From the remote dataset documentation, "When these grids are accessed as @earth_relief_01s or @earth_relief_03s we will automatically up-sample the relevant @earth_relief_15s tiles to fill in the missing ocean values." The ocean values are no longer filled in the master branch, which is a regression since 6.2.0.

**Full script that generated the error**

```
gmt grdimage @earth_relief_03s -R-71/-70/41/42 -JM6i -Baf -V -png 6.2.0
``` 
**Actual outcome**

![dev-branch](https://user-images.githubusercontent.com/14077947/137826516-9697c392-fff7-4291-8745-16cbe318b904.png)

**Expected outcome**

![6 2 0](https://user-images.githubusercontent.com/14077947/137826564-0f72e471-0625-49fe-bb64-8faa2118c6a4.png)

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): 6.3.0_3becbaa_2021.10.18

**Comment by PaulWessel** [comment]
So this seems to relate to a recent change based on another PyGMT example where the user was surprised to see us download earth_relief_15s when only land was involved.  I could be mistaken but I think the user used earth_relief and not earth_srtm in that case.  There is really no way for me to know if the 15s will be needed or not in the case when all the tiles inside the region was found, since tiles may only partially cover land.  So I will need to revert this fix since I cannot think of a way to determine uniquely that the selected region partly includes the ocean.  I could check if any of the 4 corners of the region is in the ocean, but I am sure there are regions where a fjord intrudes in the middle of a side and I would miss it.

One idea: Right now, the strm_tiles.nc grid only stores 0 if no SRTM tile and 1 if there is a tile.  We could improve on this and compute a 3rd value if there is any ocean in a tile.  for example, 0 could mean no tile, 1 could mean tile entirely on land, and 2 could mean a tile but also ocean.  I could create a script that would take quite some time to compute that grid, but then we would have the solution we want.  Agreed?

**Comment by PaulWessel** [comment]
Basically a gmt grdlandmask job.  Which, now that I am thinking, we have already done via the earth_mask process.  I just need to determine, on a 1x1 degree box, if the 15s earth mask shows evidence of ocean.
