### ISSUE TITLE
Issue with grdcut and autoresolution earth_relief

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6047]
## Intro:

I want to make a topographic map of the western hemisphere. I try this command and works fine:

```
gmt grdcut @earth_relief_10m -Gcut_west.nc -Vi -R-180/0/-90/90`
grdcut [INFORMATION]: New:grdcut [INFORMATION]: 	-180	0	-90	90	0.166666666667	0.166666666667	1080	1080

```

## Issue:

When I try use the auto-resolution feature of `earth_relief`I have to add `-J`. **With the followings commands I get a grid of the whole earth.** 

```
 gmt grdcut @earth_relief -Gcut_west.nc -Vi -R-180/0/-90/90 -JX15
 gmt grdcut @earth_relief -Gcut_west.nc -Vi -R-180/0/-90/90 -JW15c
 gmt grdcut @earth_relief -Gcut_west.nc -Vi -R-180/0/-90/90 -JG-90/0/15c

grdcut [INFORMATION]: New:grdcut [INFORMATION]: 	0	360	-90	90	0.1	0.1	3600	1800
```

## Note 1:

I got a western hemisphere grid when I use Mercator.

```
gmt grdcut @earth_relief -Gcut_west.nc -Vi -R-180/0/-89/89 -JM15c
grdcut [INFORMATION]: New:grdcut [INFORMATION]: 	-180	0	-89	89	0.0166666666667	0.0166666666667	10800	10680

```

## Note 2: 
BTW, first I try to use `grdgradient` to download the @earth_relief but I get a message that I must use `grdcut` to set the autoresolution. So when I processed cut_west.nc I end processing the whole eastern hemisphere that I didn't need it.

**Comment by PaulWessel** [comment]
I will see what can be done.  I think what happens is that whenever you go to +90 or -90 in latitude you automatically get 0-360 in longitude since the pole point has all those longitudes.  I think even the -JX case knows the the remote data set is in fact geographic and does the same thing.  But given you have a central latitude at Equator we do not actually need 360 since we are not going across the pole.  So maybe there is a check that can be improved to detect this special case.

Yes, grdgradient , like most grd* modules not making plots all need a specific resolution to function.

**Comment by meghanrjones** [comment]
Can this issue be closed or is there more to be done here?

**Comment by meghanrjones** [comment]
Closed by https://github.com/GenericMappingTools/gmt/pull/6077
