### ISSUE TITLE
The KNOWN FAILURES status

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6068]
We have a set of test failures that are long-lived or due to sutble architectural differences between Windows and *nix.  These are marked with `# GMT_KNOWN_FAILURE_WINDOWS` or `# GMT_KNOWN_FAILURE`.  Since we now never get reminders that these fail, we forget.

One can tell Cmake to include these failures by uncommenting the line

`set (GMT_ENABLE_KNOWN2FAIL OFF)`

in cmake/ConfigUserAdvanced.cmake and build and run the tests.  I just did that.  That way I relearned that, for instance, _psbasemap/map_JE.sh_ is flagged as a Windows failure but the plot looks fine on macOS so I assume these are tiny differences in the gridlines that triggers the failures.  That is very different from actual failures across all OS due to bugs in GMT.  Just looking at the PNG and PDFs resulting from the failed tests I wonder if these non-issues but failing Windows test scripts:

```
psbasemap/map_JE.sh
test/grdvector/vectors.sh
test/mapproject/oblmerc_down.sh
```

should instead be reclassified with a slightly higher RMS setting, e.g. as in

`./pscoast/oblsuite.sh:# GRAPHICSMAGICK_RMS = 0.02`

@meghanrjones, could you please have a look at this and determine what those RMS might be and then we can remove the **GMT_KNOWN_FAILURE_WINDOWS** and instead set the higher RMS trigger points?

**Comment by meghanrjones** [comment]
The `test/grdvector/vectors.sh` test failure on windows is due to inconsistencies in clipping depending on the vector begin coordinates. This is the diff for the original test:
![vectors](https://user-images.githubusercontent.com/14077947/144126967-012407cf-2277-4765-af7a-82f1b1af0f83.png)

And this is the diff if I add -N to the grdvector commands:
![vectors](https://user-images.githubusercontent.com/14077947/144126869-c632d1ce-366f-4ab9-9181-0349b10fa2f5.png)

The windows case actually seems more consistent than the macOS result because neither of the vectors near the southern pole are plotted unless -N is given, whereas one of the two are plotted for macOS without -N.

**Comment by PaulWessel** [comment]
Looks like with the pixel registration those vectors have latitudes that might fall exactly on the lower horizon.  Perhaps we can avoid the issue by using JG45/41/4.5i ?

**Comment by meghanrjones** [comment]
> Looks like with the pixel registration those vectors have latitudes that might fall exactly on the lower horizon. Perhaps we can avoid the issue by using JG45/41/4.5i ?

That would work, but we would also need to update the PS file. Do you prefer that over the original suggestion to increase the RMS limit (would need to be 0.02 to pass on windows)?

**Comment by PaulWessel** [comment]
No, I guess the 0.02 is a better solution.
