### ISSUE TITLE
remove error: Permission denied when using high-resolution remote grids on Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#6183]
**Description of the problem**

I don't have a Windows machine so I can't reproduce it, but many Windows users in China have seen errors like this while some other users never see the errors. 

![image](https://user-images.githubusercontent.com/3974108/147915321-7a288ad4-10a0-4a53-956d-4cba048360ca.png)

It happens when users use high-resolution remote grids on Windows. The error doesn't make sense to me, because GMT is able to create temporary grdlbend grids and should have the permission to delete them.

**Comment by joa-quim** [comment]
We have had similar reports in the past. My guess is that the file is tried to be deleted while the pointer to the file is still open. In those cases we get that permission denied message. We need the full (variables please) command that raises this issue.

**Comment by PaulWessel** [comment]
It is a good point.  As I look, it is not clear to me now if we actually close those temporary files explicitly (the end of the module will do so as the process ends and the system takes care of it).  This is specifically for those temp files since here we do this:

```
if (B[k].open) {	/* If an open file then we wipe */
	if (GMT_Destroy_Data (GMT->parent, &B[k].G)) return GMT_NOERROR;
	B[k].open = false;
	gmt_M_free (GMT, B[k].z);
	gmt_M_free (GMT, B[k].RbR);
	if (B[k].delete)	/* Delete the temporary resampled file */
		if (gmt_remove_file (GMT, B[k].file))	/* Oops, removal failed */
		GMT_Report (GMT->parent, GMT_MSG_ERROR, "Failed to delete file %s\n", B[k].file);
}
```

There is nothing in here that actually _closes_ the netCDF file we have opened for row-by-row reading.  And since this mode of i/o only happens in **grdblend** it was probably never an issue until we did the resampling, and it still is not a problem on *nix so there...

I will have a look at what happens to those open netcdf file pointers.
