### ISSUE TITLE
Question. Where is gmt when installed via Conda?!?

### ISSUE THREAD

**Issue by isobelrlawrence** [GenericMappingTools/gmt#632]
Hello,

I previously installed GMT using Homebrew and have been using it happily for years. I have also been running Python 3.7 managed by Anaconda. Last week something happened, not really sure what but I think it was a package dependency problem, and GMT stopped working. 

I've decided to install GMT now with conda to try and avoid dependency conflicts; so I ran
```
conda install gmt --channel conda-forge
```
as suggested on the installation Wiki. It said it installed fine but when i type 'gmt' at the command line, nothing is found. And 'import gmt' in python also returns nothing.

So my question is... where is this GMT installed via conda and how do I use it?

Many thanks

**Comment by leouieda** [comment]
Hi @isobelrlawrence, thanks for reporting the issue!

> where is this GMT installed via conda 

All conda install packages go into the folder where you installed Anaconda. On linux and Mac, I think this is usually `~/anaconda` but it depends on where you decided during setup. The `gmt` executable should be in the `bin` folder in that directory. 

>  how do I use it?

It should be put in your `PATH` by default. Could you please post here the output of `conda list  --show-channel-urls`?

>  And 'import gmt' in python also returns nothing.

It shouldn't, since you installed GMT and not [PyGMT](https://www.pygmt.org/dev/install.html). That was a terrible naming choice on my part to have the Python wrapper called `gmt`. That's part of the reason why the project was renamed `pygmt`. Note that PyGMT is not yet released so there is no conda package for it.
