### ISSUE TITLE
Remote dataset docs: indicate if dataset is split up into tiles

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6320]
The high-resolution versions of the [remote data sets](https://www.generic-mapping-tools.org/remote-datasets/index.html) are subdivided into smaller tiles for obvious reasons (..), but:

* is the reasoning behind this described anywhere in the docs?
* does it even state in the docs that the higher resolution grids are in fact split up into smaller tiles?
* one single file vs. sub-tiles - is there a fixed threshold for when a dataset becomes tiled? Resolution > [?]m?
* I think it would be useful to indicate the resolutions at which a dataset comes in a tiled form. Maybe simply put an asterisk of something in the dataset [table](https://www.generic-mapping-tools.org/remote-datasets/earth-gebco.html#usage).

I'll be happy to help with this, if it's interesting.

**Comment by PaulWessel** [comment]
We do discuss technical aspects [here](https://docs.generic-mapping-tools.org/dev/datasets/remote-data.html).  However, we certainly could add some language about tiling there.  I think this is true (@meghanrjones may correct me):

All datasets resolutions from 5m and smaller are tiled
None of the images (night, day) are tiled at all
Earth mask is not tiled since so small even at 15s

So the technical section could have another paragraph discussing tiling and why, and say the 6m and coarser grids are single-file, with exceptions noted in the data docs, and then the specific exceptions can be mentioned there?

**Comment by anbj** [comment]
Sounds very good. What about adding a column in the table for each dataset (that shows resolution etc.) to indicate if that resolution is tiled? With an asterisk or something. Or is it overkill?

**Comment by PaulWessel** [comment]
Bringing @meghanrjones into this since she set up the remote data documentation repo.  Any suggestions for how best to do this?

**Comment by meghanrjones** [comment]
I think an asterisk next to the size in the tables could work well, since it would be pertinent for the users to know this information from the [file compression section](https://docs.generic-mapping-tools.org/latest/datasets/remote-data.html#file-compression) - "However, for the tiled data sets we only download the tiles that intersect your selected region the first time they are referenced."

**Comment by anbj** [comment]
Sounds good! The only thing I don't like about having an asterisk next to the size in the tables is that it probably won't line perfectly up, as it would if it was in a dedicated column. But, details.

**Comment by meghanrjones** [comment]
I recommend trying it for one table first to preview the changes in a PR. I'm not opposed to a dedicated column if it makes it look much nicer.

**Comment by anbj** [comment]
I'll fork https://github.com/GenericMappingTools/remote-datasets and do some testing.

**Comment by anbj** [comment]
See screenshot (just for testing appearance)

. I think a dedicated column may be a bit too much. Having an asterisk next to the size works nicely, as Meghan proposed.

Now the essential question;

* asterisk the datasets that are tiled
* asterisk the datasets that are not tiled

What say you?
![Screenshot from 2022-02-09 08-27-27](https://user-images.githubusercontent.com/29237824/153142380-2c8be47d-c0cb-4571-a762-4f8ac2965701.png)

**Comment by PaulWessel** [comment]
I think asterisk next to the code is best since size changes a lot but for most things change at 06m.  * should mean tiled.

**Comment by anbj** [comment]
Ok! I'll make a PR.

**Comment by PaulWessel** [comment]
OK, I can make a PR addressing the images and masks first.
