### ISSUE TITLE
psxy -Z<const> ignores pen thickness in Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6328]
While reproducing the ``variable_z.sh`` test in Julia I noticed that all cases work but the last.

```
D = [mat2ds([0 0; 0 1; 1 1; 1 0.3; 0 0])[1], mat2ds([1 1; 1 2; 2 2; 2 1; 1 1])[1]];
C = makecpt(cmap = :hot, range = (0, 5));

psxy(D, frame=:bare, C=C, level=3, pen=20, Vd=1, show=1)
        psxy  -JX14c/0 -B0 -R-0.1/2.1/-0.1/2.1 -Z3 -C -G+z -L -W20 -P -K > C:\TEMP\GMTjl_tmp.ps
```
Not that it ignores the outline pen thickness.
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/153312678-20e7a8bb-72ec-45fc-96cc-d9485bf7790a.png)

The entire test for reference
 
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/153312947-925ae44a-6f81-47e3-a5dc-14045d69e15f.png)

**Comment by PaulWessel** [comment]
Looking at your case:

`gmt plot pol.txt -JX14c/0 -B0 -R-0.1/2.1/-0.1/2.1 -Z3 -Ct.cpt -G+z -L -W20 -png t`

works correctly.  So what is the difference? You are passing in the polygons and that clearly works fine (shapes are right).  You specify a single z-value for the lookup, which works, and then you are giving a fixed pen thickness, which does not work?  So where could it possibly ignore the pen specification (I am asking since I acknowledge your plot but I fail to see how this is different from the -W2p case unless I am blind and your -W20 has a capital o in it...). Your echoed psxy call worked fine for me in classic mode as well.

**Comment by joa-quim** [comment]
Yes, can't see why it is failing but passing a vector works, so ... no idea
```
psxy(D, frame=:bare, C=C, level=[3,3], pen=20, Vd=1, show=1)
        psxy  -JX14c/0 -B0 -R-0.1/2.1/-0.1/2.1 -Z -C -G+z -L -W20 -P -K > C:\TEMP\GMTjl_tmp.ps
```
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/153316145-af324baf-84a4-4f33-b987-16262470c462.png)

**Comment by PaulWessel** [comment]
In debug I can see that the two segments you pass in as a data set have segment headers that are not NULL and both segment headers say " -W0.5".  So something you are doing by default it seems.
