### ISSUE TITLE
grdview -T+o<pen> screws

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6359]
While working in a ``pcode`` module for Julia I noticed this bad behavior of the the pen setting of ``grdview.'s -T`` option

```
gmt grdview lixo.grd -R-3.15/3.15/-3.15/3.15 -JX14c/0 -Baf -n+a -T+s+o2,dash -Clixo.cpt -png lixo
```
[files.zip](https://github.com/GenericMappingTools/gmt/files/8105220/files.zip)
![lixo](https://user-images.githubusercontent.com/537321/154870551-8d70d1fe-95aa-4b9e-9824-5d95f92e1a69.png)

**Comment by PaulWessel** [comment]
What you are seeing is that we loop over the cells and for each we plot a polygon with an outline.  Since a pen has a final width the outline will extend outside the cell.  Then the next cell is painted and it will overlay any previously plotted neighbors outline by half that pen width.  Since outlines start in one corner (SW I think) and draw clockwise, and cell sizes are under the control of the user (scale, increments) then the line going from W to E along S is not in sync with the line going from E to W along N in terms of dash vs gap locations; that would require you to do some serious math up front to figure it out - if at all.

The moral of the story is that it probably makes no sense to use a dashed pen with **-T**.  if you just want to draw dashed gridlines on top then use -B.  Note that even if we delayed all the outlines until all the polygons were painted then you would get a very similar mess except for the loss of half line thicknesses.  But you would not get nice dashed lines with the same dash lengths.

Open to suggestion if you think we need to "warn" the user on the man page that dashed lines makes no sense

**Comment by PaulWessel** [comment]
The lines are all of the same width but half of them are overprinted by the next green square as we plot from N to S or whatever the order is.

Dotted lines are just short dashes so similar.

**Comment by PaulWessel** [comment]
Not entirely sure, but there are several things going on that interfere with the lines:

1. Dashed lines will not be synced so the dashes along one side will not be aligned with dashes on the neighboring tile
2. The order of plotting tiles may affect what we see.

The odd fat-thin dots you see are probably a combination of the cropped half-line (the thin part on the upper tile) and the uncropped and horizontally shifted fat pen on the lower time.

**Comment by PaulWessel** [comment]
Can we close this one, @joa-quim ? There is nothing to do here since we cannot do the outlines after laying down the tiles since part of tiles and lines are blocked as we build the 3-D view from back to front.

**Comment by joa-quim** [comment]
If there is nothing that can be done ... it's solved (there is a Portuguese saying that says exactly this).
