### ISSUE TITLE
Add a workflow to check that new dvc files are on the DAGsHub remote

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/gmt#6433]
**Description of the problem**

We need to add a workflow that verifies that any cache files associated with modifications to the .dvc files are pushed to the DAGsHub repository and prevents merging when the dvc files haven't been pushed yet.

**Comment by meghanrjones** [comment]
There isn't a straightforward solution to this, apart from adding a git hook for `dvc push` (which I think isn't in line with GMT's dev strategies). While we could add a workflow that runs ``dvc status --remote origin`` and then scans the output for "Missing cache files", this would be slow because `dvc status` takes the extra step of querying each individual file in the cache. https://github.com/iterative/dvc/issues/5369 describes exactly the feature that we need to simplify this. In the meantime, developers will just need to remember to push files to the cache.

**Comment by PaulWessel** [comment]
I think the more often we do this stuff the easier it will be to do it right.  I am starting to get the hang of this now, slowly.

**Comment by seisman** [comment]
https://github.com/iterative/dvc/issues/5369 has been closed.

As I understand it, we can check if the new DVC files are on the remote by running:
```
dvc data status --not-in-remote --json | grep -v not_in_remote
```

Implemented in PR https://github.com/GenericMappingTools/gmt/pull/7824. If someone forget to run `dvc push`, the Code Validator workflow should fail.
