### ISSUE TITLE
Time stamp (-U) is hiden under images

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6499]
If I do this, I see the Time stamp at it's default position
```
julia> imshow(rand(256,256), U="", Vd=1)
        grdimage  -R0.5/256.5/0.5/256.5 -JX14c/0 -Baf -BWSen -U -n+a -C -P -K > C:\TEMP\GMTjl_tmp.ps
```
however
```
julia> imshow(rand(256,256), U="+o0/0", Vd=1)
        grdimage  -R0.5/256.5/0.5/256.5 -JX14c/0 -Baf -BWSen -U+o0/0 -n+a -C -P -K > C:\TEMP\GMTjl_tmp.ps
```
(or any other position inside the axes) shows no Time stamp.

**Comment by PaulWessel** [comment]
Well, back in 1989 it was implemented to plot outside your main canvas so it is one of the first things to be plotted.  Sounds like you want to

1. Place it inside the plotting box
2. Plot it last (during plot_end) so that it will be on top of anything.

I guess one would handle this the same way I do progress bars and labels in movies: Create a PostScript function that does the timestamp or by default nothing, and then call it at the end (to do nothing or place the stamp).  Of course, I think it will be susceptible to any crazy -X -Y you may be doing.

**Comment by PaulWessel** [comment]
Forgot: So not a bug but a feature.
