### ISSUE TITLE
S="~d4c:+skarrow-0.4+gblack" crashes Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6594]
Tried to find why but the debugger landed on ``gmtapi_extract_argument()`` and the argument of ``isdigit`` in
```
*n_pre = (k >= 0 && key[k][K_MODIFIER] && isdigit (key[k][K_MODIFIER])) ? (int)(key[k][K_MODIFIER]-'0') : 0;
```
key[k][K_MODIFIER] = -3

Ofc, the root of the error is somewhere before but can't reach with with debugging from Julia runs taking 20 sec per step. Anyway, it must be at the parsing of *kustom* symbol

**Comment by PaulWessel** [comment]
Just so I understand, the input has a - instead of / and crashes instead of giving parsing error?

**Comment by joa-quim** [comment]
Yes.

**Comment by PaulWessel** [comment]
That would mean you would ban a hyphen from being allowed in a custom name. Which is fine of course.  I am sure we also do not what a + sign to be part of a custom symbol name either, and not / or special characters.  So perhaps just letters, underscore, and numbers, and we should document that.

**Comment by joa-quim** [comment]
Hmm, why (the - and +)? What the parser will see is the lack of of ``/size``, no?

**Comment by PaulWessel** [comment]
Yes, the parser can check for that, but do we really want symbol names with hyphens etc? I think you have said that looks like subtraction.

**Comment by joa-quim** [comment]
Yes, it does but many people put whatever in file names. See the bloody spaces example.

**Comment by PaulWessel** [comment]
Well, those people need to be punished.

**Comment by PaulWessel** [comment]
I am not sure about decorated lines, but in general if a size is not supplied we expect it in the input file.  But since input is a line I suspect that should not be an option.  I will start by adding a name-checker.  The - and + are not good in names since the + gets wrapped up in modifier searches and the minus looks like subtraction to me too.  THese are shitty names and the user should be told so.
