### ISSUE TITLE
Modifier +s not working when the symbol code is given in the last column of the input

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#66]
**Description of the problem**
According to the documentation, one can simply give x and y coordinates of start and end point when plotting vectors with +s modifier.

https://github.com/GenericMappingTools/gmt/blob/c1a5c7c914116a6ee01eb9c47d3eeb0cf5b48e0b/doc_modern/rst/source/explain_vectors.rst_#L71-L72

**Full script that generated the error**

The following script plots two arrows, one with symbol code in the command line and the other one in the last column of the input.
```
gmt begin GMT_arrows png
echo 0.5 1.5 4.5 1.5 | gmt plot -R0/5/0/5 -Baf -JX1.75i -Sv0.2i+s+b+e -W1.5p -Gred
echo 0.5 3.5 4.5 3.5 v0.2i+s+b+e | gmt plot -R0/5/0/5 -Baf -JX1.75i -S -W1.5p -Gred
gmt end
```
Output figure:
![gmt_arrows](https://user-images.githubusercontent.com/3974108/45501786-363c7a80-b750-11e8-9e63-d04bdaf7ab22.png)

**System information**

* Operating system: macOS
* Version of GMT: 6.0.0 c1a5c7c

**Comment by PaulWessel** [comment]
I am fixing this issue.  I expect using +s in the data file will work unless you are specially formatted coordinates lind ddd:mm:ss since the data parser probably may not handle a sudden switch of column format.  However, I have not checked to see if that is true, but my fix for this issue works. I will create a pull request shortly.
