### ISSUE TITLE
Tocantins border

### ISSUE THREAD

**Issue by gracoba** [GenericMappingTools/gmt#6869]
**Description of the desired feature**
The Brazilian state of **Tocantins** was created on 1988, but its **border**  is not included on GMT database. Is it possible to include it by default on `pscoast `command? 

Thank you

**Are you willing to help implement and maintain this feature?** No

**Comment by PaulWessel** [comment]
We shall see what can be done.  Perhaps @Esteban82 can wield his magic?

**Comment by Esteban82** [comment]
Yes, sure. Can you share its border? And the border of the other states that were affected?

**Comment by gracoba** [comment]
Hi,
how can I share the database? Is it useful the shape file provided by IBGE (Brazilian Statistics and Geographic) on the following link?
https://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2021/Brasil/BR/BR_UF_2021.zip

**Comment by joa-quim** [comment]
Please consider using GADM. This is the same kind of issue of people wanting improvements in the gshhs database. We cannot do this on user demand.

**Comment by PaulWessel** [comment]
True, one band aid after the other gets old.

**Comment by Esteban82** [comment]
@gracoba have you check the borders in gmt-dcw? Does it work for you?

**Comment by Esteban82** [comment]
> Your problem is with the GSHHG data, right? I.e. what command do you run? gmt coast -N2 ?

**Comment by gracoba** [comment]
@Esteban82 

I was following an tutorial on pyGmt (https://www.pygmt.org/latest/gallery/maps/borders.html#sphx-glr-gallery-maps-borders-py) , and I am supposing the line below is the equivalent to `gmt coast -N2`:

`fig.coast(borders=["1/0.5p,black", "2/0.5p,red", "3/0.5p,blue"], land="gray")`

I checked the dcw_states.txt file, and Tocantins  is there and I can see it on the map available on https://www.soest.hawaii.edu/pwessel/dcw/.

Thanks

**Comment by joa-quim** [comment]
Can we close this?

**Comment by Esteban82** [comment]
The borders are ok (as far as I know) in DCW. But in GSHHG is missing. 

I don't know well how to edit the GSHHG file. I still want to update the -N2 borders for Argentina. 


![tocantis](https://user-images.githubusercontent.com/17908951/179420660-1202bf40-57fc-4ec6-9ba4-84df8cb6d75c.png)

**Comment by joa-quim** [comment]
The GSHHG, whose change depends on GMT4 code/libs, is not going to be changed anymore (unless Paul thinks that's how he will buy a ticked to Heaven).

**Comment by PaulWessel** [comment]
I am sure after a few years in Norway I may wish for tickets to warmer places.

Perhaps instead of spending lots of time band-aiding the ancient GSHHG data compilation, we should instead explore how much work it might be to build GSHHG3.  I think this may be a reasonable starting point:

1. The closed polygons of all islands and continents from **OpenStreetMap**
2. The closed polygons of all lakes and islands in lakes and so on from **HYDROLakes**
3. The administrative boundaries from GADM.

The first two should allow us to build a GSHHG version higher than "full", while the GADM would let us build a replacement for DCW.  As is the case today, these two datasets will not be 100% compatible as the OSM coastline seems to be of higher resolution than the GADM.  It is possible for clever programmers with time on their hand to find the coastal GADM lines and replace then somehow with OSM, but unclear if such people are lining up for this task.  However, it could come down the road - we live with the same problem right now and the discrepancy between OSM and GADM should be much smaller than the shits between DCW and GSHHG (in addition to being more accurate).

If all the closed polygons can be had for GSHHG3 I think all the old GMT4-based processing code can be used with minor changes (need to allow for an even higher resolution than full) to build _GSHHG_binned_u.nc_ for ultra.

I am interested in building GSHHG3 but I cannot spend all my time on this - I sacrificed that time in making GSHHG2. However, I can help and supervise and collaborate on it and fix the source to make it happen.  Maybe @Esteban82 would think his spare time is better spent on something new than the old?

PS. How can I find that posting a year or more ago with the plots of various data sets and their accuracy?

**Comment by Esteban82** [comment]
Maybe in a future I could find some time deal with GSHHG. 

BTW, I think that this issue should be move to gshhg-gmt repository. I don't know how to do it (and probably I don't have the permissions neccesary).

**Comment by joa-quim** [comment]
I'm going to close this as I don't think it will be addressed in a foreseeable future.
