### ISSUE TITLE
Add long-options to surface module

### ISSUE THREAD

**Issue by rbdavis** [GenericMappingTools/gmt#6880]
**Description of the desired feature**

Add long-options to surface module

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
Down the road we will need to consider how to document these options in our documentation. Many UNIX tools have the same issue.  Here are a few lines from the grep man page on the command line:

```
     -A num, --after-context=num
             Print num lines of trailing context after each match.  See also the -B and -C options.
```

So perhaps we would do the same, e.g.,

```
  -S<search_radius>[m|s] --searchradius=<radius>[m|s]
     Set <search_radius> to initialize grid; default = 0 will skip this step. This step is slow and not needed unless grid dimensions are pathological;
     i.e., have few or no common factors. Append m or s to give <search_radius> in minutes or seconds.
```

I note that in the grep synopsis they only list the short version when there is long and short, and then they have newer options that only exist in short form.  This, of course, is a good model for GMT as well since we have run out of letters in many modules (same problem the UNIX tools faced).

**Comment by anbj** [comment]
Please include a comma, separating the short and long option (as in *grep*).  And ‘search_radius’ -> ‘search-radius’? Easier to read.

**Comment by PaulWessel** [comment]
search-radius will be seen as a subtraction in Julia so we cannot use hyphens.

**Comment by anbj** [comment]
I never thought I would hear or see a drawback against Julia. @joa-quim, explain thy.

**Comment by joa-quim** [comment]
Julia, like Matlab are sane languages where a **-** means subtraction. Not like certain languages where a **+** applied to numbers means concatenation
```
>>> [1, 2, 3, 4] + [5, 6]
[1, 2, 3, 4, 5, 6]
```
