### ISSUE TITLE
Add ffmpeg as an optional dependency

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#732]
**Description of the problem**

`gmt movie` needs ffmpeg to generate animations in MP4 and webm formats. We should list it as an optional dependency and maybe check its availability during cmake configuration.

**Comment by PaulWessel** [comment]
Good point, but this also brings up the fact that gmt movie **-A** uses GraphicsMagick (**gm**) to make animated GIFs as well.  Because movie is new and not (yet) essential to GMT users I think we should do this:

1. Explain in our installation document that movie requires **ffmpeg** to build movies and **gm** to build animated gifs.
2. Let cmake warn if these are not installed and state that movie won't be able to do such and such.

It is conceivable that some people will just use gmt movie to build a stash of PNG files and then use other tools (QuickTime, Movie, MovieMaker) to generate a movie from them, so it is still useful even if **ffmpeg** and **gm** are not there.

**Comment by PaulWessel** [comment]
Closed as implemented.
