### ISSUE TITLE
Non-existent code in coast -E produces garbage -R

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#7476]
If a non-existent code is supplied to **coast -E**, and, it's the only code supplied, **coast** prints garbage.

Current output:

```
$ gmt pscoast -Edoesnotexist
pscoast [WARNING]: No country code matching doesnotexist (skipped)
pscoast [WARNING]: Column selected for latitude-formatting has values that exceed +/- 90; set to NaN
pscoast [WARNING]: Column selected for latitude-formatting has values that exceed +/- 90; set to NaN
-R0/0/NaN/NaN
```

If **coast** gives a bad -R, you might as well don't print anything at all.

Suggested output:

```
$ gmt pscoast -Edoesnotexist
pscoast [WARNING]: No country code matching doesnotexist (skipped)
[nothing more]
```

If you supply *more codes*, that does exist, the output is reasonable.
A valid `-R` is given, and a warning:

```
$ gmt pscoast -Edoesnotexist,NO
pscoast [WARNING]: No country code matching doesnotexist (skipped)
-R4.650158/31.138197/57.966579/71.18811
```

**Comment by joa-quim** [comment]
> pscoast [WARNING]: Column selected for latitude-formatting has values that exceed +/- 90; set to NaN

The double warning could be removed, but not **returning** the garbage would be a bad idea. And I emphasized the *returning* because that's the reason why it would be a bad idea. No problems for GMT CLI that doesn't return anything but for the wrappers that are expecting a return value that could mean extra troubles.

**Comment by anbj** [comment]
Hmm, yes I see the point; the wrapper *needs* to have some kind of return value?

For CLI then, this looks weird and not useful.
The code does not exist, yet the longitude range is ``0/0`` and the latitude range ``NaN/NaN``.

**Comment by PaulWessel** [comment]
No offence, but here is a point we need to remember:

GMT and similar software are typically written BY and FOR scientists.  That is and was our target audience.
For commercial software, an inordinate amount of time goes into vetting the users answers and options and settings so that they cannot to crazy stuff without being kindly told that “so and so is not allowed or so and so needs to be in the 0-5 range”, etc.
The GMT developers have spent time on preventing the most common errors, but it is extremely poor use of a Professor’s time to spend days coding safety valves to yield a nice error message and exit if a user do things like -Ebadcode.  It is the user’s fault for giving junk arguments and for many such options there is no rigorous parse checking as it is just not what I want to spend my time on.  So things may crash with ugly messages and you may get subsequent error message that are not really relevant, like here, but usually lets you figure out the problem.

Those who gets too bothered by these errors are welcome to try to trace through the code, either in text or in a debugger, and suggest or implement modest changes to reduces this annoyance.  We can help a bit with that but fixing actual bugs are more important, no?

**Comment by anbj** [comment]
You’re absolutely right, Paul.
