### ISSUE TITLE
gmt coast should print usage in modern mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#777]
In classic mode, typing `gmt pscoast` will print the module usage.

In modern mode, `gmt coast` will report some errors:
```
$ gmt coast                                                         
pscoast [ERROR]: Syntax error: Must specify -R option
pscoast [ERROR]: Syntax error: Must specify at least one of -C, -G, -S, -I, -N, -Q and -W
```
The same goes for other modules for modern mode, and for `gmt meca`, it crashes.

Is it possible that `gmt coast` can print the full usage?

**Comment by PaulWessel** [comment]
There are some issues with this. For instance, gmt plot by itself may be a valid modern mode command if **-R -J** has already been set and the data are piped in.  We would only be able to check that by detecting a session has started and **-R -J** has been set.  Even then, we do not know the intention of the user.  However, I think "gmt plot" may be the only "valid" command and I would be OK insisting the user add **-W**_pen_ to get what they want here, otherwise it should be "show me usage".
I will have to see how this may be implemented.

**Comment by PaulWessel** [comment]
I propose that all plot modules in _modern_ mode must supply an explicit option. Currently, I think only two modules could be used in a script where **-R -J** is set explicitly by earlier modules and you could do things like

cat my data | gmt clip
cat my_points | gmt plot

Since the modules are unaware of the stdin stream we would have to allow

gmt clip
gmt plot

to wait for input rather than print the usage message.  This seems too far out for me, hence the suggestion of requiring an option (or file) to run the module.  While for plot there is no problem (give **-W**_pen_ instead of relying on a default), with clip there is no option to activate clipping.  There is **-C**[**a**|_n_] to deactivate but the default is to activate.  Hence, to get cat my_data | gmt clip to take an option we need to invent one.  My suggestion would be **-Cb** for begin clipping, and let that be the default.  Let me know what @GenericMappingTools/core think.

**Comment by PaulWessel** [comment]
Note that this would also apply to gmt info under modern mode.  cat file | gmt info currently works in classic but if run in modern mode an option would be required, such as **-Id** for default behavior.

**Comment by joa-quim** [comment]
Confusing. I see no meaning in asking for the module's usage in the middle of modern session. Since a ``gmt begin`` has already been issued, user has only to know what he wants to do. Also, obliging to give 
needless options seems to go contrary to the simplification route.

I would say that to be able to use the modern name in asking online usage, the more logic is to ask it explicitly with, e.g. ``gmt coast -`` or ``gmt coast -?``

**Comment by PaulWessel** [comment]
It is a good point.  I am trying to avoid the ugliness of

gmt coast
pscoast [ERROR]: Syntax error: Must specify -R option
pscoast [ERROR]: Syntax error: Must specify at least one of -C, -G, -S, -I, -N, -Q and -W

and

gmt text
pstext [ERROR]: Syntax error: Must specify -R option

at the same time things like

gmt ternary

just sits there (as does clip, contour, mask, wiggle).  It seems inconsistent.  Calls like "gmt logo" gives usage message but per documentation has no required options...
Maybe I need to figure out a way for gmt text, coast, legend, and a few others that do require an argument to instead give the usage?

**Comment by joa-quim** [comment]
What about just changing the error message and instead of saying that it need such or such options it just says

gmt coast
pscoast [ERROR]: In modern mode to ask for 'coast' usage you must explicitly ask it with either 'gmt coast -' or 'gmt coast -?'

**Comment by PaulWessel** [comment]
That is one option.  That means gmt plot, clip, wiggle etc will still quietly sit there awaiting input, but those that require an option would issue your message.  I will test to see how hard to do.  I would need to (1) detect it is a modern mode call (new names such as coast) and then insert that message instead of calling usage.  Presumably, gmt trend1d etc should be assumed to be classic and do what they have done in the past.

**Comment by seisman** [comment]
> 
> gmt coast
> pscoast [ERROR]: In modern mode to ask for 'coast' usage you must explicitly ask it with either 'gmt coast -' or 'gmt coast -?'

I like this idea.

**Comment by PaulWessel** [comment]
OK, two against one.  I will do as you wish, but later.

**Comment by seisman** [comment]
This is what I got with GMT 6.0.0_bffddd2_2019.06.13.

```
gmt meca                                                                                  
[1]    3106 abort      gmt meca
```

```
gmt meca -Vd                                                                            
gmt [DEBUG]: Obtained the ppid from parent: 79966
gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl
gmt [DEBUG]: GMT->session.SHAREDIR = /opt/GMT-6.0.0/share
gmt [DEBUG]: GMT->session.HOMEDIR = /Users/seisman
gmt [DEBUG]: GMT->session.USERDIR = /Users/seisman/.gmt [created]
gmt [DEBUG]: GMT->session.CACHEDIR = /Users/seisman/.gmt/cache [created]
gmt [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
gmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
gmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /Users/seisman/.gmt
gmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /Users/seisman/.gmt/postscriptlight
gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /opt/GMT-6.0.0/share/postscriptlight
gmt [DEBUG]: GMT: 5. gmt_getsharepath failed
gmt [DEBUG]: Map distance calculation will be Cartesian
gmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
gmt [DEBUG]: Enter: New_PSL_Ctrl
gmt [DEBUG]: Exit:  New_PSL_Ctrl
gmt [DEBUG]: Enter: gmt_manage_workflow
gmt [DEBUG]: Exit : gmt_manage_workflow
gmt [DEBUG]: Enter: PSL_beginsession
gmt [DEBUG]: Exit : PSL_beginsession
gmt [DEBUG]: Enter: PSL_setdefaults
gmt [DEBUG]: Exit : PSL_setdefaults
gmt [DEBUG]: Enter: gmtlib_io_init
gmt [DEBUG]: Exit : gmtlib_io_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: The PROJ_GEODESIC set to Vincenty
gmt [DEBUG]: Enter: gmt_getdefaults
gmt [DEBUG]: Exit:  gmt_getdefaults
gmt [DEBUG]: Enter: gmtlib_plot_C_format
gmt [DEBUG]: Exit:  gmtlib_plot_C_format
gmt [DEBUG]: Enter: gmtinit_get_history
gmt [DEBUG]: Initialize FFTW with 8 threads.
gmt [DEBUG]: GMT_Create_Session initialized GMT structure
gmt [DEBUG]: Shared Library # 0 (core). Path = libgmt.dylib
gmt [DEBUG]: Loading core GMT shared library: libgmt.dylib
gmt [DEBUG]: Loading GMT plugins from: /opt/GMT-6.0.0/lib/gmt/plugins
gmt [DEBUG]: Shared Library # 1 (supplements). Path = /opt/GMT-6.0.0/lib/gmt/plugins/supplements.so
gmt [ERROR]: Shared GMT module not found: meca

ERROR: No module named meca was found.  This could mean one of four cases:
  1. There actually is no such module; please check your spelling.
  2. You used a modern mode module name while running in GMT classic mode.
  3. Module exists in the GMT supplemental library, but the library could not be found.
  4. Module exists in a GMT custom library, but none was specified via GMT_CUSTOM_LIBS.
Shared libraries must be in standard system paths or set via environmental parameter DYLD_LIBRARY_PATH.

gmt [DEBUG]: Entering GMT_Destroy_Session
```

```
gmt meca -                                                                                    
gmt meca [seis] 6.0.0_bffddd2_2019.06.13 [64-bit] - Plot focal mechanisms on maps

usage: gmt meca [<table>] -J<args> -R<west>/<east>/<south>/<north>[+r]
	-S<format><scale>[/<fontsize>[/<offset>]][+u] [-B<args>]
	[-C[<pen>][+s<pointsize>]] [-D<depmin>/<depmax>] [-E<fill>] [-G<fill>] [-L<pen>] [-M]
	[-Fa[<size>[/<Psymbol>[<Tsymbol>]]] [-Fe<fill>] [-Fg<fill>] [-Fo] [-Fr<fill>] [-Fp[<pen>]] [-Ft[<pen>]] [-Fz[<pen>]]
	[-N] [-T<nplane>[/<pen>]] [-U[<label>][+c][+j<just>][+o<dx>/<dy>]] [-V[<level>]] [-W<pen>]
	[-X[a|c|f|r]<xshift>[<unit>]] [-Y[a|c|f|r]<yshift>[<unit>]] [-Z<cpt>]
	[-c[<row>,<col>]] [-di<nodata>] [-e[~]<pattern>] [-h[i|o][<nrecs>][+c][+d][+r<remark>][+t<title>]]
	[-i<cols>[+l][+s<scale>][+o<offset>][,...]]
	[-p[x|y|z]<azim>[/<elev>[/<zlevel>]][+w<lon0>/<lat0>[/<z0>][+v<x0>/<y0>]]
	[-t<transp>] [-:[i|o]] [--PAR=<value>]
```

**Comment by PaulWessel** [comment]
OK, am looking at this.  It is confusing what we decided.  Here is what I think we agreed to above (under classic mode there should be no change, this is all about modern mode):

1. gmt _module_ with no arguments should print _You must give -? to get usage_ and exit
2. Exceptions are modules that can run with no arguments (e.g., plot, info, wiggle). Those will just sit there and wait for i/o.

There are some problems with this.  In classic mode there are three modules (regress, info, convert) that are flagged as _special_, meaning they can run with no arguments.  E.g., in classic mode, if you type gmt info it sits and waits for input.  In modern mode there are potentially many more modules that could be special, since all those that require **-R -J** can now get those without options.  That means plot, wiggle, etc. could theoretically be run in a gmt modern script with no options (i.e., `cat data | gmt plot`). And because a missing **-R** means we obtain it from the data and a missing **-J** sets a default projection, many modules are special.  Finally,` gmt plot` with no args means "read from standard input".  But there are no data, and plot will wait for input so that it can read and determine the region to make a **-R**.  This never happens until you hit Ctrl-D of something and it crashes.  It is hard for GMT to detect that input is a stdin at that point in the execution.  The module has passed way down to the reading of data section when it realizes there is stdin, and even then it cannot know if there is anything coming or not.

I think it may be safest to only allow info, convert, and regress (none of which requires **-R -J**) to operate without arguments in modern mode, and let everybody else require options.  For instance, `cat data | gmt plot `would draw a default pen line but it is clearer to say `cat data | gmt plot -W0.25p`.  I don't think we loose much by disallowing a few plotting modules from having no arguments.  It also would mean modern and classic behaves the same way with respect to usage message.

So I propose to force printing of usage message in exactly the same situations that they are printed in classic mode.

**Comment by seisman** [comment]
I still prefer `cat data | gmt plot` in modern mode. It's much simpler and more elegant than `cat data | gmt plot -W0.25p`.

**Comment by PaulWessel** [comment]
But I cannot tell if there is a cat data part.  I cannot tell gmt plot from cat data | gmt plot.  In both cases there are no arguments and in both cases GMT will think there is data coming via stdin.  This is the same with meca, no? gmt meca with no arguments means get data from stdin. Right now meca has no required arguments. IS there a default for -S?

**Comment by seisman** [comment]
I think psmeca has a bug here. -S is not required, but -S doesn't have a default value. If -S is not specified, then psmeca won't draw any beachball.

**Comment by seisman** [comment]
Let's focus on `gmt plot` now.

Running `gmt plot -Vd` alone gives:

```
gmt plot -Vd
gmt [DEBUG]: Obtained the ppid from parent: 13103
gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl
gmt [DEBUG]: GMT->session.SHAREDIR = /opt/GMT-6.0.0/share
gmt [DEBUG]: GMT->session.HOMEDIR = /Users/seisman
gmt [DEBUG]: GMT->session.USERDIR = /Users/seisman/.gmt [created]
gmt [DEBUG]: GMT->session.CACHEDIR = /Users/seisman/.gmt/cache [created]
gmt [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
gmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
gmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /Users/seisman/.gmt
gmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /Users/seisman/.gmt/postscriptlight
gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /opt/GMT-6.0.0/share/postscriptlight
gmt [DEBUG]: GMT: 5. gmt_getsharepath failed
gmt [DEBUG]: Map distance calculation will be Cartesian
gmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
gmt [DEBUG]: Enter: New_PSL_Ctrl
gmt [DEBUG]: Exit:  New_PSL_Ctrl
gmt [DEBUG]: Enter: gmt_manage_workflow
gmt [DEBUG]: Exit : gmt_manage_workflow
gmt [DEBUG]: Enter: PSL_beginsession
gmt [DEBUG]: Exit : PSL_beginsession
gmt [DEBUG]: Enter: PSL_setdefaults
gmt [DEBUG]: Exit : PSL_setdefaults
gmt [DEBUG]: Enter: gmtlib_io_init
gmt [DEBUG]: Exit : gmtlib_io_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: The PROJ_GEODESIC set to Vincenty
gmt [DEBUG]: Enter: gmt_getdefaults
gmt [DEBUG]: Exit:  gmt_getdefaults
gmt [DEBUG]: Enter: gmtlib_plot_C_format
gmt [DEBUG]: Exit:  gmtlib_plot_C_format
gmt [DEBUG]: Enter: gmtinit_get_history
gmt [DEBUG]: Initialize FFTW with 8 threads.
gmt [DEBUG]: GMT_Create_Session initialized GMT structure
gmt [DEBUG]: Shared Library # 0 (core). Path = libgmt.dylib
gmt [DEBUG]: Loading core GMT shared library: libgmt.dylib
gmt [DEBUG]: Loading GMT plugins from: /opt/GMT-6.0.0/lib/gmt/plugins
gmt [DEBUG]: Shared Library # 1 (supplements). Path = /opt/GMT-6.0.0/lib/gmt/plugins/supplements.so
gmt [ERROR]: Shared GMT module not found: plot

ERROR: No module named plot was found.  This could mean one of four cases:
  1. There actually is no such module; please check your spelling.
  2. You used a modern mode module name while running in GMT classic mode.
  3. Module exists in the GMT supplemental library, but the library could not be found.
  4. Module exists in a GMT custom library, but none was specified via GMT_CUSTOM_LIBS.
Shared libraries must be in standard system paths or set via environmental parameter DYLD_LIBRARY_PATH.

gmt [DEBUG]: Entering GMT_Destroy_Session
```
The error message shows GMT cannot find `gmt plot`. I know it's classic mode, but I remember we discussed to allow `gmt plot` in classic mode, so users can see some usage in a terminal. Does this mean GMT still cannot find `gmt plot` in classic mode?

**Comment by PaulWessel** [comment]
OK. Yes, since gmt.c calls GMT_Call_Module with "plot" it ends up calling GMT_plot which says

```
int GMT_plot (void *V_API, int mode, void *args) {
	/* This is the GMT6 modern mode name */
	struct GMTAPI_CTRL *API = gmt_get_api_ptr (V_API);	/* Cast from void to GMTAPI_CTRL pointer */
	if (API->GMT->current.setting.run_mode == GMT_CLASSIC) {
		GMT_Report (API, GMT_MSG_NORMAL, "Shared GMT module not found: plot\n");
		return (GMT_NOT_A_VALID_MODULE);
	}
	return GMT_psxy (V_API, mode, args);
}

```

So we cannot even get there unless we  flag in gmt.c that this module has no arguments and then I could pass that if test and call psxy.  There is no session yet.

**Comment by seisman** [comment]
Just tried to "debug" it by adding following statement before the if test.
```
fprintf(stderr, "%d %d %d\n", API->GMT->current.setting.run_mode, GMT_CLASSIC, GMT_MODERN);
```

For `gmt plot`, the output is `1 0 1`, while `gmt plot -Vd` gives `0 0 1`.

**Comment by PaulWessel** [comment]
Hm, and when I run gmt plot by itself it says

```
pwessel@macnut:~/GMTdev/gmt-dev/src-> gmt plot
PSL:../src/postscriptlight.c:5756: PSL_fopen error: Unable to open file /Users/pwessel/.gmt/sessions/gmt6.544/gmt_0.ps- with mode w!
psxy [ERROR]: Cannot open /Users/pwessel/.gmt/sessions/gmt6.544/gmt_0.ps- with mode w

```

So I see in gmt.c I call gmt_check_if_modern_mode_oneliner and it is the one that sets it to 1:

```
void gmt_check_if_modern_mode_oneliner (struct GMTAPI_CTRL *API, int argc, char *argv[], bool gmt_main) {
	/* Determine if user is attempting a modern mode one-liner plot, and if so, set run mode to GMT_MODERN.
	 * This is needed since there is not gmt begin | end sequence in this case.
	 * Also, if a user wants to get the usage message for a modern mode module then it is also a type
	 * of one-liner and thus we set to GMT_MODERN as well, but only for modern module names. */

```

But clearly this has side-effects since being modern means there is a session etc and for me that ends up badly with the PostScript file.

Did we not agree some weeks ago that to get usage message for modern modules on the commandline like this we need to add -?.  So gmt plot -? works fine.

**Comment by seisman** [comment]
Let's assume I'm a new GMT user, and i'm using 6.0.0. I know nothing about classic mode or modern mode, and someone told me I can use `gmt plot` to plot some lines or symbols.

Then, I open a terminal, type `gmt plot` and expect to see some usage message, just like most other Linux commands do. However, what I see is 😭 
```
[1]    20821 abort      gmt plot
```

**Comment by PaulWessel** [comment]
Yes I agree, we dont want that.  But there is now a confusion between a legitimate one-liner modern mode commands:

`gmt plot stuff -R.. -J.. -png map
`

and modern mode names being used just to get usage (like your case).  I will have to see how to separate those.

**Comment by joa-quim** [comment]
For me it tells why
```
gmt plot
PSL: PSL_fopen error: Unable to open file C:/j/.gmt/sessions/gmt6.16752/gmt_0.ps- with mode w!
psxy [ERROR]: Cannot open C:/j/.gmt/sessions/gmt6.16752/gmt_0.ps- with mode w
```

I would rather force that all online help commands require ``-`` or ``-?`` on modern mode then to force ``cat data | gmt plot -W``

**Comment by seisman** [comment]
See #910. This explains why I always got a segment fault with `gmt plot`. After #910 is fixed, `gmt plot` will wait for stdin.
