### ISSUE TITLE
grdinterpolate -S is broken for externals passing a memory cube

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7940]
The beginning
```
julia> grdinterpolate(cube, S=[606200 4213440.5])
grdtrack [ERROR]: GMT_Read_Data: Wildcards only allowed for DATASET. Use GMT_Read_Group to read groups of other data types
String[]
```

This happens because in grdinterpolate#L604

```
sprintf (grid, "%s?%s[%" PRIu64 "]", Ctrl->In.file[0], cube_layer, k);
```
results in

```
grid = @GMTAPI@-S-I-U-U-U-N-000035?[0]
```

Because of the trailing ?[0] the GMT_Get_FilePath() fails to detect it as a memory file in

```
if (gmt_M_file_is_memory (file)) return GMT_NOERROR;	/* Memory files are always fine */ 
```
and picks it as a nc variable because of the '?' and the return value is simply "?[0]" that
later in GMT_Read_Data() falls under the codition   strpbrk (infile, "*?[]")  in

```
if (!gmt_M_file_is_remote (infile) && !gmt_M_file_is_url(infile) && infile && strpbrk (infile, "*?[]") && !gmtapi_file_with_netcdf_directive (API, infile)) {
```

and the final error pops up. Now, as I understand it the `?[n]` is for selecting layers of a netcdf file but that doesn't work for in-memory cubes, so I don't know what is the solution here.

**Comment by PaulWessel** [comment]
We could fix the macro to do this

`#define gmt_M_file_is_memory(file) (file && !strncmp (file, "@GMTAPI@-", GMTAPI_PREFIX_LEN) && strlen (file) >= GMTAPI_MEMFILE_LEN)
`

That way it will be recognised even if there are` ?[layer] `at the end (`>= vs ==`).

Next, we allow the `@GMTAPI@-S-I-U-U-U-N-000035?[0]` filename to be passed without scrutiny and then **grdtrack** will call _GMT_Read_Data_ and then _gmtapi_import_grid_ will need a new trick to point to that layer.  I think `@GMTAPI@-S-I-U-U-U-N-000035?[layer] should be allowed.  I can imagine you also passing layer _n_ of a stack to **grdimage** etc.

If course, you could probably do this in Julia and pass a grid instead of a cube layer, but what fun is it in that?

**Comment by PaulWessel** [comment]
How do a load in a cube? Tried 

C = gmtread("cube.nc",cube=true);
but your gmtread docs do not mention cube, but have no error.

but grdinterpolate sees it as a grid.

grdinterpolate(C, S=[5.5 4.5])
grdinterpolate [ERROR]: Input memory reference is not a cube!

@GMTAPI@-S-I-G-G-G-N-000002 seems to come from Julia since it is in the opt array.

**Comment by PaulWessel** [comment]
Ok, when back please give me steps so I can run either my or your command.

**Comment by joa-quim** [comment]
> C = gmtread("cube.nc",cube=true);
but your gmtread docs do not mention cube, but have no error.

Given the way the keyword/values work no ``kwarg`` pair is actually an error if the parsing in the program doesn't catch the specific case. And because the number of possible _errors_ is infinite what I do is that I _consume_ all valid options and at the end if there are _unconsumed_ I report that as a warning that is a strong indicator of user mistake. This works fine in pure modules but become quite complicated in modules that call other modules (`gmtread` became quite complex).

Anyway, it turns out that you can use `grdinterpolate` to import the cube into memory. *i.e.,*
```
C = grdinterpolate("cube.nc")
```
and then do the
```
grdinterpolate(C, S=[5.5 4.5])
```

**Comment by PaulWessel** [comment]
I did that, but C seems to be a grid.  Dont we want it to be a cube? How (in Julia) can I tell the dimensions of C?

**Comment by joa-quim** [comment]
No, you did `gmtread("cube")` and that reads just one layer (needs fix). What I'm saying is to `grdinterpolate("cube")` and that gives a cube. Possibly not intended but it does what's is needed here. Other option is to update GMT.jl to have the (incomplete) fix that I just committed and do `C = gdalread("cube")`

**Comment by joa-quim** [comment]
If this is all too complicated, leave it. I think I can program the ``grdinterpolate -S`` directly in Julia.

**Comment by PaulWessel** [comment]
I see, so you cannot do something like C{0} to get grid layer 0.  I was imagining people with cubes wanting to pass slices like cube[3] to grdimage and we would then need to handle that slicing in gmtapi_import_grid.

**Comment by joa-quim** [comment]
Sure we can. I said it above. One can do ``slicecube(cube, 1)`` and pass first layer. It has to be a function and not just ``C[1]`` because that's just the first element of the 3D array. And it can't neither (well, it can) be ``C[:,:,1]`` that looses all grid's metadata and passes just a raw 2D matrix. But when we pass a single layer it's a grid that is being passed and not a cube with only one layer (a needless complicated entity).

**Comment by PaulWessel** [comment]
So close this or?

**Comment by joa-quim** [comment]
Yes better close, though this may strike again in another circumstance. I hope that then we will still remember about this.
