### ISSUE TITLE
Problematic short options for conversion from long-options

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7985]
Long-options were conceived years to decades after the standard short-form command options were created for ~150 modules (in addition to the common options **-R -J** etc). The translation from long-options (e.g., **--region**=w/e/s/n) to short option (e.g, **-R**w/e/s/n) need to be unique.  The following is a (probably incomplete) list of options I have flagged for consideration by @rbdavis to see if they break the new rules.  For some options a solution could be a backward compatible change to short-options syntax so it fits our long-option framework, or alternatively these are common enough that we need to enhance the long-option parser or possibly enhance the **GMT_KEYWORD_DICTIONARY** structure to accept more information that allows the parsing to succeed in the cases below.

## Very similar or identical options expecting a letter soup with our without commas

These specify one or more codes, i.e., directives, typically back to back but sometimes with commas:

```
-Afields		e.g. -Axslhw block*.c
-C[xycnpago]		e.g. -Cxyc in spectrum1d.c
-Cx|e,y|n,z|v		e.g, -Ce,v in potential/earthtide.c
-D[a][c][o][n]		e.g. -Dan in grdgradient.c
-Fflags			e.g. -Ffmnsc  fitcircle.c
-Fflags			e.g, -Frsy in project.c
-Fxymrw|p|P|c		e.g. -Fxm in trend1d.c
-Fxyzmrw|p		e.g. -Fxyr in trend2d.c
-Fflags			e.g. -Ffaa,depth in x2sys/x2sys_get.c
-Fflags			e.g. -Fxytz in x2sys/x2sys_list.c
-Fname1,name2,…,	e.g. -Flon,lat,depth in x2sys/x2sys_datalist.c
-Iflags			e.g. -Icfglrsz in gmtselect.c
-Iflags			e.g, -ICF in grdselect.c
-I[c][z]		e.g. -Icz in grd2cpt.c
-I[c][z]		e.g. -Icz in makecpt.c
-L[t][r]		e.g. -Lrt in greenspline.c
-M[h][v]		e.g. -Mvh in potential/gmtflexlure.c
-M[h][v]		e.g. -Mhv in potential/gravprisms.c
-M[h][v]		e.g. -Mvh in potential/talwani2d.c
-M[h][v]		e.g. -Mvh in potential/talwani3d.c
-S[x][y]		e.g. -Sxy in gmtinfo.c
-Sflags			e.g. -Say in spotter/gmtpmodeler.c
-Sflags			e.g. -SXY in spotter/grdpmodeler.c
-Tdcna			e.g. -Tda in pssolar.c
-T[h][d[[~]<cols>]]	e.g. -Thd2:4 in gmtconvert.c
-Z[flags]		e.g. -STLbw in grd2xyz and xyz2grd
```

Question: Can we use **-Fa,b,c,d** to have 4 long-format directives **aname, bname,cname,dname** and parse `--fields=cname,bname back` to **-Fc,b** or **-Fcb** ?

## These may violate the rules since short-form has = or :

```
-Aout_img[=driver]		e.g. -Amap.tif=Geotiff in grdimage.c ?
-Dselection			e.g, -Ddata=earth_age in gmtget.c ?
-Fcolumns[,logic][:bittests]	e.g. -Fdist,faa,grav12_2:+faa in mgd7/mgd77list.c
```

## Almost same as near-common -I but has optional directive x so I think we do this one separately in the module include. --inc=steps:5/4 ?

`-I[x]<xinc>[+e|n][/<yinc>[+e|n]]	e.g. -Ix5/4 in grdbarb.c and grdvector.c`

## Comma separated arguments, problem, or just one string argument?

`-N[p|P|f|F|c|C|s|S|x]n,...	e.g.  -NP0,P2,F3 in trend1d.c`

## Repeatable options:

`-Qb|i|u|x|yvalue		e.g.,  -Qb2 -Qx50 in segy/*segy*.c`

Let me know what is not possible at the moment, and how to best handle the **-F**_flags_ variant since that seems pretty extensively used.

**Comment by rbdavis** [comment]
Here are my opinions on the above questions, many subject to change pending detailed code inspection/enhancement and more extensive experimentation.

The large first **Very similar or identical options expecting a letter soup** block of problematic command options in the original post of this thread are, with two exceptions (see next paragraph), of the form **-X**_flagset_ where _flagset_ is a set of single-letter directives from which the user can typically specify one or more directives in any order, in most cases with no other characters between each pair of adjacent single-letter directives or, in one particular case, with a comma between each such pair. The current longoption translator does not support longoption usage in any of these cases where it is desired to specify more than a single directive other than by specifying all of the shortoption directives in their current form as a single text string, e.g.,

`blockmedian --fields=xslhw
`

There are two command options in this first block, however, which do not follow this pattern, namely

```
-Fflags                 e.g. -Ffaa,depth in x2sys/x2sys_get.c
-Fname1,name2,…,        e.g. -Flon,lat,depth in x2sys/x2sys_datalist.c
```

In these two cases there are actually no directives specified but rather a set of arbitrary character strings separated by commas. These commands should be translatable via existing longoption translation code, e.g.,

`--column_names=lon,lat,depth
`

provided that such options are not multi-section options which use the comma as a section separator (like the **-qi** and **-qo** common options).

There are three commands specified in the second block labeled **These may violate the rules since short-form has = or :** . Of these, the first two are translatable via existing longoption translation code despite the fact that they include a = character: 

```
-Aout_img[=driver]              e.g. -Amap.tif=Geotiff in grdimage.c ?
-Dselection                     e.g, -Ddata=earth_age in gmtget.c ?
```

This is because neither actually includes a directive, but rather only a single arbitrary text string argument which happens to contain = .  Curiously, the first of these (from **grdimage**) is currently commented as disallowed in the **grdimage_inc.h** file, possibly because that module was longoptified prior to the July 2023 switch which changed translation syntax. The second **gmtget** option is already longoptified in the **gmtget** longoptions PR which was submitted very recently. The **grdimage_inc.h** file should now be updated to allow the longoption translation.

The third command (**mgd77list**) in this second command block

`-Fcolumns[,logic][:bittests]    e.g. -Fdist,faa,grav12_2:+faa in mgd7/mgd77list.c
`

may indeed be problematic other than simply treating all arguments as a single text string, which might work:

`--columns=dist,faa,grav12_2:+faa
`

(It's very possible or even perhaps likely that the + in this example would be problematically parsed as a modifier, however.)

I believe that the single **-I** command in the next block should work as a module-specific variant of the current **GMT_I_INCREMENT_KW**:

`-I[x]<xinc>[+e|n][/<yinc>[+e|n]]        e.g. -Ix5/4 in grdbarb.c and grdvector.c
`

The single **trend1d** command in the next **Comma separated arguments, problem, or just one string argument?** command block

`-N[p|P|f|F|c|C|s|S|x]n,...      e.g.  -NP0,P2,F3 in trend1d.c
`

can be handled by the current longoption translation only by treating the repeatable comma-separated flag sets as one single text string, e.g.,

`--components=P0,P2,F3
`

Finally, the single **segy**? command in the last **Repeatable options:** command block

`-Qb|i|u|x|yvalue                e.g.,  -Qb2 -Qx50 in segy/*segy*.c
`

should be trivially translatable with current longoption translation code, e.g.,

`--settings=bias:2 --settings=mult:50
`

**Proposed Translation Enhancement**

I believe it may be possible to enhance the current longoption translation code to properly handle the majority of multi-directive examples in the first and largest command block of this thread's original post (but perhaps none of the other problematic option specifications listed in the other command blocks), e.g., to effect a translation such as

`--fruits=apples,pears,bananas ----> -Fapb (or Fa,p,b)
`

This is likely to be easier if two restrictions could be added (which I believe would not disqualify any of the listed commands):

(1) only the last directive may include a value specification, e.g., `--fruits=apples,pears,bananas:5` (as opposed to --`fruits=apples:1,pears:7` which would be disallowed), and it is of course possible that text strings for such value specifications may not work properly if they contain problematic character sequences such as those containing : , = , etc.; and

(2) no multi-section processing (like that of **GMT_I_INCREMENT_KW**) would be supported (especially anything using comma as a section separator).

I would probably enlarge the translation table entry structure by one field to declare that a particular option does or does not have multi-directive support with or without commas emitted during translation via new constants such as **GMT_MULTIDIR_DISABLE**, **GMT_MULTIDIR_NOCOMMA** and **GMT_MULTIDIR_COMMA**.

**Comment by PaulWessel** [comment]
Sounds pretty good @rbdavis. Yes I do think the arbitrary listing of actual directives need a solution and I do not think they take further arguments per directive.  Sometime these may be an argument and of course modifiers, but where often it is -Fapb7+r so that could be --stuff=appes,pears,bananas:7+remove_skin.

**Comment by rbdavis** [comment]
OK, then I'll pause on the module list for now starting this coming week and begin working on the multi-directive translation feature as proposed? If that turns out OK I will first revisit the previously longoptified modules to incorporate it, then resume with the assembly line longoptification process for the remaining modules.
