### ISSUE TITLE
mapproject -L is broken in Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#8012]
```
julia> mapproject([146.54376 -36.04616], dist2line=mat2ds([146.54295 -36.04986; 146.54577 -36.04925; 146.54707 -36.04880; 146.54919 -36.04718; 146.55075 -36.04586]))
mapproject [ERROR]: No filename provided
ERROR: Something went wrong when calling the module. GMT error number = 72

or

julia> gmt("mapproject -L", [146.54376 -36.04616], [146.54295 -36.04986; 146.54577 -36.04925; 146.54707 -36.04880; 146.54919 -36.04718; 146.55075 -36.04586])
mapproject [ERROR]: No filename provided
ERROR: Something went wrong when calling the module. GMT error number = 72
```
weird because KEY for it is there in `mapproject`

**Comment by joa-quim** [comment]
Debugging show a never seen situation. There **two** main inputs that each seems to contain the in-memory files, but the "L" option is empty.

![image](https://github.com/GenericMappingTools/gmt/assets/537321/56233487-30ba-43f7-bc43-ff8e0d090736)

**Comment by PaulWessel** [comment]
Will try to look tomorrow

**Comment by joa-quim** [comment]
Where is the `option` pointer filled? It's when it checks the KEYs? A very similar case is provided by
```
gmtselect([0.5 0.5], F=[0.0 0; 0 1; 1 1; 1 0; 0 0])
```
and this one works well.

**Comment by PaulWessel** [comment]
Grep for “mapproject “ in gmt_init.c and see if the checks in Encode_Options have issues

**Comment by joa-quim** [comment]
Nothing `mapproject` specific there but what I found is the `=` in KEY `LD(=` makes that `takes_mod` is set to 1 in `gmtapi_extract_argument` and then in gmt_api#L13542

```
if (takes_mod == 1)	/* Got some option like -E[+f] but no +f was given so no implicit file needed */
	implicit = false;
````
which does not add the `?` to the 'L' option. If, in the debugger, I set `implicit = true` than the whole command works. 

The `gmtselect -F` isn't actually a equivalent case because the the **-F** KEY does not have a `=` in it. So this is probably a more general problem that was hit only now.

**Comment by PaulWessel** [comment]
I modified _gmtapi_extract_argument_ to set _takes_mod_ to 2 if there are no argument. Now, **-L** gets to be **-L?** and that part works.  The input and output gets assigned correctly:

` Revised options: -L@GMTAPI@-S-I-D-M-T-N-000000 @GMTAPI@-S-I-D-M-T-N-000001 ->@GMTAPI@-S-O-D-D-T-N-000002`

Question: How can I add a branch instead of `GMT#master` so I can debug using that branch and not depend on having to update master before I know a solution is correct?  The fix I did I uploaded to master since it was just one line (`L# 13013`).

Please run your Julia test suite in case my change breaks other things.  Once stable I will do some renaming of constants related to _takes_mod_.  0, 1, and 2 does not remind me of what the hell those mean...

**Comment by PaulWessel** [comment]
Oh, I guess `GMT#master` is correct since that is the Julia wrapper part, not the GMT library which is pointed to by **$GMT_LIBRARY**.

**Comment by joa-quim** [comment]
Yes, you want to use ``GMT#master``, otherwise it would be ``GMT#name-of-the-branch`` but I don't see a situation where you'd need to do that.
