### ISSUE TITLE
Encapsulated GMT Binary tables

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#8047]
I think it is a very good idea to work with native binary tables (I think Joaquim will agree with me). 
But for me, the difficulty is that I must know what was the code (e.g. `-bo1f,1l,1d`) used to convert the original data (this does not happen with ascii tables).

So, my idea is to save that code into the header of the same file. Here I made this script to explain it.

```
#!/usr/bin/env bash

# Make binary file with leading header with info about binary format
# 0. Code for binary (de)coding
code=1u

# A. Creation of file
# ---------------------------------------
# 1. Save code as header 
echo $code > test.b

# 2. Append more data to file on binary format
gmt math -T0/255/1 -o1 -bo$code T = t.b
cat t.b >> test.b

# B. Recover file
# ---------------------------------------
# 1. Get code from first line and create variable
header=$(head -n1 test.b)

# 2. Compute the size of the header in bytes and add 1 (due to LF)
h=$((${#header}+ 1))

# 3. Run gmt convert which will strip off the headers on output
gmt convert test.b -bi$header -hi${h} > out1.txt
```

## Idea 
So, my proposal would be to add a modifier (like `+a`) that would produce that the code used  (`1u` in the example) will be saved in the first line of the new file. This would result in a new type of file (encapsulated GMT Binary table. EGBT).
Then, to recover the file, we could use the same modifier (or maybe another letter). Maybe better, GMT could realize only that the file is an EGBT (it recognizes SHP) and therefore it might not be necessary to add a modifier (`+a`) or `-bi` directly.

```
# A. Creation of file
gmt math -T0/255/1 -o1 -bo1u*+a* T = t.b

# B. Recovery of the file
gmt convert t.b -bi*+a* > out1.txt
```

What do you think?

**Comment by Esteban82** [comment]
From the docs:

"GMT programs also support native binary tables to speed up input-output for i/o-intensive tasks like gridding and preprocessing. This is discussed in more detail in section. Unlike ASCII tables, binary tables do not have any limitations on the number of data columns."

Also I the binary files are generally smallers.

https://docs.generic-mapping-tools.org/dev/reference/file-formats.html#binary-tables

**Comment by PaulWessel** [comment]
The trick is knowing if there is a header and how many bytes it takes up. Since GMT < 6.5 would have no knowledge of the it is basically screwed and cannot read the new binary files.  I am hesitant to consider adding this feature. We could easily do it and it would be find for 6.5 onwards but you will be hard pressed to know what stuff.bin is in either case unless you know exactly what it is. Note there is no "first line of the file" in binary native dumps - which is why we never did it that way.

**Comment by Esteban82** [comment]
Well, the file generated will be a mixed between ASCII and binary. So I think that it shouldn't be call ".bin".

Some options are:

1. Use another extension instead of `.bin` (for example `gbin`, `gmtb`, ... ).
2. Create two files. The tradicional binary file and the other one with the header info (like `.h`).

**Comment by joa-quim** [comment]
Honestly, time for this type of hacks as passed. We now have formats that are self descriptive. NetCDF is one and the new arrow/parquet that also mix ascii and binary will be prevalent. But "GMT does not read them". Yes, that is part of a problem but solution is not to invent new formats. And, BTW, GMT **can read** them but it's a bit autistic and for only talks to GMT.jl

**Comment by Esteban82** [comment]
I agree that would be better that GMT could write NetCDF tables.

**Comment by PaulWessel** [comment]
Given our knowledge of netCDF and how to write new files (grids) it should not be too hard to write a netCDF table.  I'll make a proposal.

**Comment by PaulWessel** [comment]
One issue is that netCDF files are not possible to redirect since different aspects of the file are written at different times.  So that means we must have a file name for output and a way to specify this.  Most table output is simply written to stdout and then redirected to a file.  For netCDF writing (this is the main reason we did not implement writing netcdf files) it may be possible to use the output file redirection, i.e. `'->my file.nc'.`, with quotes needed to escape the > character.  I think that could work provided we detect it is netCDF output so we dont just open that file for regular stdout writing.

```
echo 1 2 3 | gmt convert '->file.txt'
cat file.txt
1	2	3
```

Maybe @remkos has some thoughts on this?

**Comment by joa-quim** [comment]
Maybe close this?

**Comment by Esteban82** [comment]
I could script this if I want to use it. So, it can be closed.
