### ISSUE TITLE
gmtspatial/poldecimate.sh fails on Linux

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#945]
**Description of the problem**

What I get on Linux (N=563 on macOS, and N=533 on Linux)

![image](https://user-images.githubusercontent.com/3974108/59557671-bc227600-8fad-11e9-858f-34b11e46ac09.png)

**Comment by PaulWessel** [comment]
I think when I looked into this it is tied to subtle differences in qsort and since it is iterative, once we get one slightly difference it will continue.  Neither is wrong.  Probably best to set to GMT_KNOWN_FAILURE.

**Comment by joa-quim** [comment]
But then what is the point of running the test?

**Comment by PaulWessel** [comment]
OK, so maybe better to set it to its own high RSM so that if we truly get a
bug it will exceed that level.

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa


On June 15, 2019 at 3:55:25 PM, Joaquim (notifications@github.com) wrote:

But then what is the point of running the test?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/GenericMappingTools/gmt/issues/945?email_source=notifications&email_token=AGJ7IX4YR33RSYDKXRWDQILP2WMQ3A5CNFSM4HYQC6M2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXZDKPA#issuecomment-502412604>,
or mute the thread

**Comment by seisman** [comment]
The RMS error reported by travis CI is 0.0923.

**Comment by PaulWessel** [comment]
Actually, maybe a bug after all.  I am using a nearest neighbor scheme so why are there so many on top of each other at the center.  The Linux look better actually.  I will have a second look.

**Comment by PaulWessel** [comment]
Sorry, not paying attention.  The green dots are the original data and the red are the reduced due to nearest neighbor.  I will try to turn some debug on to see the sequence of decisions.

**Comment by PaulWessel** [comment]
Should be addressed with #956.

**Comment by seisman** [comment]
Fixed by #956 and #957.
